
// this is firebase-node.js with long-polling disabled, some window.* -like
// globals added, and a final "exports.Firebase = Firebase" at the end.

var WebSocket = require("websocket").WebSocket; // must provide this
var setTimeout = require("timers").setTimeout;
var clearTimeout = require("timers").clearTimeout;
var setInterval = require("timers").setInterval;

function g(a){throw a;}var i=void 0,k=!0,m=null,o=!1;function p(){return function(){}}function aa(a){return function(){return this[a]}}function r(a){return function(){return a}}var s,ba=this;function ca(){}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return a!==i}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function fa(a){return"number"==typeof a}function ga(a){return"function"==da(a)}function ha(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return y.apply(m,arguments)}function ka(a,b){function c(){}c.prototype=b.prototype;a.Md=b.prototype;a.prototype=new c};function la(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function ma(){this.$b=i}
function na(a,b,c){switch(typeof b){case "string":oa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if("array"==da(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],na(a,a.$b?a.$b.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),
oa(f,c),c.push(":"),na(a,a.$b?a.$b.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var pa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},qa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function oa(a,b){b.push('"',a.replace(qa,function(a){if(a in pa)return pa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return pa[a]=e+b.toString(16)}),'"')};function ra(a){return"undefined"!==typeof JSON&&t(JSON.parse)?JSON.parse(a):la(a)}function z(a){if("undefined"!==typeof JSON&&t(JSON.stringify))a=JSON.stringify(a);else{var b=[];na(new ma,a,b);a=b.join("")}return a};function sa(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);55296<=e&&56319>=e&&(e-=55296,d++,A(d<a.length,"Surrogate pair missing trail surrogate."),e=65536+(e<<10)+(a.charCodeAt(d)-56320));128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(65536>e?b[c++]=e>>12|224:(b[c++]=e>>18|240,b[c++]=e>>12&63|128),b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};function B(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&g(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function C(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:ta.assert(o,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}return a+" failed: "+(d+" argument ")}
function D(a,b,c,d){(!d||t(c))&&!ga(c)&&g(Error(C(a,b,d)+"must be a valid function."))}function ua(a,b,c){t(c)&&(!ha(c)||c===m)&&g(Error(C(a,b,k)+"must be a valid context object."))};function E(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function va(a,b){if(Object.prototype.hasOwnProperty.call(a,b))return a[b]};var wa={},ta={},xa=/[\[\].#$\/]/,ya=/[\[\].#$]/;function za(a){return v(a)&&0!==a.length&&!xa.test(a)}function Aa(a,b,c){(!c||t(b))&&Ba(C(a,1,c),b)}
function Ba(a,b,c,d){c||(c=0);d||(d=[]);t(b)||g(Error(a+"contains undefined"+Ca(d)));ga(b)&&g(Error(a+"contains a function"+Ca(d)));Da(b)&&g(Error(a+"contains "+b.toString()+Ca(d)));1E3<c&&g(new TypeError(a+"contains a cyclic object value ("+d.slice(0,100).join(".")+"...)"));v(b)&&(b.length>10485760/3&&10485760<wa.Nd.Ld(b).length)&&g(Error(a+"contains a string greater than 10485760 utf8 bytes"+Ca(d)+" ('"+b.substring(0,50)+"...')"));if(ha(b))for(var e in b)E(b,e)&&(".priority"!==e&&(".value"!==e&&
!za(e))&&g(Error(a+"contains an invalid key ("+e+")"+Ca(d)+'.  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),d.push(e),Ba(a,b[e],c+1,d),d.pop())}function Ca(a){return 0==a.length?"":" in property "+a.join(".")}function Ea(a,b,c,d){(!d||t(c))&&(c!==m&&!fa(c)&&!v(c))&&g(Error(C(a,b,d)+"must be a valid firebase priority (null or a string.)"))}
function Fa(a,b,c){if(!c||t(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:g(Error(C(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}function Ga(a,b){t(b)&&!za(b)&&g(Error(C(a,2,k)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}
function Ha(a,b){(!v(b)||0===b.length||ya.test(b))&&g(Error(C(a,1,o)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function Ia(a,b){".info"===F(b)&&g(Error(a+" failed: Can't modify data under /.info/"))};function H(a,b,c,d,e,f,h){this.k=a;this.path=b;this.wa=c;this.da=d;this.pa=e;this.ua=f;this.Qa=h;t(this.da)&&(t(this.ua)&&t(this.wa))&&g("Query: Can't combine startAt(), endAt(), and limit().")}H.prototype.pc=function(a,b){B("Query.on",2,4,arguments.length);Fa("Query.on",a,o);D("Query.on",2,b,o);var c=Ja("Query.on",arguments[2],arguments[3]);this.k.Cb(this,a,b,c.cancel,c.Y);return b};H.prototype.on=H.prototype.pc;
H.prototype.Mb=function(a,b,c){B("Query.off",0,3,arguments.length);Fa("Query.off",a,k);D("Query.off",2,b,k);ua("Query.off",3,c);this.k.Zb(this,a,b,c)};H.prototype.off=H.prototype.Mb;H.prototype.xd=function(a,b){function c(h){f&&(f=o,e.Mb(a,c),b.call(d.Y,h))}B("Query.once",2,4,arguments.length);Fa("Query.once",a,o);D("Query.once",2,b,o);var d=Ja("Query.once",arguments[2],arguments[3]),e=this,f=k;this.pc(a,c,function(){e.Mb(a,c);d.cancel&&d.cancel.call(d.Y)})};H.prototype.once=H.prototype.xd;
H.prototype.sd=function(a){B("Query.limit",1,1,arguments.length);(!fa(a)||Math.floor(a)!==a||0>=a)&&g("Query.limit: First argument must be a positive integer.");return new H(this.k,this.path,a,this.da,this.pa,this.ua,this.Qa)};H.prototype.limit=H.prototype.sd;H.prototype.Gd=function(a,b){B("Query.startAt",0,2,arguments.length);Ea("Query.startAt",1,a,k);Ga("Query.startAt",b);t(a)||(b=a=m);return new H(this.k,this.path,this.wa,a,b,this.ua,this.Qa)};H.prototype.startAt=H.prototype.Gd;
H.prototype.nd=function(a,b){B("Query.endAt",0,2,arguments.length);Ea("Query.endAt",1,a,k);Ga("Query.endAt",b);return new H(this.k,this.path,this.wa,this.da,this.pa,a,b)};H.prototype.endAt=H.prototype.nd;function Ka(a){var b={};t(a.da)&&(b.sp=a.da);t(a.pa)&&(b.sn=a.pa);t(a.ua)&&(b.ep=a.ua);t(a.Qa)&&(b.en=a.Qa);t(a.wa)&&(b.l=a.wa);t(a.da)&&(t(a.pa)&&a.da===m&&a.pa===m)&&(b.vf="l");return b}H.prototype.Ia=function(){var a=La(Ka(this));return"{}"===a?"default":a};
function Ja(a,b,c){var d={};b&&c?(d.cancel=b,D(a,3,d.cancel,k),d.Y=c,ua(a,4,d.Y)):b&&("object"===typeof b&&b!==m?d.Y=b:"function"===typeof b?d.cancel=b:g(Error(C(a,3,k)+"must either be a cancel callback or a context object.")));return d};function J(a){if(a instanceof J)return a;if(1==arguments.length){this.n=a.split("/");for(var b=0,c=0;c<this.n.length;c++)0<this.n[c].length&&(this.n[b]=this.n[c],b++);this.n.length=b;this.ba=0}else this.n=arguments[0],this.ba=arguments[1]}function F(a){return a.ba>=a.n.length?m:a.n[a.ba]}function Ma(a){var b=a.ba;b<a.n.length&&b++;return new J(a.n,b)}function Pa(a){return a.ba<a.n.length?a.n[a.n.length-1]:m}s=J.prototype;
s.toString=function(){for(var a="",b=this.ba;b<this.n.length;b++)""!==this.n[b]&&(a+="/"+this.n[b]);return a||"/"};s.parent=function(){if(this.ba>=this.n.length)return m;for(var a=[],b=this.ba;b<this.n.length-1;b++)a.push(this.n[b]);return new J(a,0)};s.C=function(a){for(var b=[],c=this.ba;c<this.n.length;c++)b.push(this.n[c]);if(a instanceof J)for(c=a.ba;c<a.n.length;c++)b.push(a.n[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new J(b,0)};
s.f=function(){return this.ba>=this.n.length};function Qa(a,b){var c=F(a);if(c===m)return b;if(c===F(b))return Qa(Ma(a),Ma(b));g("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")}s.contains=function(a){var b=0;if(this.n.length>a.n.length)return o;for(;b<this.n.length;){if(this.n[b]!==a.n[b])return o;++b}return k};function Ra(){this.children={};this.Db=0;this.value=m}function Sa(a,b,c){this.Jb=a?a:"";this.pb=b?b:m;this.o=c?c:new Ra}function L(a,b){for(var c=b instanceof J?b:new J(b),d=a,e;(e=F(c))!==m;)d=new Sa(e,d,va(d.o.children,e)||new Ra),c=Ma(c);return d}s=Sa.prototype;s.j=function(){return this.o.value};function M(a,b){A("undefined"!==typeof b);a.o.value=b;Ta(a)}s.clear=function(){this.o.value=m;this.o.children={};this.o.Db=0;Ta(this)};s.Hb=function(){return 0<this.o.Db};
s.f=function(){return this.j()===m&&!this.Hb()};s.A=function(a){for(var b in this.o.children)a(new Sa(b,this,this.o.children[b]))};function Ua(a,b,c,d){c&&!d&&b(a);a.A(function(a){Ua(a,b,k,d)});c&&d&&b(a)}function Va(a,b,c){for(a=c?a:a.parent();a!==m;){if(b(a))return k;a=a.parent()}return o}s.path=function(){return new J(this.pb===m?this.Jb:this.pb.path()+"/"+this.Jb)};s.name=aa("Jb");s.parent=aa("pb");
function Ta(a){if(a.pb!==m){var b=a.pb,c=a.Jb,d=a.f(),e=E(b.o.children,c);d&&e?(delete b.o.children[c],b.o.Db--,Ta(b)):!d&&!e&&(b.o.children[c]=a.o,b.o.Db++,Ta(b))}};function N(a,b){this.Na=a?a:Wa;this.ca=b?b:Xa}function Wa(a,b){return a<b?-1:a>b?1:0}s=N.prototype;s.ma=function(a,b){return new N(this.Na,this.ca.ma(a,b,this.Na).copy(m,m,o,m,m))};s.remove=function(a){return new N(this.Na,this.ca.remove(a,this.Na).copy(m,m,o,m,m))};s.get=function(a){for(var b,c=this.ca;!c.f();){b=this.Na(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return m};
function Ya(a,b){for(var c,d=a.ca,e=m;!d.f();){c=a.Na(b,d.key);if(0===c){if(d.left.f())return e?e.key:m;for(d=d.left;!d.right.f();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}g("Attempted to find predecessor key for a nonexistent key.  What gives?")}s.f=function(){return this.ca.f()};s.count=function(){return this.ca.count()};s.mb=function(){return this.ca.mb()};s.Ta=function(){return this.ca.Ta()};s.va=function(a){return this.ca.va(a)};s.Ja=function(a){return this.ca.Ja(a)};
s.Ra=function(a){return new Za(this.ca,a)};function Za(a,b){this.Xc=b;for(this.Kb=[];!a.f();)this.Kb.push(a),a=a.left}function $a(a){if(0===a.Kb.length)return m;var b=a.Kb.pop(),c;c=a.Xc?a.Xc(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.f();)a.Kb.push(b),b=b.left;return c}function ab(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=m?c:k;this.left=d!=m?d:Xa;this.right=e!=m?e:Xa}s=ab.prototype;
s.copy=function(a,b,c,d,e){return new ab(a!=m?a:this.key,b!=m?b:this.value,c!=m?c:this.color,d!=m?d:this.left,e!=m?e:this.right)};s.count=function(){return this.left.count()+1+this.right.count()};s.f=r(o);s.va=function(a){return this.left.va(a)||a(this.key,this.value)||this.right.va(a)};s.Ja=function(a){return this.right.Ja(a)||a(this.key,this.value)||this.left.Ja(a)};function bb(a){return a.left.f()?a:bb(a.left)}s.mb=function(){return bb(this).key};
s.Ta=function(){return this.right.f()?this.key:this.right.Ta()};s.ma=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(m,m,m,e.left.ma(a,b,c),m):0===d?e.copy(m,b,m,m,m):e.copy(m,m,m,m,e.right.ma(a,b,c));return cb(e)};function db(a){if(a.left.f())return Xa;!a.left.H()&&!a.left.left.H()&&(a=eb(a));a=a.copy(m,m,m,db(a.left),m);return cb(a)}
s.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.f()&&(!c.left.H()&&!c.left.left.H())&&(c=eb(c)),c=c.copy(m,m,m,c.left.remove(a,b),m);else{c.left.H()&&(c=fb(c));!c.right.f()&&(!c.right.H()&&!c.right.left.H())&&(c=gb(c),c.left.left.H()&&(c=fb(c),c=gb(c)));if(0===b(a,c.key)){if(c.right.f())return Xa;d=bb(c.right);c=c.copy(d.key,d.value,m,m,db(c.right))}c=c.copy(m,m,m,m,c.right.remove(a,b))}return cb(c)};s.H=aa("color");
function cb(a){a.right.H()&&!a.left.H()&&(a=hb(a));a.left.H()&&a.left.left.H()&&(a=fb(a));a.left.H()&&a.right.H()&&(a=gb(a));return a}function eb(a){a=gb(a);a.right.left.H()&&(a=a.copy(m,m,m,m,fb(a.right)),a=hb(a),a=gb(a));return a}function hb(a){var b;b=a.copy(m,m,k,m,a.right.left);return a.right.copy(m,m,a.color,b,m)}function fb(a){var b;b=a.copy(m,m,k,a.left.right,m);return a.left.copy(m,m,a.color,m,b)}
function gb(a){var b,c;b=a.left.copy(m,m,!a.left.color,m,m);c=a.right.copy(m,m,!a.right.color,m,m);return a.copy(m,m,!a.color,b,c)}function ib(){}s=ib.prototype;s.copy=function(){return this};s.ma=function(a,b){return new ab(a,b,i,i,i)};s.remove=function(){return this};s.get=r(m);s.count=r(0);s.f=r(k);s.va=r(o);s.Ja=r(o);s.mb=r(m);s.Ta=r(m);s.H=r(o);var Xa=new ib;var jb=Array.prototype,kb=jb.forEach?function(a,b,c){jb.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},lb=jb.map?function(a,b,c){return jb.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};function mb(){};function nb(){this.z=[];this.ic=[];this.jd=[];this.Rb=[];this.Rb[0]=128;for(var a=1;64>a;++a)this.Rb[a]=0;this.reset()}ka(nb,mb);nb.prototype.reset=function(){this.z[0]=1732584193;this.z[1]=4023233417;this.z[2]=2562383102;this.z[3]=271733878;this.z[4]=3285377520;this.Ac=this.ib=0};
function ob(a,b){var c;c||(c=0);for(var d=a.jd,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}c=a.z[0];for(var h=a.z[1],j=a.z[2],l=a.z[3],n=a.z[4],q,e=0;80>e;e++)40>e?20>e?(f=l^h&(j^l),q=1518500249):(f=h^j^l,q=1859775393):60>e?(f=h&j|l&(h|j),q=2400959708):(f=h^j^l,q=3395469782),f=(c<<5|c>>>27)+f+n+q+d[e]&4294967295,n=l,l=j,j=(h<<30|h>>>2)&4294967295,h=c,c=f;a.z[0]=a.z[0]+c&4294967295;a.z[1]=a.z[1]+h&
4294967295;a.z[2]=a.z[2]+j&4294967295;a.z[3]=a.z[3]+l&4294967295;a.z[4]=a.z[4]+n&4294967295}nb.prototype.update=function(a,b){t(b)||(b=a.length);var c=this.ic,d=this.ib,e=0;if(v(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(ob(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(ob(this,c),d=0);this.ib=d;this.Ac+=b};function pb(){this.Ma={};this.length=0}pb.prototype.setItem=function(a,b){E(this.Ma,a)||(this.length+=1);this.Ma[a]=b};pb.prototype.getItem=function(a){return E(this.Ma,a)?this.Ma[a]:m};pb.prototype.removeItem=function(a){E(this.Ma,a)&&(this.length-=1,delete this.Ma[a])};var O=m;if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),O=sessionStorage}catch(qb){O=new pb}else O=new pb;function rb(a,b,c,d){this.host=a;this.xb=b;this.Ua=c;this.P=d||O.getItem(a)||this.host}function sb(a,b){b!==a.P&&(a.P=b,"s-"===a.P.substr(0,2)&&O.setItem(a.host,a.P))}rb.prototype.toString=function(){return(this.xb?"https://":"http://")+this.host};var tb,ub,vb,wb;function xb(){return ba.navigator?ba.navigator.userAgent:m}wb=vb=ub=tb=o;var yb;if(yb=xb()){var zb=ba.navigator;tb=0==yb.indexOf("Opera");ub=!tb&&-1!=yb.indexOf("MSIE");vb=!tb&&-1!=yb.indexOf("WebKit");wb=!tb&&!vb&&"Gecko"==zb.product}var Ab=ub,Bb=wb,Cb=vb;var Db;if(tb&&ba.opera){var Eb=ba.opera.version;"function"==typeof Eb&&Eb()}else Bb?Db=/rv\:([^\);]+)(\)|;)/:Ab?Db=/MSIE\s+([^\);]+)(\)|;)/:Cb&&(Db=/WebKit\/(\S+)/),Db&&Db.exec(xb());var Fb=m,Gb=m;
function Hb(a,b){ea(a)||g(Error("encodeByteArray takes an array as a parameter"));if(!Fb){Fb={};Gb={};for(var c=0;65>c;c++)Fb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),Gb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?Gb:Fb,d=[],e=0;e<a.length;e+=3){var f=a[e],h=e+1<a.length,j=h?a[e+1]:0,l=e+2<a.length,n=l?a[e+2]:0,q=f>>2,f=(f&3)<<4|j>>4,j=(j&15)<<2|n>>6,n=n&63;l||(n=64,h||(j=64));d.push(c[q],c[f],c[j],c[n])}return d.join("")}
;var Ib,Jb=1;Ib=function(){return Jb++};function A(a,b){a||g(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function Kb(a){a=sa(a);return Hb(a,k)}function Lb(a){var b=sa(a),a=new nb;a.update(b);var b=[],c=8*a.Ac;56>a.ib?a.update(a.Rb,56-a.ib):a.update(a.Rb,64-(a.ib-56));for(var d=63;56<=d;d--)a.ic[d]=c&255,c/=256;ob(a,a.ic);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.z[d]>>e&255;return Hb(b)}
function Mb(){for(var a="",b=0;b<arguments.length;b++)a=ea(arguments[b])?a+Mb.apply(m,arguments[b]):"object"===typeof arguments[b]?a+z(arguments[b]):a+arguments[b],a+=" ";return a}var Nb=m,Ob=k;function Pb(){Ob===k&&(Ob=o,Nb===m&&"true"===O.getItem("logging_enabled")&&Qb(k));if(Nb){var a=Mb.apply(m,arguments);Nb(a)}}function Rb(a){return function(){Pb(a,arguments)}}
function Sb(){if("undefined"!==typeof console){var a="FIREBASE INTERNAL ERROR: "+Mb.apply(m,arguments);"undefined"!==typeof console.error?console.error(a):console.log(a)}}function Tb(){var a=Mb.apply(m,arguments);g(Error("FIREBASE FATAL ERROR: "+a))}function P(){if("undefined"!==typeof console){var a="FIREBASE WARNING: "+Mb.apply(m,arguments);"undefined"!==typeof console.warn?console.warn(a):console.log(a)}}
function Da(a){return fa(a)&&(a!=a||a==Number.POSITIVE_INFINITY||a==Number.NEGATIVE_INFINITY)}function Ub(a,b){return a!==b?a===m?-1:b===m?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Vb(a,b){if(b&&a in b)return b[a];g(Error("Missing required key ("+a+") in object: "+z(b)))}var Wb=0;function La(a){if("object"!==typeof a||a===m)return z(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=z(b[d]),c+=":",c+=La(a[b[d]]);return c+"}"}
function Yb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c}
function Zb(a){A(!Da(a));var b,c,d,e;0===a?(d=c=0,b=-Infinity===1/a?1:0):(b=0>a,a=Math.abs(a),a>=Math.pow(2,-1022)?(d=Math.min(Math.floor(Math.log(a)/Math.LN2),1023),c=d+1023,d=Math.round(a*Math.pow(2,52-d)-Math.pow(2,52))):(c=0,d=Math.round(a/Math.pow(2,-1074))));e=[];for(a=52;a;a-=1)e.push(d%2?1:0),d=Math.floor(d/2);for(a=11;a;a-=1)e.push(c%2?1:0),c=Math.floor(c/2);e.push(b?1:0);e.reverse();b=e.join("");c="";for(a=0;64>a;a+=8)d=parseInt(b.substr(a,8),2).toString(16),1===d.length&&(d="0"+d),c+=d;
return c.toLowerCase()};function $b(a,b){this.sa=a;A(this.sa!==m,"LeafNode shouldn't be created with null value.");this.Va="undefined"!==typeof b?b:m}s=$b.prototype;s.L=r(k);s.m=aa("Va");s.gc=function(a){return new $b(this.sa,a)};s.O=function(){return Q};s.F=function(a){return F(a)===m?this:Q};s.U=r(m);s.D=function(a,b){return(new R(new N,this.Va)).D(a,b)};s.Za=function(a,b){var c=F(a);return c===m?b:this.D(c,Q.Za(Ma(a),b))};s.f=r(o);s.Lb=r(0);
s.ea=function(a){return a&&this.m()!==m?{".value":this.j(),".priority":this.m()}:this.j()};s.hash=function(){var a="";this.m()!==m&&(a+="priority:"+ac(this.m())+":");var b=typeof this.sa,a=a+(b+":"),a="number"===b?a+Zb(this.sa):a+this.sa;return Lb(a)};s.j=aa("sa");s.toString=function(){return"string"===typeof this.sa?'"'+this.sa+'"':this.sa};function R(a,b){this.T=a||new N;this.Va="undefined"!==typeof b?b:m}s=R.prototype;s.L=r(o);s.m=aa("Va");s.gc=function(a){return new R(this.T,a)};s.D=function(a,b){var c=this.T.remove(a);b&&b.f()&&(b=m);b!==m&&(c=c.ma(a,b));return b&&b.m()!==m?new bc(c,m,this.Va):new R(c,this.Va)};s.Za=function(a,b){var c=F(a);if(c===m)return b;var d=this.O(c).Za(Ma(a),b);return this.D(c,d)};s.f=function(){return this.T.f()};s.Lb=function(){return this.T.count()};var cc=/^\d+$/;s=R.prototype;
s.ea=function(a){if(this.f())return m;var b={},c=0,d=0,e=k;this.A(function(f,h){b[f]=h.ea(a);c++;e&&cc.test(f)?d=Math.max(d,Number(f)):e=o});if(!a&&e&&d<2*c){var f=[],h;for(h in b)f[h]=b[h];return f}a&&this.m()!==m&&(b[".priority"]=this.m());return b};s.hash=function(){var a="";this.m()!==m&&(a+="priority:"+ac(this.m())+":");this.A(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Lb(a)};s.O=function(a){a=this.T.get(a);return a===m?Q:a};
s.F=function(a){var b=F(a);return b===m?this:this.O(b).F(Ma(a))};s.U=function(a){return Ya(this.T,a)};s.Jc=function(){return this.T.mb()};s.Kc=function(){return this.T.Ta()};s.A=function(a){return this.T.va(a)};s.kc=function(a){return this.T.Ja(a)};s.Ra=function(){return this.T.Ra()};s.toString=function(){var a="{",b=k;this.A(function(c,d){b?b=o:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var Q=new R(new N);function bc(a,b,c){R.call(this,a,c);b===m&&(b=new N(dc),a.va(function(a,c){b=b.ma({name:a,ya:c.m()},c)}));this.oa=b}ka(bc,R);s=bc.prototype;s.D=function(a,b){var c=this.O(a),d=this.T,e=this.oa;c!==m&&(d=d.remove(a),e=e.remove({name:a,ya:c.m()}));b&&b.f()&&(b=m);b!==m&&(d=d.ma(a,b),e=e.ma({name:a,ya:b.m()},b));return new bc(d,e,this.m())};s.U=function(a,b){var c=Ya(this.oa,{name:a,ya:b.m()});return c?c.name:m};s.A=function(a){return this.oa.va(function(b,c){return a(b.name,c)})};
s.kc=function(a){return this.oa.Ja(function(b,c){return a(b.name,c)})};s.Ra=function(){return this.oa.Ra(function(a,b){return{key:a.name,value:b}})};s.Jc=function(){return this.oa.f()?m:this.oa.mb().name};s.Kc=function(){return this.oa.f()?m:this.oa.Ta().name};function ec(a,b){if("object"!==typeof a)return new $b(a,b);if(a===m)return Q;var c=m;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);A(c===m||"string"===typeof c||"number"===typeof c);if(".value"in a&&a[".value"]!==m)return new $b(a[".value"],c);var c=new R(new N,c),d;for(d in a)if(E(a,d)&&"."!==d.substring(0,1)){var e=ec(a[d]);if(e.L()||!e.f())c=c.D(d,e)}return c}function dc(a,b){return Ub(a.ya,b.ya)||(a.name!==b.name?a.name<b.name?-1:1:0)}
function ac(a){return"number"===typeof a?"number:"+Zb(a):"string:"+a};function S(a,b){this.o=a;this.Yb=b}S.prototype.ea=function(){B("Firebase.DataSnapshot.val",0,0,arguments.length);return this.o.ea()};S.prototype.val=S.prototype.ea;S.prototype.od=function(){B("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.o.ea(k)};S.prototype.exportVal=S.prototype.od;S.prototype.C=function(a){B("Firebase.DataSnapshot.child",0,1,arguments.length);fa(a)&&(a=String(a));Ha("Firebase.DataSnapshot.child",a);var b=new J(a),c=this.Yb.C(b);return new S(this.o.F(b),c)};
S.prototype.child=S.prototype.C;S.prototype.lc=function(a){B("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Ha("Firebase.DataSnapshot.hasChild",a);var b=new J(a);return!this.o.F(b).f()};S.prototype.hasChild=S.prototype.lc;S.prototype.m=function(){B("Firebase.DataSnapshot.getPriority",0,0,arguments.length);return this.o.m()};S.prototype.getPriority=S.prototype.m;
S.prototype.forEach=function(a){B("Firebase.DataSnapshot.forEach",1,1,arguments.length);D("Firebase.DataSnapshot.forEach",1,a,o);if(this.o.L())return o;var b=this;return this.o.A(function(c,d){return a(new S(d,b.Yb.C(c)))})};S.prototype.forEach=S.prototype.forEach;S.prototype.Hb=function(){B("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.o.L()?o:!this.o.f()};S.prototype.hasChildren=S.prototype.Hb;
S.prototype.name=function(){B("Firebase.DataSnapshot.name",0,0,arguments.length);return this.Yb.name()};S.prototype.name=S.prototype.name;S.prototype.Lb=function(){B("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.o.Lb()};S.prototype.numChildren=S.prototype.Lb;S.prototype.Ad=function(){B("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.Yb};S.prototype.ref=S.prototype.Ad;function fc(a){this.tc=a;this.Tb=[];this.Pa=0;this.jc=-1;this.Ha=m}function gc(a,b,c){for(a.Tb[b]=c;a.Tb[a.Pa];){b=a.Tb[a.Pa];delete a.Tb[a.Pa];for(c=0;c<b.length;++c)b[c]&&a.tc(b[c]);if(a.Pa===a.jc){a.Ha&&(clearTimeout(a.Ha),a.Ha(),a.Ha=m);break}a.Pa++}};function T(a,b){for(var c in a)b.call(i,a[c],c,a)}function hc(a){var b={},c;for(c in a)b[c]=a[c];return b};function ic(){this.bb={}}function jc(a,b,c){t(c)||(c=1);E(a.bb,b)||(a.bb[b]=0);a.bb[b]+=c}ic.prototype.get=function(){return hc(this.bb)};function kc(a){this.kd=a;this.Ib=m}kc.prototype.get=function(){var a=this.kd.get(),b=hc(a);if(this.Ib)for(var c in this.Ib)b[c]-=this.Ib[c];this.Ib=a;return b};function lc(a,b){this.yc={};this.cc=new kc(a);this.u=b;setTimeout(y(this.Vc,this),10+6E4*Math.random())}lc.prototype.Vc=function(){var a=this.cc.get(),b={},c=o,d;for(d in a)0<a[d]&&E(this.yc,d)&&(b[d]=a[d],c=k);c&&(a=this.u,a.fa&&(b={c:b},a.e("reportStats",b),a.Aa("s",b)));setTimeout(y(this.Vc,this),6E5*Math.random())};var mc={},nc={};function oc(a){a=a.toString();mc[a]||(mc[a]=new ic);return mc[a]};var pc=require("http");function qc(a,b,c){this.Eb=a;this.e=Rb(a);this.B=b;this.R=oc(b);this.La=c;this.Z=this.Fa=o;this.$=new rc;this.buffer={};this.aa=[];this.zd=function(a){b.host!==b.P&&(a.ns=b.Ua);var c=[],f;for(f in a)a.hasOwnProperty(f)&&c.push(f+"="+a[f]);return"/.hp?"+c.join("&")}}qc.isAvailable=r(o);s=qc.prototype;
s.open=function(a,b){this.eb=0;this.N=b;this.yd=new fc(a);var c=this;this.K=setTimeout(function(){c.e("Timed out trying to connect.");c.close();c.K=m},3E4);var d=Math.floor(1E8*Math.random()),e={start:"t"};e.ser=d;e.v="5";this.La&&(e.s=this.La);this.e("Connecting via httppoll to "+this.B.P);sc(this,d,e)};s.start=function(){this.$a=k;for(this.fb=Math.floor(1E8*Math.random());this.xa(););};
s.send=function(a){for(var a=z(a),a=Kb(a),a=Yb(a,1048576),b=0;b<a.length;++b)this.aa.push({vc:this.eb,Cc:a.length,gb:a[b]}),this.$a&&this.xa(),this.eb++};s.close=function(){if(!this.Z){this.e("Httppoll is being closed");if(this.$a&&this.id&&this.qb){this.e("doing a disconnect");var a={};a.id=this.id;a.pw=this.qb;a.disconn="t";sc(this,0,a)}this.Ca()}};
s.xa=function(){if(this.$a&&this.$.count()<(0<this.aa.length?2:1)){var a=this.fb++,b={};b.id=this.id;b.pw=this.qb;b.ser=a;for(var c=[];0<this.aa.length;)if(1048608>=this.aa[0].gb.length){var d=this.aa.shift();c.push(d.vc+":"+d.Cc+":"+d.gb)}else break;var e=this,d=setTimeout(function(){e.$.remove(a);e.xa()},25E3);this.$.add(a,d);sc(this,a,b,c.join("\n"));return k}return o};s.ha=function(){this.Z||(this.e("Httppoll is closing itself"),this.Ca(),this.N&&(this.N(this.Fa),this.N=m))};
s.Ca=function(){this.Z=k;this.$a=o;this.K&&(clearTimeout(this.K),this.K=m);T(this.$.set,function(a){clearTimeout(a)});this.$.clear()};
function sc(a,b,c,d){var d=d||"",c=a.zd(c),e=a.B.P,f=e.split(":"),h=a.B.xb?443:80;1<f.length&&(e=f[0],h=parseInt(f[1]));c=pc.request({method:"POST",host:e,port:h,path:c},function(c){if(a.K){clearTimeout(a.K);a.K=m}var d=a.$.get(b);d&&clearTimeout(d);a.$.remove(b);a.xa();if(c.statusCode!=200){a.e("error code received: "+c.statusCode);a.ha()}else{if("x-firebase-poll-id"in c.headers&&"x-firebase-poll-pw"in c.headers){a.id=c.headers["x-firebase-poll-id"];a.qb=c.headers["x-firebase-poll-pw"]}if("x-firebase-poll-close"in
c.headers){a.e("recvd close");a.$a=o}c.on("data",function(b){b=b.toString();a.buffer[c]=c in a.buffer?a.buffer[c]+b:b});c.on("end",function(){if(c in a.buffer){var b=a.buffer[c];delete a.buffer[c];var b=ra(b),d=parseInt(Vb("x-firebase-response",c.headers));gc(a.yd,d,b)}})}});c.on("error",function(b){a.e("An error occurred: "+b.message);a.ha()});c.end(d)};var tc=m,tc=require("faye-websocket").Client;function uc(a,b,c){this.Eb=a;this.e=Rb(this.Eb);this.frames=this.kb=m;this.zc=0;this.R=oc(b);this.Oa=(b.xb?"wss://":"ws://")+b.P+"/.ws?v=5";b.host!==b.P&&(this.Oa=this.Oa+"&ns="+b.Ua);c&&(this.Oa=this.Oa+"&s="+c)}var vc;
uc.prototype.open=function(a,b){this.W=b;this.Pb=a;this.e("websocket connecting to "+this.Oa);this.V=new tc(this.Oa);this.Fa=o;var c=this;this.V.onopen=function(){c.e("Websocket connected.");c.Fa=k};this.V.onclose=function(){c.e("Websocket connection was disconnected.");c.V=m;c.ha()};this.V.onmessage=function(a){if(c.V!==m)if(a=a.data,jc(c.R,"bytes_received",a.length),c.frames!==m)wc(c,a);else{a:{A(c.frames===m,"We already have a frame buffer");if(4>=a.length){var b=Number(a);if(!isNaN(b)){c.zc=b;
c.frames=[];a=m;break a}}c.zc=1;c.frames=[]}a!==m&&wc(c,a)}};this.V.onerror=function(){c.e("WebSocket error.  Closing connection.");c.ha()}};uc.prototype.start=p();uc.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&tc!==m&&!vc};function wc(a,b){a.frames.push(b);if(a.frames.length==a.zc){var c=a.frames.join("");a.frames=m;c=ra(c);xc(a);a.Pb(c)}}
uc.prototype.send=function(a){xc(this);a=z(a);jc(this.R,"bytes_sent",a.length);a=Yb(a,16384);1<a.length&&this.V.send(String(a.length));for(var b=0;b<a.length;b++)this.V.send(a[b])};uc.prototype.Ca=function(){this.Z=k;this.kb&&(clearTimeout(this.kb),this.kb=m);this.V&&(this.V.close(),this.V=m)};uc.prototype.ha=function(){this.Z||(this.e("WebSocket is closing itself"),this.Ca(),this.W&&(this.W(this.Fa),this.W=m))};uc.prototype.close=function(){this.Z||(this.e("WebSocket is being closed"),this.Ca())};
function xc(a){clearTimeout(a.kb);a.kb=setInterval(function(){a.V.send("0");xc(a)},45E3)};function rc(){this.set={}}s=rc.prototype;s.add=function(a,b){this.set[a]=b!==m?b:k};s.contains=function(a){return E(this.set,a)};s.get=function(a){return this.set[a]};s.remove=function(a){delete this.set[a]};s.clear=function(){this.set={}};s.f=function(){var a;a:{for(a in this.set){a=o;break a}a=k}return a};s.count=function(){var a=0,b;for(b in this.set)a++;return a};s.keys=function(){var a=[],b;for(b in this.set)E(this.set,b)&&a.push(b);return a};function yc(a,b,c){this.Eb=a;this.e=Rb(a);this.Kd=b;this.R=oc(b);this.La=c;this.Fa=o;this.Bb=function(a){b.host!==b.P&&(a.ns=b.Ua);var c=[],f;for(f in a)a.hasOwnProperty(f)&&c.push(f+"="+a[f]);return(b.xb?"https://":"http://")+b.P+"/.lp?"+c.join("&")}}var zc;
yc.prototype.open=function(a,b){this.eb=0;this.N=b;this.Qc=new fc(a);this.Z=o;var c=this;this.K=setTimeout(function(){c.e("Timed out trying to connect.");c.ha();c.K=m},3E4);if(!c.Z){c.ia=new Ac(function(a,b,d,j,l){jc(c.R,"bytes_received",z(arguments).length);if(c.ia)if(c.K&&(clearTimeout(c.K),c.K=m),c.Fa=k,"start"==a)c.id=b,c.qb=d;else if("close"===a)if(b){c.ia.$c=o;var n=c.Qc;n.jc=b;n.Ha=function(){c.ha()};n.jc<n.Pa&&(n.Ha(),n.Ha=m)}else c.ha();else g(Error("Unrecognized command received: "+a))},
function(a,b){jc(c.R,"bytes_received",z(arguments).length);gc(c.Qc,a,b)},function(){c.ha()},c.Bb);var d={start:"t"};d.ser=Math.floor(1E8*Math.random());c.ia.Hd&&(d.cb=c.ia.Hd);d.v="5";c.La&&(d.s=c.La);d=c.Bb(d);c.e("Connecting via long-poll to "+d);Bc(c.ia,d,p())}};yc.prototype.start=function(){var a=this.ia,b=this.qb;a.nc=this.id;a.Pc=b;for(a.hc=k;a.xa(););};yc.isAvailable=function(){return zc||o};
yc.prototype.Ca=function(){this.Z=k;this.ia&&(this.ia.close(),this.ia=m);this.Oc&&(document.body.removeChild(this.Oc),this.Oc=m);this.K&&(clearTimeout(this.K),this.K=m)};yc.prototype.ha=function(){this.Z||(this.e("Longpoll is closing itself"),this.Ca(),this.N&&(this.N(this.Fa),this.N=m))};yc.prototype.close=function(){this.Z||(this.e("Longpoll is being closed."),this.Ca())};
yc.prototype.send=function(a){a=z(a);jc(this.R,"bytes_sent",a.length);for(var a=Kb(a),a=Yb(a,1840),b=0;b<a.length;b++){var c=this.ia;c.aa.push({vc:this.eb,Cc:a.length,gb:a[b]});c.hc&&c.xa();this.eb++}};function Ac(a,b,c,d){this.Bb=d;this.W=c;this.$=new rc;this.aa=[];this.fb=Math.floor(1E8*Math.random());this.$c=k;this.ld=a;this.wd=b}
Ac.prototype.close=function(){this.hc=o;this.oc&&(this.oc.Id.body.innerHTML="",document.body.removeChild(this.oc),this.oc=m);if(this.nc){var a={disconn:"t"};a.id=this.nc;a.pw=this.Pc;a=this.Bb(a);Cc(a)}if(a=this.W)this.W=m,a()};
Ac.prototype.xa=function(){if(this.hc&&this.$c&&this.$.count()<(0<this.aa.length?2:1)){this.fb++;var a={};a.id=this.nc;a.pw=this.Pc;a.ser=this.fb;for(var a=this.Bb(a),b="",c=0;0<this.aa.length;)if(1870>=this.aa[0].gb.length+30+b.length){var d=this.aa.shift(),b=b+"&seg"+c+"="+d.vc+"&ts"+c+"="+d.Cc+"&d"+c+"="+d.gb;c++}else break;var a=a+b,e=this.fb,f=this;f.$.add(e);var h=function(){f.$.remove(e);f.xa()},j=setTimeout(h,25E3);Bc(this,a,function(){clearTimeout(j);h()});return k}return o};
function Cc(a,b){Dc||(Dc=require("request"));Dc(a,function(a,d,e){a&&g("Rest request for "+url+" failed.");b&&b(e)})}var Dc;function Bc(a,b,c){Cc({url:b,Jd:k},function(b){Ec(a,b);c()})}function Ec(a,b){eval("var document = function(pLPCommand, pRTLPCB) {"+b+"}");document(a.ld,a.wd)};function Fc(){function a(a,c){c&&c.isAvailable()&&b.push(c)}var b=[],c=Gc;if("array"==da(c))for(var d=0;d<c.length;++d)a(0,c[d]);else T(c,a);this.ec=b}var Gc=[yc,qc,uc];function U(a,b,c,d,e,f){this.id=a;this.e=Rb("c:"+this.id+":");this.tc=c;this.nb=d;this.N=e;this.sc=f;this.B=b;this.Sb=[];this.Ec=0;this.Bc=new Fc;this.qa=0;this.e("Connection created");Hc(this)}function Hc(a){var b;var c=a.Bc;0<c.ec.length?b=c.ec[0]:g(Error("No transports available"));a.J=new b("c:"+a.id+":"+a.Ec++,a.B);b=Ic(a,a.J);c=Jc(a,a.J);a.zb=a.J;a.wb=a.J;a.J.open(b,c);a.w=m}
function Jc(a,b){return function(c){b===a.J?(a.J=m,!c&&0===a.qa?(a.e("Realtime connection failed."),"s-"===a.B.P.substr(0,2)&&(O.removeItem(a.B.Ua),a.B.P=a.B.host)):1===a.qa&&a.e("Realtime connection lost."),a.close()):b===a.w?(c=a.w,a.w=m,(a.zb===c||a.wb===c)&&a.close()):a.e("closing an old connection")}}
function Ic(a,b){return function(c){if(2!=a.qa)if(b===a.wb){var d=Vb("t",c),c=Vb("d",c);if("c"==d){if(d=Vb("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,f=c.h;a.La=c.s;sb(a.B,f);if(0==a.qa&&(a.J.start(),c=a.J,a.e("Realtime connection established."),a.J=c,a.qa=1,a.nb&&(a.nb(d),a.nb=m),"5"!==e&&P("Protocol version mismatch detected"),c=1<a.Bc.ec.length?a.Bc.ec[1]:m))a.w=new c("c:"+a.id+":"+a.Ec++,a.B,a.La),a.w.open(Ic(a,a.w),Jc(a,a.w))}else if("n"===d){a.e("recvd end transmission on primary");a.wb=
a.w;for(c=0;c<a.Sb.length;++c)a.Nb(a.Sb[c]);a.Sb=[];Kc(a)}else"s"===d?(a.e("Connection shutdown command received. Shutting down..."),a.sc&&(a.sc(c),a.sc=m),a.N=m,a.close()):"r"===d?(a.e("Reset packet received.  New host: "+c),sb(a.B,c),1===a.qa?a.close():(Lc(a),Hc(a))):Sb("Unknown control packet command: "+d)}else"d"==d&&a.Nb(c)}else b===a.w?(d=Vb("t",c),c=Vb("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.w.start(),a.e("sending client ack on secondary"),a.w.send({t:"c",d:{t:"a",d:{}}}),a.e("Ending transmission on primary"),
a.J.send({t:"c",d:{t:"n",d:{}}}),a.zb=a.w,Kc(a)):"r"===c&&(a.e("Got a reset on secondary, closing it"),a.w.close(),(a.zb===a.w||a.wb===a.w)&&a.close())):"d"==d?a.Sb.push(c):g(Error("Unknown protocol layer: "+d))):a.e("message on old connection")}}U.prototype.wc=function(a){a={t:"d",d:a};1!==this.qa&&g("Connection is not connected");this.zb.send(a)};function Kc(a){a.zb===a.w&&a.wb===a.w&&(a.e("cleaning up and promoting a connection: "+a.w.Eb),a.J=a.w,a.w=m)}U.prototype.Nb=function(a){this.tc(a)};
U.prototype.close=function(){2!==this.qa&&(this.e("Closing realtime connection."),this.qa=2,Lc(this),this.N&&(this.N(),this.N=m))};function Lc(a){a.e("Shutting down all connections");a.J&&(a.J.close(),a.J=m);a.w&&(a.w.close(),a.w=m)};function Mc(a,b,c,d){this.id=Nc++;this.e=Rb("p:"+this.id+":");this.Ya=k;this.ga={};this.Q=[];this.ob=0;this.rc={};this.fa=o;this.Xb=1E3;this.Ob=b;this.Sc=c;this.N=d;this.B=a;this.uc=m;this.Ub=[];this.za={};this.Dd=0;this.lb=this.Nc=m;setTimeout(y(this.Fc,this),0)}var Nc=0,Oc=0;s=Mc.prototype;
s.Aa=function(a,b,c,d){var e=++this.Dd,a={r:e,a:a,b:b};this.e(z(a));this.fa?this.ub.wc(a):this.Ub.push(a);var f=this,a=setTimeout(function(){var a=f.za[e];a&&(delete f.za[e],a.la&&a.la.Qb&&a.la.Qb())},45E3);this.za[e]={la:{Pb:c,Qb:d},cd:a}};function Pc(a,b,c,d,e){a.e("Listen on "+b+" for "+c);var f={p:b},d=lb(d,function(a){return Ka(a)});"{}"!==c&&(f.q=d);a.Aa("l",f,function(d){a.e("listen response",d);d=d.s;"ok"!==d&&Qc(a,b,c);e&&e(d)},function(){a.e("timed out on listen...")})}
s.ab=function(a,b){this.Fb={md:a,Hc:o,ja:b};this.e("Authenticating using credential: "+this.Fb);Rc(this)};s.Ab=function(){delete this.Fb;this.fa&&this.Aa("unauth",{},p(),p())};function Rc(a){var b=a.Fb;a.fa&&b&&a.Aa("auth",{cred:b.md},function(c){c=c.s;"ok"!==c&&delete a.Fb;b.Hc||(b.Hc=k,b.ja&&b.ja(c))},function(){a.e("timed out on auth...")})}
s.ed=function(a,b,c){a=a.toString();if(Qc(this,a,b)&&this.fa){this.e("Unlisten on "+a+" for "+b);var d=this,a={p:a},c=lb(c,function(a){return Ka(a)});"{}"!==b&&(a.q=c);this.Aa("u",a,m,function(){d.e("timed out on unlisten...")})}};s.W=function(a,b){this.rc[a]=b;this.fa&&Sc(this,a,b)};function Sc(a,b,c){b={p:b,d:c};a.e("onDisconnect",b);a.Aa("o",b,function(a){"ok"!==a.s&&g("onDisconnect failed: "+z(a.d))},function(){a.e("timed out on onDisconnect...")})}s.put=function(a,b,c,d){Tc(this,"p",a,b,c,d)};
function Tc(a,b,c,d,e,f){c={p:c,d:d};t(f)&&(c.h=f);a.Q.push({action:b,Wc:c,G:e});a.ob++;b=a.Q.length-1;a.fa&&Uc(a,b)}function Uc(a,b){var c=a.Q[b].action,d=a.Q[b].G;a.Aa(c,a.Q[b].Wc,function(e){a.e(c+" response",e);delete a.Q[b];a.ob--;0===a.ob&&(a.Q=[]);d&&d(e.s)},function(){a.e("timed out on put...")})}
s.Nb=function(a){if("r"in a){this.e("from server: "+z(a));var b=a.r,c=this.za[b];c&&(delete this.za[b],clearTimeout(c.cd),c.la&&c.la.Pb&&c.la.Pb(a.b))}else"error"in a&&g("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,c=a.b,this.e("handleServerMessage",b,c),"d"===b?this.Ob(c.p,c.d):"m"===b?this.Ob(c.p,c.d,k):"c"===b?(a=c.p,b=(b=c.q)?lb(b,function(a){return La(a)}).join("$"):"{}",(a=Qc(this,a,b))&&a.G&&a.G("permission_denied")):"sd"===b?this.uc?this.uc(c):"msg"in c&&"undefined"!==typeof console&&
console.log("FIREBASE: "+c.msg.replace("\n","\nFIREBASE: ")):Sb("Unrecognized action received from server: "+z(b)+"\nAre you using the latest client?"))};
s.nb=function(a){this.e("connection ready");this.fa=k;this.lb=(new Date).getTime();Wb=a-(new Date).getTime();for(a=0;a<this.Ub.length;a++)this.ub.wc(this.Ub[a]);this.Ub=[];Rc(this);for(var b in this.ga)for(var c in this.ga[b])a=this.ga[b][c],Pc(this,b,c,a.Wa,a.G);for(b in this.rc)Sc(this,b,this.rc[b]);for(b=0;b<this.Q.length;b++)this.Q[b]&&Uc(this,b);this.Sc&&this.Sc()};
s.Tc=function(){this.fa=o;this.e("data client disconnected");if(!this.Ya){for(var a=0;a<this.Q.length;a++){var b=this.Q[a];b&&"h"in b.Wc&&(b.G&&b.G("disconnect"),delete this.Q[a],this.ob--)}0===this.ob&&(this.Q=[]);for(var c in this.za)a=this.za[c],delete this.za[c],a!==m&&(a.la&&a.la.Qb&&a.la.Qb(),clearTimeout(a.cd))}var d=y(function(){this.Fc()},this);this.Ya?(this.lb&&(3E4<(new Date).getTime()-this.lb&&(this.Xb=1E3),this.lb=m),c=Math.max(0,this.Xb-((new Date).getTime()-this.Nc)),c*=Math.random(),
this.e("Trying to reconnect in "+c+"ms"),setTimeout(d,c),this.Xb=Math.min(3E4,1.3*this.Xb)):this.Yc=function(){setTimeout(d,0)};this.N&&this.N()};s.Fc=function(){if(this.Ya){this.e("Making a connection attempt");this.Nc=(new Date).getTime();this.lb=m;var a=y(this.Nb,this),b=y(this.nb,this),c=y(this.Tc,this),d=this.id+":"+Oc++,e=this;this.ub=new U(d,this.B,a,b,c,function(a){e.Ya=o;g(Error(a))})}};s.Sa=function(){this.Ya=o;this.ub?this.ub.close():this.Tc()};
s.vb=function(){this.Ya=k;this.Yc();this.Yc=i};function Qc(a,b,c){b=(new J(b)).toString();c||(c="{}");var d=a.ga[b][c];delete a.ga[b][c];return d};function Vc(){this.Ka=Q}function V(a,b){return a.Ka.F(b)}function W(a,b,c){a.Ka=a.Ka.Za(b,c)}Vc.prototype.toString=function(){return this.Ka.toString()};function Wc(){this.Ba=new Vc;this.M=new Vc;this.Da=new Vc;this.sb=new Sa}function Xc(a,b){for(var c=V(a.Ba,b),d=V(a.M,b),e=L(a.sb,b),f=o,h=e;h!==m;){if(h.j()!==m){f=k;break}h=h.parent()}if(f)return o;c=Yc(c,d,e);return c!==d?(W(a.M,b,c),k):o}function Yc(a,b,c){if(c.f())return a;if(c.j()!==m)return b;a=a||Q;c.A(function(d){var d=d.name(),e=a.O(d),f=b.O(d),h=L(c,d),e=Yc(e,f,h);a=a.D(d,e)});return a}
Wc.prototype.set=function(a,b){var c=this,d=[];kb(b,function(a){var b=a.path,a=a.Ga,h=Ib();M(L(c.sb,b),h);W(c.M,b,a);d.push({path:b,Ed:h})});return d};function Zc(a,b){kb(b,function(b){var d=b.Ed,b=L(a.sb,b.path),e=b.j();A(e!==m,"pendingPut should not be null.");e===d&&M(b,m)})};function $c(){this.Ea=[]}function ad(a,b){if(0!==b.length){a.Ea.push.apply(a.Ea,b);for(var c=0;c<a.Ea.length;c++)if(a.Ea[c]){var d=a.Ea[c];a.Ea[c]=m;var e=d.ja;e(d.ad,d.tb)}a.Ea=[]}};function X(a,b,c,d){this.type=a;this.na=b;this.X=c;this.tb=d};function bd(a){this.I=a;this.ka=[];this.Gc=new $c}function cd(a,b,c,d,e){a.ka.push({type:b,ja:c,cancel:d,Y:e});var d=[],f=dd(a.g);a.jb&&f.push(new X("value",a.g));for(var h=0;h<f.length;h++)if(f[h].type===b){var j=new Y(a.I.k,a.I.path);f[h].X&&(j=j.C(f[h].X));d.push({ja:e?y(c,e):c,ad:new S(f[h].na,j),tb:f[h].tb})}ad(a.Gc,d)}bd.prototype.Vb=function(a,b){b=this.Wb(a,b);b!=m&&ed(this,b)};
function ed(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],f=e.type,h=new Y(a.I.k,a.I.path);b[d].X&&(h=h.C(b[d].X));h=new S(b[d].na,h);"value"===e.type&&!h.Hb()?f+="("+h.ea()+")":"value"!==e.type&&(f+=" "+h.name());Pb(a.I.k.u.id+": event:"+a.I.path+":"+a.I.Ia()+":"+f);for(f=0;f<a.ka.length;f++){var j=a.ka[f];b[d].type===j.type&&c.push({ja:j.Y?y(j.ja,j.Y):j.ja,ad:h,tb:e.tb})}}ad(a.Gc,c)}
function dd(a){var b=[];if(!a.L()){var c=m;a.A(function(a,e){b.push(new X("child_added",e,a,c));c=a})}return b}function fd(a){a.jb||(a.jb=k,ed(a,[new X("value",a.g)]))};function gd(a,b){bd.call(this,a);this.g=b}ka(gd,bd);gd.prototype.Wb=function(a,b){this.g=a;this.jb&&b!=m&&b.push(new X("value",this.g));return b};gd.prototype.hb=function(){return{}};function hd(a,b){this.Gb=a;this.qc=b}
function id(a,b,c,d,e){var f=a.F(c),h=b.F(c),d=new hd(d,e),e=jd(d,c,f,h),j=o;if(!f.f()&&!h.f()&&f.m()!==h.m())var j=a.F(c.parent()),l=b.F(c.parent()),n=Pa(c),j=j.U(n,f)!=l.U(n,h);if(e||j){f=c;c=e;for(h=j;f.parent()!==m;){var q=a.F(f),e=b.F(f),j=f.parent();if(!d.Gb||L(d.Gb,j).j())l=b.F(j),n=[],f=Pa(f),q.f()?(q=l.U(f,e),n.push(new X("child_added",e,f,q))):e.f()?n.push(new X("child_removed",q,f)):(q=l.U(f,e),h&&n.push(new X("child_moved",e,f,q)),c&&n.push(new X("child_changed",e,f,q))),d.qc(j,l,n);h&&
(h=o,c=k);f=j}}}function jd(a,b,c,d){var e,f=[];c===d?e=o:c.L()&&d.L()?e=c.j()!==d.j():c.L()?(md(a,b,Q,d,f),e=k):d.L()?(md(a,b,c,Q,f),e=k):e=md(a,b,c,d,f);e?a.qc(b,d,f):c.m()!==d.m()&&a.qc(b,d,m);return e}
function md(a,b,c,d,e){var f=o,h=!a.Gb||!L(a.Gb,b).f(),j=[],l=[],n=[],q=[],x={},u={},w,K,I,G;w=c.Ra();I=$a(w);K=d.Ra();for(G=$a(K);I!==m||G!==m;){c=I===m?1:G===m?-1:I.key===G.key?0:dc({name:I.key,ya:I.value.m()},{name:G.key,ya:G.value.m()});if(0>c)f=va(x,I.key),t(f)?(n.push({Ic:I,dd:j[f]}),j[f]=m):(u[I.key]=l.length,l.push(I)),f=k,I=$a(w);else{if(0<c)f=va(u,G.key),t(f)?(n.push({Ic:l[f],dd:G}),l[f]=m):(x[G.key]=j.length,j.push(G)),f=k;else{c=b.C(G.key);if(c=jd(a,c,I.value,G.value))q.push(G),f=k;I=
$a(w)}G=$a(K)}if(!h&&f)return k}for(h=0;h<l.length;h++)if(x=l[h])c=b.C(x.key),jd(a,c,x.value,Q),e.push(new X("child_removed",x.value,x.key));for(h=0;h<j.length;h++)if(x=j[h])c=b.C(x.key),l=d.U(x.key,x.value),jd(a,c,Q,x.value),e.push(new X("child_added",x.value,x.key,l));for(h=0;h<n.length;h++)x=n[h].Ic,j=n[h].dd,c=b.C(j.key),l=d.U(j.key,j.value),e.push(new X("child_moved",j.value,j.key,l)),(c=jd(a,c,x.value,j.value))&&q.push(j);for(h=0;h<q.length;h++)a=q[h],l=d.U(a.key,a.value),e.push(new X("child_changed",
a.value,a.key,l));return f};function nd(){this.rb=this.ra=m;this.set={}}ka(nd,rc);s=nd.prototype;s.setActive=function(a){this.ra=a};function od(a){return a.contains("default")}function pd(a){return a.ra!=m&&od(a)}s.defaultView=function(){return od(this)?this.get("default"):m};s.path=aa("rb");s.toString=function(){return lb(this.keys(),function(a){return"default"===a?"{}":a}).join("$")};s.Wa=function(){var a=[];T(this.set,function(b){a.push(b.I)});return a};function qd(a,b){bd.call(this,a);this.g=Q;this.Wb(b,dd(b))}ka(qd,bd);
qd.prototype.Wb=function(a,b){if(b===m)return b;var c=[],d=this.I;t(d.da)&&(t(d.pa)&&d.pa!=m?c.push(function(a,b){var c=Ub(b,d.da);return 0<c||0===c&&a>=d.pa}):c.push(function(a,b){return 0<=Ub(b,d.da)}));t(d.ua)&&(t(d.Qa)?c.push(function(a,b){var c=Ub(b,d.ua);return 0>c||0===c&&a<=d.Qa}):c.push(function(a,b){return 0>=Ub(b,d.ua)}));var e=m,f=m;if(t(this.I.wa))if(t(this.I.da)){if(e=rd(a,c,this.I.wa,o)){var h=a.O(e).m();c.push(function(a,b){var c=Ub(b,h);return 0>c||0===c&&a<=e})}}else if(f=rd(a,c,
this.I.wa,k)){var j=a.O(f).m();c.push(function(a,b){var c=Ub(b,j);return 0<c||0===c&&a>=f})}for(var l=[],n=[],q=[],x=[],u=0;u<b.length;u++){var w=b[u].X,K=b[u].na;switch(b[u].type){case "child_added":sd(c,w,K)&&(this.g=this.g.D(w,K),n.push(b[u]));break;case "child_removed":this.g.O(w).f()||(this.g=this.g.D(w,m),l.push(b[u]));break;case "child_changed":!this.g.O(w).f()&&sd(c,w,K)&&(this.g=this.g.D(w,K),x.push(b[u]));break;case "child_moved":var I=!this.g.O(w).f(),G=sd(c,w,K);I?G?(this.g=this.g.D(w,
K),q.push(b[u])):(l.push(new X("child_removed",this.g.O(w),w)),this.g=this.g.D(w,m)):G&&(this.g=this.g.D(w,K),n.push(b[u]))}}var kd=e||f;if(kd){var ld=(u=f!==m)?this.g.Jc():this.g.Kc(),Xb=o,Na=o,Oa=this;(u?a.kc:a.A).call(a,function(a,b){!Na&&ld===m&&(Na=k);if(Na&&Xb)return k;Xb?(l.push(new X("child_removed",Oa.g.O(a),a)),Oa.g=Oa.g.D(a,m)):Na&&(n.push(new X("child_added",b,a)),Oa.g=Oa.g.D(a,b));ld===a&&(Na=k);a===kd&&(Xb=k)})}for(u=0;u<n.length;u++)c=n[u],w=this.g.U(c.X,c.na),l.push(new X("child_added",
c.na,c.X,w));for(u=0;u<q.length;u++)c=q[u],w=this.g.U(c.X,c.na),l.push(new X("child_moved",c.na,c.X,w));for(u=0;u<x.length;u++)c=x[u],w=this.g.U(c.X,c.na),l.push(new X("child_changed",c.na,c.X,w));this.jb&&0<l.length&&l.push(new X("value",this.g));return l};function rd(a,b,c,d){if(a.L())return m;var e=m;(d?a.kc:a.A).call(a,function(a,d){if(sd(b,a,d)&&(e=a,c--,0===c))return k});return e}function sd(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.m()))return o;return k}
qd.prototype.lc=function(a){return this.g.O(a)!==Q};qd.prototype.hb=function(a,b,c){var d={};this.g.L()||this.g.A(function(a){d[a]=k});var e=this.g,c=V(c,new J("")),f=new Sa;M(L(f,this.I.path),k);var h=Q.Za(a,b),j=[];id(c,h,a,f,function(a,b,c){c!==m&&(j=j.concat(c))});this.Wb(b,j);this.g.L()||this.g.A(function(a){d[a]=k});this.g=e;return d};function td(a,b){this.u=a;this.i=b;this.Rc=b.Ka;this.ta=new Sa}
td.prototype.Cb=function(a,b,c,d,e){var f=a.path,h=L(this.ta,f),j=h.j();j===m?(j=new nd,M(h,j)):A(!j.f(),"We shouldn't be storing empty QueryMaps");var l=a.Ia();if(j.contains(l))cd(j.get(l),b,c,d,e);else{var n=this.i.Ka.F(f),a="default"===a.Ia()?new gd(a,n):new qd(a,n);if(pd(j)||ud(h))j.add(l,a),j.rb||(j.rb=a.I.path);else{var q,x;j.f()||(q=j.toString(),x=j.Wa());j.add(l,a);j.rb||(j.rb=a.I.path);j.setActive(vd(this,j));q&&x&&this.u.ed(j.path(),q,x)}pd(j)&&Ua(h,function(a){if(a=a.j()){a.ra&&a.ra();
a.ra=m}});cd(a,b,c,d,e);(b=(b=Va(L(this.ta,f),function(a){var b;if(b=a.j())if(b=a.j().defaultView())b=a.j().defaultView().jb;if(b)return k},k))||this.u===m)&&fd(a)}};function wd(a,b,c,d,e){for(var f=a.get(b),h=o,j=f.ka.length-1;0<=j;j--){var l=f.ka[j];if((!c||l.type===c)&&(!d||l.ja===d)&&(!e||l.Y===e))if(f.ka.splice(j,1),h=k,c&&d)break}(c=h&&!(0<f.ka.length))&&a.remove(b);return c}td.prototype.Zb=function(a,b,c,d){var e=L(this.ta,a.path).j();return e===m?m:xd(this,e,a,b,c,d)};
function xd(a,b,c,d,e,f){var h=b.path(),h=L(a.ta,h),c=c?c.Ia():m,j=[];c&&"default"!==c?wd(b,c,d,e,f)&&j.push(c):kb(b.keys(),function(a){wd(b,a,d,e,f)&&j.push(a)});b.f()&&M(h,m);c=ud(h);if(0<j.length&&!c){for(var l=h,n=h.parent(),c=o;!c&&n;){var q=n.j();if(q){A(!pd(q));var x=l.name(),u=o;T(q.set,function(a){u=a.lc(x)||u});u&&(c=k)}l=n;n=n.parent()}l=m;if(!pd(b)){n=b.ra;b.ra=m;var w=[],K=function(b){var c=b.j();c&&od(c)?(w.push(c.path()),c.ra==m&&c.setActive(vd(a,c))):(c&&c.ra==m&&c.setActive(vd(a,
c)),b.A(K))};K(h);l=w;n&&n()}return c?m:l}return m}function yd(a,b,c){Ua(L(a.ta,b),function(a){(a=a.j())&&T(a.set,function(a){fd(a)})},c,k)}function zd(a,b,c){function d(a){for(var b=0;b<c.length;++b)if(c[b].contains(a))return k;return o}var e=a.Rc,f=a.i.Ka;a.Rc=f;var h=b.toString();id(e,f,b,a.ta,function(b,c,e){if(b.toString().substring(0,h.length)===h){var f=d(b);f&&yd(a,b,o);a.Vb(b,c,e);f&&yd(a,b,k)}else a.Vb(b,c,e)});d(b)&&yd(a,b,k)}
td.prototype.Vb=function(a,b,c){a=L(this.ta,a).j();a!==m&&T(a.set,function(a){a.Vb(b,c)})};function ud(a){return Va(a,function(a){return a.j()&&pd(a.j())})}
function vd(a,b){if(a.u){var c=b.keys(),d=a.u,e=function(d){"ok"!==d?(P("on() or once() for "+b.path().toString()+" failed: "+d),b&&T(b.set,function(a){for(var b=0;b<a.ka.length;b++){var c=a.ka[b];c.cancel&&(c.Y?y(c.cancel,c.Y):c.cancel)()}}),xd(a,b)):kb(c,function(a){(a=b.get(a))&&fd(a)})},f=b.toString(),h=b.path().toString();d.ga[h]=d.ga[h]||{};A(!d.ga[h][f],"listen() called twice for same path/queryId.");d.ga[h][f]={Wa:b.Wa(),G:e};d.fa&&Pc(d,h,f,b.Wa(),e);return y(a.u.ed,a.u,b.path(),b.toString(),
b.Wa())}return ca}td.prototype.hb=function(a,b,c,d){var e={};T(b.set,function(b){b=b.hb(a,c,d);T(b,function(a,b){e[b]=E(e,b)?e:a})});c.L()||c.A(function(a){E(e,a)||(e[a]=o)});return e};
function Ad(a,b,c,d,e,f){var h=b.path();if(f!==m){var j=[];d.L()||d.A(function(a,b){j.push({path:h.C(a),Ga:b});delete f[a]});T(f,function(a,b){j.push({path:h.C(b),Ga:Q})});return j}var b=a.hb(h,b,d,e),l=Q,n=[];T(b,function(b,f){var h=new J(f);b?l=l.D(f,d.F(h)):n=n.concat(Bd(a,d.F(h),L(c,h),e))});return[{path:h,Ga:l}].concat(n)}
function Cd(a,b,c,d,e){for(var f=L(a.ta,b),h=f.parent(),j=o;!j&&h!==m;){var l=h.j();l!==m&&(od(l)?j=k:(l=a.hb(b,l,c,d),f=f.name(),va(l,f)&&(j=k)));f=h;h=h.parent()}if(j)return[{path:b,Ga:c}];h=L(a.ta,b);j=h.j();return j!==m?od(j)?[{path:b,Ga:c}]:Ad(a,j,h,c,d,e):Bd(a,c,h,d)}function Bd(a,b,c,d){var e=c.j();if(e!==m)return od(e)?[{path:c.path(),Ga:b}]:Ad(a,e,c,b,d,m);if(b.L())return[];var f=[];b.A(function(b,e){var l=new J(b);f=f.concat(Bd(a,e,L(c,l),d))});return f};function Dd(a){this.B=a;this.R=oc(a);this.u=new Mc(this.B,y(this.Ob,this),y(this.ud,this),y(this.vd,this));var b=y(function(){return new lc(this.R,this.u)},this),a=a.toString();nc[a]||(nc[a]=b());this.bd=nc[a];this.dc=new Sa;this.i=new Wc;this.S=new td(this.u,this.i.Da);this.Lc=new Vc;this.mc=new td(m,this.Lc);Ed(this,o)}s=Dd.prototype;s.toString=function(){return(this.B.xb?"https://":"http://")+this.B.host};s.name=function(){return this.B.Ua};
s.Ob=function(a,b,c){var d=[],e=m;if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new J(a.substring(0,a.length-9)),c=V(this.i.Ba,a).gc(b),d.push(a);else if(c){var e=b,a=new J(a),c=V(this.i.Ba,a),f;for(f in b){var h=ec(b[f]),c=c.D(f,h);d.push(a.C(f))}}else a=new J(a),c=ec(b),d.push(a);b=Cd(this.S,a,c,this.i.M,e);e=o;for(f=0;f<b.length;++f){var c=b[f],h=this.i,j=c.path;W(h.Ba,j,c.Ga);e=Xc(h,j)||e}e&&(a=Fd(this,a),Gd(this,a),a=a.path());zd(this.S,a,d)};s.ud=function(){Ed(this,k)};
s.vd=function(){Ed(this,o)};function Ed(a,b){var c=new J("/.info/connected");W(a.Lc,c,ec(b));zd(a.mc,c,[c])}s.ab=function(a,b){this.u.ab(a,function(a){Hd(b,"ok"===a,a)})};s.Ab=function(){this.u.Ab()};
s.yb=function(a,b,c,d){this.e("set",{path:a.toString(),value:b});var b=ec(b,c),c=Cd(this.S,a,b,this.i.M,m),e=this.i.set(a,c),f=this;this.u.put(a.toString(),b.ea(k),function(b){var c="ok"===b;Zc(f.i,e);if(!c){P("set at "+a+" failed: "+b);Xc(f.i,a);var l=Fd(f,a);Gd(f,l);zd(f.S,l.path(),[])}Hd(d,c,b)});b=Fd(this,a);Id(this,a);Gd(this,b);zd(this.S,b.path(),[a])};
s.update=function(a,b,c){this.e("update",{path:a.toString(),value:b});var d=V(this.i.Da,a),e=k,f=[],h;for(h in b){var e=o,j=ec(b[h]),d=d.D(h,j);f.push(a.C(h))}if(e)Pb("update() called with empty data.  Don't do anything."),Hd(c,k);else{var d=Cd(this.S,a,d,this.i.M,b),l=this.i.set(a,d),n=this;Tc(this.u,"m",a.toString(),b,function(b){A("ok"===b||"permission_denied"===b,"merge at "+a+" failed.");var d="ok"===b;Zc(n.i,l);Hd(c,d,b)},i);b=Fd(this,a);Id(this,a);Gd(this,b);zd(this.S,b.path(),f)}};
s.bc=function(a,b,c){this.e("setPriority",{path:a.toString(),ya:b});var d=V(this.i.M,a).gc(b),d=Cd(this.S,a,d,this.i.M,m),e=this.i.set(a,d),f=this;this.u.put(a.toString()+"/.priority",b,function(a){var b="ok"===a;Zc(f.i,e);Hd(c,b,a)});a=Fd(this,a);Gd(this,a);zd(this.S,a.path(),[])};s.ac=function(a,b){this.u.W(a.toString(),b)};s.Cb=function(a,b,c,d,e){".info"===F(a.path)?this.mc.Cb(a,b,c,d,e):this.S.Cb(a,b,c,d,e)};
s.Zb=function(a,b,c,d){if(".info"===F(a.path))this.mc.Zb(a,b,c,d);else if(b=this.S.Zb(a,b,c,d),b!==m){for(var c=this.i,a=a.path,d=[],e=0;e<b.length;++e)d[e]=V(c.Ba,b[e]);W(c.Ba,a,Q);for(e=0;e<b.length;++e)W(c.Ba,b[e],d[e])}};s.Sa=function(){this.u.Sa()};s.vb=function(){this.u.vb()};
s.xc=function(a){if("undefined"!==typeof console){a?(this.cc||(this.cc=new kc(this.R)),a=this.cc.get()):a=this.R.get();var b=a,c=[],d=0,e;for(e in b)c[d++]=e;var f=function(a,b){return Math.max(b.length,a)};if(c.reduce)e=c.reduce(f,0);else{var h=0;kb(c,function(a){h=f.call(i,h,a)});e=h}for(var j in a){b=a[j];for(c=j.length;c<e+2;c++)j+=" ";console.log(j+b)}}};s.e=function(){Pb("r:"+this.u.id+":",arguments)};function Jd(a,b){var c=new Y(a,b);return new S(V(a.i.Da,b),c)}
function Hd(a,b,c){a&&(1===a.length?a(b):b?a(m):a(Error(c)))}
function Kd(a,b,c){ga(c)&&1===c.length&&(P("\n"+b+' was passed an onComplete callback that takes 1 argument.\nOn 2/4/2013, we are changing our callback signature from:\n    function(success) { /* success is true for success, false for failure. */ }\nto:\n    function(error) { /* error is null for success, an Error object for failure. */ }\n\nTHIS WILL BE A BREAKING CHANGE!  To fix your code, you can either:\n * Remove all parameters from your callback. E.g.:\n     function() { ... }\n * Opt in to the new behavior early by adding a "dummy" second argument. E.g.:\n     function(error, dummy) { ... }\nPlease email support@firebase.com for more info.'),jc(a.R,
"old_callback"),a.bd.yc.old_callback=k)};function Id(a,b){var c=L(a.dc,b);Va(c,function(b){Ld(a,b)});Ld(a,c);Ua(c,function(b){Ld(a,b)})}function Ld(a,b){var c=b.j();if(c!==m){for(var d=-1,e=[],f=0;f<c.length;f++)if(2===c[f].status)A(d===f-1,"All SENT items should be at beginning of queue."),d=f,c[f].status=4,c[f].Dc="set";else if(c[f].fc(),c[f].G){var h=Jd(a,b.path());e.push(Md(c[f].G,Error("set"),o,h))}-1===d?M(b,m):c.length=d+1;for(f=0;f<e.length;f++)e[f]()}}
function Nd(a,b){var c=b||a.dc;b||Od(a,c);if(!c.f())if(c.j()!==m){var d=Pd(a,c);if(0!==d.length){var e=c.path();if(2!==d[0].status&&4!==d[0].status){for(var f=0;f<d.length;f++)A(1===d[f].status,"tryToSendTransactionForNode_: items in queue should all be run."),d[f].status=2,d[f].Zc++;var h=V(a.i.M,e).hash();W(a.i.M,e,V(a.i.Da,e));var j=V(a.i.M,e).ea(k),l=Ib();M(L(a.i.sb,e),l);a.u.put(e.toString(),j,function(b){a.e("transaction put response",{path:e.toString(),status:b});var h=L(a.i.sb,e),j=h.j();
A(j!==m,"tryToSendTransactionsForNode_: pendingPut should not be null.");j===l&&(M(h,m),W(a.i.M,e,V(a.i.Ba,e)));if("ok"===b){b=[];for(f=0;f<d.length;f++)d[f].status=3,d[f].G&&(h=Jd(a,d[f].path),b.push(Md(d[f].G,m,k,h))),d[f].fc();Od(a,c);Nd(a);for(f=0;f<b.length;f++)b[f]()}else{if("datastale"===b)for(f=0;f<d.length;f++)d[f].status=4===d[f].status?5:1;else{P("transaction at "+e+" failed: "+b);for(f=0;f<d.length;f++)d[f].status=5,d[f].Dc=b}b=Fd(a,e);Gd(a,b);zd(a.S,b.path(),[e])}},h)}}}else c.A(function(b){Nd(a,
b)})}
function Gd(a,b){var c=b.path();W(a.i.Da,c,V(a.i.M,c));var d=Pd(a,b);if(0!==d.length){for(var e=V(a.i.Da,c),f=[],h=0;h<d.length;h++){var j=Qa(c,d[h].path),l=o,n;A(j!==m,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[h].status)l=k,n=d[h].Dc;else if(1===d[h].status)if(25<=d[h].Zc)l=k,n="maxretry";else{var q=d[h].update(e.F(j).ea());t(q)?(Ba("transaction failed: Data returned ",q),e=e.Za(j,ec(q))):(l=k,n="nodata")}l&&(d[h].fc(),d[h].status=3,d[h].G&&(l=new Y(a,d[h].path),j=
new S(e.F(j),l),"nodata"===n?f.push(Md(d[h].G,m,o,j)):f.push(Md(d[h].G,Error(n),o,j))))}d=V(a.i.M,c).m();W(a.i.Da,c,e.gc(d));Nd(a);for(h=0;h<f.length;h++)f[h]()}}function Fd(a,b){for(var c,d=a.dc;(c=F(b))!==m&&d.j()===m;)d=L(d,c),b=Ma(b);return d}function Pd(a,b){var c=[];Qd(a,b,c);c.sort(function(a,b){return a.Uc-b.Uc});return c}function Qd(a,b,c){var d=b.j();if(d!==m)for(var e=0;e<d.length;e++)c.push(d[e]);b.A(function(b){Qd(a,b,c)})}
function Od(a,b){var c=b.j();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;M(b,0<c.length?c:m)}b.A(function(b){Od(a,b)})}function Md(a,b,c,d){return!a?p():0<a.length&&4>a.length?function(){a(c,d,b===m?"":b.message)}:function(){a(b,c,d)}};function Z(){this.Xa={}}Z.qd=function(){return Z.Mc?Z.Mc:Z.Mc=new Z};Z.prototype.Sa=function(){for(var a in this.Xa)this.Xa[a].Sa()};Z.prototype.interrupt=Z.prototype.Sa;Z.prototype.vb=function(){for(var a in this.Xa)this.Xa[a].vb()};Z.prototype.resume=Z.prototype.vb;var $={rd:function(a){var b=R.prototype.hash;R.prototype.hash=a;return function(){R.prototype.hash=b}}};$.hijackHash=$.rd;$.Ia=function(a){return a.Ia()};$.queryIdentifier=$.Ia;$.td=function(a){return a.k.u.ga};$.listens=$.td;$.Bd=function(a){return a.k.u.ub};$.refConnection=$.Bd;$.gd=Mc;$.DataConnection=$.gd;Mc.prototype.sendRequest=Mc.prototype.Aa;Mc.prototype.interrupt=Mc.prototype.Sa;$.hd=U;$.RealTimeConnection=$.hd;U.prototype.sendRequest=U.prototype.wc;U.prototype.close=U.prototype.close;
$.fd=rb;$.ConnectionTarget=$.fd;$.pd=function(){zc=vc=k};$.forceLongPolling=$.pd;$.Fd=function(a,b){a.k.u.uc=b};$.setSecurityDebugCallback=$.Fd;$.xc=function(a,b){a.k.xc(b)};$.stats=$.xc;var Rd,Sd=0,Td=[];Rd=function(){var a=(new Date).getTime()+Wb,b=a===Sd;Sd=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);A(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===Td[d];d--)Td[d]=0;Td[d]++}else for(d=0;12>d;d++)Td[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(Td[d]);A(20===a.length,"NextPushId: Length should be 20.");return a};function Y(){var a,b,c;if(arguments[0]instanceof Dd)c=arguments[0],a=arguments[1];else{B("new Firebase",1,2,arguments.length);var d=arguments[0],e="";a="";b=k;var f="";if(v(d)){e=d.indexOf("//");0<=e&&(b="http:"!==d.substring(0,e),d=d.substring(e+2));var h=d.indexOf("/");-1===h&&(h=d.length);e=d.substring(0,h);d=d.substring(h+1);h=e.split(".");if(3==h.length){if("firebase"===h[1])Tb(e+" is no longer supported. Please use <YOUR FIREBASE>.firebaseio.com instead");else{a=h[0];f="";d=("/"+d).split("/");
for(h=0;h<d.length;h++)if(0<d[h].length){var j=d[h];try{j=decodeURIComponent(j.replace(/\+/g," "))}catch(l){}f+="/"+j}}a=a.toLowerCase()}else a=m}b||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&P("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new rb(e,b,a);b=new J(f);e=b.toString();if(!(d=!v(a.host)))if(!(d=0===a.host.length))if(!(d=!za(a.Ua)))if(d=0!==e.length)e&&(e=e.replace(/^\/*\.info(\/|$)/,
"/")),d=!(v(e)&&0!==e.length&&!ya.test(e));d&&g(Error(C("new Firebase",1,o)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Z?c=arguments[1]:g(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Z.qd();e=a.toString();d=va(c.Xa,e);d||(d=new Dd(a),c.Xa[e]=d);c=d;a=b}H.call(this,c,a)}ka(Y,H);var Ud=Y,Vd=["Firebase"],Wd=ba;!(Vd[0]in Wd)&&Wd.execScript&&Wd.execScript("var "+Vd[0]);
for(var Xd;Vd.length&&(Xd=Vd.shift());)!Vd.length&&t(Ud)?Wd[Xd]=Ud:Wd=Wd[Xd]?Wd[Xd]:Wd[Xd]={};module.exports=Y;Y.prototype.name=function(){B("Firebase.name",0,0,arguments.length);return this.path.f()?m:Pa(this.path)};Y.prototype.name=Y.prototype.name;
Y.prototype.C=function(a){B("Firebase.child",1,1,arguments.length);if(fa(a))a=String(a);else if(!(a instanceof J))if(F(this.path)===m){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Ha("Firebase.child",b)}else Ha("Firebase.child",a);return new Y(this.k,this.path.C(a))};Y.prototype.child=Y.prototype.C;Y.prototype.parent=function(){B("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===m?m:new Y(this.k,a)};Y.prototype.parent=Y.prototype.parent;
Y.prototype.toString=function(){B("Firebase.toString",0,0,arguments.length);var a;if(this.parent()===m)a=this.k.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};Y.prototype.toString=Y.prototype.toString;Y.prototype.set=function(a,b){B("Firebase.set",1,2,arguments.length);Ia("Firebase.set",this.path);Aa("Firebase.set",a,o);D("Firebase.set",2,b,k);Kd(this.k,"Firebase.set",b);return this.k.yb(this.path,a,m,b)};Y.prototype.set=Y.prototype.set;
Y.prototype.update=function(a,b){B("Firebase.update",1,2,arguments.length);Ia("Firebase.update",this.path);ha(a)||g(Error(C("Firebase.update",1,o)+" must be an object containing the children to replace."));Aa("Firebase.update",a,o);D("Firebase.update",2,b,k);Kd(this.k,"Firebase.update",b);return this.k.update(this.path,a,b)};Y.prototype.update=Y.prototype.update;
Y.prototype.yb=function(a,b,c){B("Firebase.setWithPriority",2,3,arguments.length);Ia("Firebase.setWithPriority",this.path);Aa("Firebase.setWithPriority",a,o);Ea("Firebase.setWithPriority",2,b,o);D("Firebase.setWithPriority",3,c,k);Kd(this.k,"Firebase.setWithPriority",c);(".length"===this.name()||".keys"===this.name())&&g("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.k.yb(this.path,a,b,c)};Y.prototype.setWithPriority=Y.prototype.yb;
Y.prototype.remove=function(a){B("Firebase.remove",0,1,arguments.length);Ia("Firebase.remove",this.path);D("Firebase.remove",1,a,k);Kd(this.k,"Firebase.remove",a);this.set(m,a)};Y.prototype.remove=Y.prototype.remove;
Y.prototype.transaction=function(a,b){function c(){}B("Firebase.transaction",1,2,arguments.length);Ia("Firebase.transaction",this.path);D("Firebase.transaction",1,a,o);D("Firebase.transaction",2,b,k);var d=this.k;ga(b)&&(0<b.length&&4>b.length)&&(P("\nFirebase.transaction was passed an onComplete callback that takes "+b.length+' arguments.\nOn 2/4/2013, we are changing our transaction callback signature from:\n    function(success, snapshot, abortReason) {\n        // success is true if the transaction was committed, false for any failure.\n    }\nto:\n    function(error, committed, snapshot) { \n        // error is an Error object on fatal errors, else null.\n        // committed is true if the transaction was committed, false if you returned no data from your update function.\n    }\n\nTHIS WILL BE A BREAKING CHANGE!  To fix your code, you can either:\n * Remove all parameters from your callback. E.g.:\n   function() { ... }\n * Opt in to the new behavior early by adding a 4th "dummy" argument. E.g.:\n   function(error, committed, snapshot, dummy) { ... }\nPlease email support@firebase.com for more info.'),
jc(d.R,"old_callback_transaction"),d.bd.yc.old_callback_transaction=k);(".length"===this.name()||".keys"===this.name())&&g("Firebase.transaction failed: "+this.name()+" is a read-only object.");var e=this.k,f=this.path;e.e("transaction on "+f);var h=new Y(e,f);h.pc("value",c);var d={path:f,update:a,G:b,Uc:Ib(),Zc:0,fc:function(){h.Mb("value",c)}},j=e.i.Da,l=d.update(V(j,f).ea());if(t(l)){Ba("transaction failed: Data returned ",l);var n=V(e.i.M,f).m();W(j,f,ec(l,n));zd(e.S,f,[f]);d.status=1;f=L(e.dc,
f);j=f.j()||[];j.push(d);M(f,j);Nd(e)}else d.fc(),d.G&&(e=Jd(e,f),Md(d.G,m,o,e)())};Y.prototype.transaction=Y.prototype.transaction;Y.prototype.bc=function(a,b){B("Firebase.setPriority",1,2,arguments.length);Ia("Firebase.setPriority",this.path);Ea("Firebase.setPriority",1,a,o);D("Firebase.setPriority",2,b,k);Kd(this.k,"Firebase.setPriority",b);this.k.bc(this.path,a,b)};Y.prototype.setPriority=Y.prototype.bc;
Y.prototype.push=function(a,b){B("Firebase.push",0,2,arguments.length);Ia("Firebase.push",this.path);Aa("Firebase.push",a,k);D("Firebase.push",2,b,k);Kd(this.k,"Firebase.push",b);var c=Rd(),c=this.C(c);"undefined"!==typeof a&&a!==m&&c.set(a,b);return c};Y.prototype.push=Y.prototype.push;Y.prototype.W=function(){var a=this;return{set:function(b){a.k.ac(a.path,b)},yb:p(),bc:p(),remove:function(){a.k.ac(a.path,m)},update:p(),cancel:p()}};Y.prototype.onDisconnect=Y.prototype.W;
Y.prototype.Cd=function(){B("Firebase.removeOnDisconnect",0,0,arguments.length);P("FirebaseRef.removeOnDisconnect() being deprecated. Please use FirebaseRef.onDisconnect().remove() instead.");this.W().remove()};Y.prototype.removeOnDisconnect=Y.prototype.Cd;Y.prototype.ac=function(a){B("Firebase.setOnDisconnect",1,1,arguments.length);Aa("Firebase.setOnDisconnect",a,o);P("FirebaseRef.setOnDisconnect(value) being deprecated. Please use FirebaseRef.onDisconnect().set(value) instead.");this.W().set(a)};
Y.prototype.setOnDisconnect=Y.prototype.ac;Y.prototype.ab=function(a,b){B("Firebase.auth",1,2,arguments.length);v(a)||g(Error(C("Firebase.auth",1,o)+"must be a valid credential (a string)."));D("Firebase.auth",2,b,k);Kd(this.k,"Firebase.auth",b);this.k.ab(a,b)};Y.prototype.auth=Y.prototype.ab;Y.prototype.Ab=function(){this.k.Ab()};Y.prototype.unauth=Y.prototype.Ab;
function Qb(a,b){A(!b||a===k||a===o,"Can't turn on custom loggers persistently.");a===k?("undefined"!==typeof console&&("function"===typeof console.log?Nb=y(console.log,console):"object"===typeof console.log&&(Nb=function(a){console.log(a)})),b&&O.setItem("logging_enabled","true")):a?Nb=a:(Nb=m,O.removeItem("logging_enabled"))}Y.enableLogging=Qb;Y.INTERNAL=$;Y.Context=Z;

exports.Firebase = Firebase;
