
// this is firebase.js with long-polling disabled, some window.* -like
// globals added, and a final "exports.Firebase = Firebase" at the end.

var WebSocket = require("websocket").WebSocket; // must provide this
var setTimeout = require("timers").setTimeout;
var clearTimeout = require("timers").clearTimeout;
var setInterval = require("timers").setInterval;

(function() {function g(a){throw a;}var i=void 0,k=!0,m=null,n=!1;function p(){return function(){}}function aa(a){return function(){return this[a]}}function r(a){return function(){return a}}var s,ba=this;function ca(){}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return a!==i}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function fa(a){return"number"==typeof a}function ga(a){return"function"==da(a)}function ha(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return y.apply(m,arguments)}function ka(a,b){function c(){}c.prototype=b.prototype;a.Fd=b.prototype;a.prototype=new c};function la(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function ma(){this.Sb=i}
function na(a,b,c){switch(typeof b){case "string":oa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if("array"==da(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],na(a,a.Sb?a.Sb.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),
oa(f,c),c.push(":"),na(a,a.Sb?a.Sb.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var pa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},qa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function oa(a,b){b.push('"',a.replace(qa,function(a){if(a in pa)return pa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return pa[a]=e+b.toString(16)}),'"')};function z(a){if("undefined"!==typeof JSON&&t(JSON.stringify))a=JSON.stringify(a);else{var b=[];na(new ma,a,b);a=b.join("")}return a};function ra(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);55296<=e&&56319>=e&&(e-=55296,d++,A(d<a.length,"Surrogate pair missing trail surrogate."),e=65536+(e<<10)+(a.charCodeAt(d)-56320));128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(65536>e?b[c++]=e>>12|224:(b[c++]=e>>18|240,b[c++]=e>>12&63|128),b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};function B(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&g(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function C(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:sa.assert(n,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}return a+" failed: "+(d+" argument ")}
function D(a,b,c,d){(!d||t(c))&&!ga(c)&&g(Error(C(a,b,d)+"must be a valid function."))}function ta(a,b,c){t(c)&&(!ha(c)||c===m)&&g(Error(C(a,b,k)+"must be a valid context object."))};function E(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function ua(a,b){if(Object.prototype.hasOwnProperty.call(a,b))return a[b]};var va={},sa={},wa=/[\[\].#$\/]/,xa=/[\[\].#$]/;function ya(a){return v(a)&&0!==a.length&&!wa.test(a)}function za(a,b,c){(!c||t(b))&&Aa(C(a,1,c),b)}
function Aa(a,b,c,d){c||(c=0);d||(d=[]);t(b)||g(Error(a+"contains undefined"+Ba(d)));ga(b)&&g(Error(a+"contains a function"+Ba(d)));Ca(b)&&g(Error(a+"contains "+b.toString()+Ba(d)));1E3<c&&g(new TypeError(a+"contains a cyclic object value ("+d.slice(0,100).join(".")+"...)"));v(b)&&(b.length>10485760/3&&10485760<va.Gd.Ed(b).length)&&g(Error(a+"contains a string greater than 10485760 utf8 bytes"+Ba(d)+" ('"+b.substring(0,50)+"...')"));if(ha(b))for(var e in b)E(b,e)&&(".priority"!==e&&(".value"!==e&&
!ya(e))&&g(Error(a+"contains an invalid key ("+e+")"+Ba(d)+'.  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),d.push(e),Aa(a,b[e],c+1,d),d.pop())}function Ba(a){return 0==a.length?"":" in property "+a.join(".")}function Da(a,b,c,d){(!d||t(c))&&(c!==m&&!fa(c)&&!v(c))&&g(Error(C(a,b,d)+"must be a valid firebase priority (null or a string.)"))}
function Ea(a,b,c){if(!c||t(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:g(Error(C(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}function Fa(a,b){t(b)&&!ya(b)&&g(Error(C(a,2,k)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}
function Ga(a,b){(!v(b)||0===b.length||xa.test(b))&&g(Error(C(a,1,n)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function Ha(a,b){".info"===F(b)&&g(Error(a+" failed: Can't modify data under /.info/"))};function H(a,b,c,d,e,f,h){this.k=a;this.path=b;this.ta=c;this.Z=d;this.la=e;this.ra=f;this.Ma=h;t(this.Z)&&(t(this.ra)&&t(this.ta))&&g("Query: Can't combine startAt(), endAt(), and limit().")}H.prototype.lc=function(a,b){B("Query.on",2,4,arguments.length);Ea("Query.on",a,n);D("Query.on",2,b,n);var c=Ia("Query.on",arguments[2],arguments[3]);this.k.wb(this,a,b,c.cancel,c.V);return b};H.prototype.on=H.prototype.lc;
H.prototype.Eb=function(a,b,c){B("Query.off",0,3,arguments.length);Ea("Query.off",a,k);D("Query.off",2,b,k);ta("Query.off",3,c);this.k.Rb(this,a,b,c)};H.prototype.off=H.prototype.Eb;H.prototype.td=function(a,b){function c(h){f&&(f=n,e.Eb(a,c),b.call(d.V,h))}B("Query.once",2,4,arguments.length);Ea("Query.once",a,n);D("Query.once",2,b,n);var d=Ia("Query.once",arguments[2],arguments[3]),e=this,f=k;this.lc(a,c,function(){e.Eb(a,c);d.cancel&&d.cancel.call(d.V)})};H.prototype.once=H.prototype.td;
H.prototype.nd=function(a){B("Query.limit",1,1,arguments.length);(!fa(a)||Math.floor(a)!==a||0>=a)&&g("Query.limit: First argument must be a positive integer.");return new H(this.k,this.path,a,this.Z,this.la,this.ra,this.Ma)};H.prototype.limit=H.prototype.nd;H.prototype.Bd=function(a,b){B("Query.startAt",0,2,arguments.length);Da("Query.startAt",1,a,k);Fa("Query.startAt",b);t(a)||(b=a=m);return new H(this.k,this.path,this.ta,a,b,this.ra,this.Ma)};H.prototype.startAt=H.prototype.Bd;
H.prototype.hd=function(a,b){B("Query.endAt",0,2,arguments.length);Da("Query.endAt",1,a,k);Fa("Query.endAt",b);return new H(this.k,this.path,this.ta,this.Z,this.la,a,b)};H.prototype.endAt=H.prototype.hd;function Ja(a){var b={};t(a.Z)&&(b.sp=a.Z);t(a.la)&&(b.sn=a.la);t(a.ra)&&(b.ep=a.ra);t(a.Ma)&&(b.en=a.Ma);t(a.ta)&&(b.l=a.ta);t(a.Z)&&(t(a.la)&&a.Z===m&&a.la===m)&&(b.vf="l");return b}H.prototype.Fa=function(){var a=Ka(Ja(this));return"{}"===a?"default":a};
function Ia(a,b,c){var d={};b&&c?(d.cancel=b,D(a,3,d.cancel,k),d.V=c,ta(a,4,d.V)):b&&("object"===typeof b&&b!==m?d.V=b:"function"===typeof b?d.cancel=b:g(Error(C(a,3,k)+"must either be a cancel callback or a context object.")));return d};function J(a){if(a instanceof J)return a;if(1==arguments.length){this.n=a.split("/");for(var b=0,c=0;c<this.n.length;c++)0<this.n[c].length&&(this.n[b]=this.n[c],b++);this.n.length=b;this.X=0}else this.n=arguments[0],this.X=arguments[1]}function F(a){return a.X>=a.n.length?m:a.n[a.X]}function La(a){var b=a.X;b<a.n.length&&b++;return new J(a.n,b)}function Ma(a){return a.X<a.n.length?a.n[a.n.length-1]:m}s=J.prototype;
s.toString=function(){for(var a="",b=this.X;b<this.n.length;b++)""!==this.n[b]&&(a+="/"+this.n[b]);return a||"/"};s.parent=function(){if(this.X>=this.n.length)return m;for(var a=[],b=this.X;b<this.n.length-1;b++)a.push(this.n[b]);return new J(a,0)};s.B=function(a){for(var b=[],c=this.X;c<this.n.length;c++)b.push(this.n[c]);if(a instanceof J)for(c=a.X;c<a.n.length;c++)b.push(a.n[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new J(b,0)};
s.f=function(){return this.X>=this.n.length};function Na(a,b){var c=F(a);if(c===m)return b;if(c===F(b))return Na(La(a),La(b));g("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")}s.contains=function(a){var b=0;if(this.n.length>a.n.length)return n;for(;b<this.n.length;){if(this.n[b]!==a.n[b])return n;++b}return k};function Qa(){this.children={};this.ec=0;this.value=m}function Ra(a,b,c){this.Bb=a?a:"";this.jb=b?b:m;this.u=c?c:new Qa}function L(a,b){for(var c=b instanceof J?b:new J(b),d=a,e;(e=F(c))!==m;)d=new Ra(e,d,ua(d.u.children,e)||new Qa),c=La(c);return d}s=Ra.prototype;s.j=function(){return this.u.value};function M(a,b){A("undefined"!==typeof b);a.u.value=b;Sa(a)}s.zb=function(){return 0<this.u.ec};s.f=function(){return this.j()===m&&!this.zb()};
s.A=function(a){for(var b in this.u.children)a(new Ra(b,this,this.u.children[b]))};function Ta(a,b,c,d){c&&!d&&b(a);a.A(function(a){Ta(a,b,k,d)});c&&d&&b(a)}function Ua(a,b,c){for(a=c?a:a.parent();a!==m;){if(b(a))return k;a=a.parent()}return n}s.path=function(){return new J(this.jb===m?this.Bb:this.jb.path()+"/"+this.Bb)};s.name=aa("Bb");s.parent=aa("jb");
function Sa(a){if(a.jb!==m){var b=a.jb,c=a.Bb,d=a.f(),e=E(b.u.children,c);d&&e?(delete b.u.children[c],b.u.ec--,Sa(b)):!d&&!e&&(b.u.children[c]=a.u,b.u.ec++,Sa(b))}};function N(a,b){this.Ja=a?a:Va;this.Y=b?b:Wa}function Va(a,b){return a<b?-1:a>b?1:0}s=N.prototype;s.ha=function(a,b){return new N(this.Ja,this.Y.ha(a,b,this.Ja).copy(m,m,n,m,m))};s.remove=function(a){return new N(this.Ja,this.Y.remove(a,this.Ja).copy(m,m,n,m,m))};s.get=function(a){for(var b,c=this.Y;!c.f();){b=this.Ja(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return m};
function Xa(a,b){for(var c,d=a.Y,e=m;!d.f();){c=a.Ja(b,d.key);if(0===c){if(d.left.f())return e?e.key:m;for(d=d.left;!d.right.f();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}g("Attempted to find predecessor key for a nonexistent key.  What gives?")}s.f=function(){return this.Y.f()};s.count=function(){return this.Y.count()};s.fb=function(){return this.Y.fb()};s.Pa=function(){return this.Y.Pa()};s.sa=function(a){return this.Y.sa(a)};s.Ga=function(a){return this.Y.Ga(a)};
s.Na=function(a){return new Ya(this.Y,a)};function Ya(a,b){this.Tc=b;for(this.Cb=[];!a.f();)this.Cb.push(a),a=a.left}function Za(a){if(0===a.Cb.length)return m;var b=a.Cb.pop(),c;c=a.Tc?a.Tc(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.f();)a.Cb.push(b),b=b.left;return c}function $a(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=m?c:k;this.left=d!=m?d:Wa;this.right=e!=m?e:Wa}s=$a.prototype;
s.copy=function(a,b,c,d,e){return new $a(a!=m?a:this.key,b!=m?b:this.value,c!=m?c:this.color,d!=m?d:this.left,e!=m?e:this.right)};s.count=function(){return this.left.count()+1+this.right.count()};s.f=r(n);s.sa=function(a){return this.left.sa(a)||a(this.key,this.value)||this.right.sa(a)};s.Ga=function(a){return this.right.Ga(a)||a(this.key,this.value)||this.left.Ga(a)};function ab(a){return a.left.f()?a:ab(a.left)}s.fb=function(){return ab(this).key};
s.Pa=function(){return this.right.f()?this.key:this.right.Pa()};s.ha=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(m,m,m,e.left.ha(a,b,c),m):0===d?e.copy(m,b,m,m,m):e.copy(m,m,m,m,e.right.ha(a,b,c));return bb(e)};function cb(a){if(a.left.f())return Wa;!a.left.G()&&!a.left.left.G()&&(a=db(a));a=a.copy(m,m,m,cb(a.left),m);return bb(a)}
s.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.f()&&(!c.left.G()&&!c.left.left.G())&&(c=db(c)),c=c.copy(m,m,m,c.left.remove(a,b),m);else{c.left.G()&&(c=eb(c));!c.right.f()&&(!c.right.G()&&!c.right.left.G())&&(c=fb(c),c.left.left.G()&&(c=eb(c),c=fb(c)));if(0===b(a,c.key)){if(c.right.f())return Wa;d=ab(c.right);c=c.copy(d.key,d.value,m,m,cb(c.right))}c=c.copy(m,m,m,m,c.right.remove(a,b))}return bb(c)};s.G=aa("color");
function bb(a){a.right.G()&&!a.left.G()&&(a=gb(a));a.left.G()&&a.left.left.G()&&(a=eb(a));a.left.G()&&a.right.G()&&(a=fb(a));return a}function db(a){a=fb(a);a.right.left.G()&&(a=a.copy(m,m,m,m,eb(a.right)),a=gb(a),a=fb(a));return a}function gb(a){var b;b=a.copy(m,m,k,m,a.right.left);return a.right.copy(m,m,a.color,b,m)}function eb(a){var b;b=a.copy(m,m,k,a.left.right,m);return a.left.copy(m,m,a.color,m,b)}
function fb(a){var b,c;b=a.left.copy(m,m,!a.left.color,m,m);c=a.right.copy(m,m,!a.right.color,m,m);return a.copy(m,m,!a.color,b,c)}function hb(){}s=hb.prototype;s.copy=function(){return this};s.ha=function(a,b){return new $a(a,b,i,i,i)};s.remove=function(){return this};s.get=r(m);s.count=r(0);s.f=r(k);s.sa=r(n);s.Ga=r(n);s.fb=r(m);s.Pa=r(m);s.G=r(n);var Wa=new hb;var ib=Array.prototype,jb=ib.forEach?function(a,b,c){ib.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},kb=ib.map?function(a,b,c){return ib.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};function lb(){};function mb(){this.z=[];this.dc=[];this.ed=[];this.Jb=[];this.Jb[0]=128;for(var a=1;64>a;++a)this.Jb[a]=0;this.reset()}ka(mb,lb);mb.prototype.reset=function(){this.z[0]=1732584193;this.z[1]=4023233417;this.z[2]=2562383102;this.z[3]=271733878;this.z[4]=3285377520;this.wc=this.$a=0};
function nb(a,b){var c;c||(c=0);for(var d=a.ed,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}c=a.z[0];for(var h=a.z[1],j=a.z[2],l=a.z[3],o=a.z[4],q,e=0;80>e;e++)40>e?20>e?(f=l^h&(j^l),q=1518500249):(f=h^j^l,q=1859775393):60>e?(f=h&j|l&(h|j),q=2400959708):(f=h^j^l,q=3395469782),f=(c<<5|c>>>27)+f+o+q+d[e]&4294967295,o=l,l=j,j=(h<<30|h>>>2)&4294967295,h=c,c=f;a.z[0]=a.z[0]+c&4294967295;a.z[1]=a.z[1]+h&
4294967295;a.z[2]=a.z[2]+j&4294967295;a.z[3]=a.z[3]+l&4294967295;a.z[4]=a.z[4]+o&4294967295}mb.prototype.update=function(a,b){t(b)||(b=a.length);var c=this.dc,d=this.$a,e=0;if(v(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(nb(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(nb(this,c),d=0);this.$a=d;this.wc+=b};function ob(){this.Ia={};this.length=0}ob.prototype.setItem=function(a,b){E(this.Ia,a)||(this.length+=1);this.Ia[a]=b};ob.prototype.getItem=function(a){return E(this.Ia,a)?this.Ia[a]:m};ob.prototype.removeItem=function(a){E(this.Ia,a)&&(this.length-=1,delete this.Ia[a])};var O=m;if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),O=sessionStorage}catch(pb){O=new ob}else O=new ob;function qb(a,b,c,d){this.host=a;this.Tb=b;this.gb=c;this.ba=d||O.getItem(a)||this.host}function rb(a,b){b!==a.ba&&(a.ba=b,"s-"===a.ba.substr(0,2)&&O.setItem(a.host,a.ba))}qb.prototype.toString=function(){return(this.Tb?"https://":"http://")+this.host};var sb,tb,ub,vb;function wb(){return ba.navigator?ba.navigator.userAgent:m}vb=ub=tb=sb=n;var xb;if(xb=wb()){var yb=ba.navigator;sb=0==xb.indexOf("Opera");tb=!sb&&-1!=xb.indexOf("MSIE");ub=!sb&&-1!=xb.indexOf("WebKit");vb=!sb&&!ub&&"Gecko"==yb.product}var zb=tb,Ab=vb,Bb=ub;var Cb;if(sb&&ba.opera){var Db=ba.opera.version;"function"==typeof Db&&Db()}else Ab?Cb=/rv\:([^\);]+)(\)|;)/:zb?Cb=/MSIE\s+([^\);]+)(\)|;)/:Bb&&(Cb=/WebKit\/(\S+)/),Cb&&Cb.exec(wb());var Eb=m,Fb=m;
function Gb(a,b){ea(a)||g(Error("encodeByteArray takes an array as a parameter"));if(!Eb){Eb={};Fb={};for(var c=0;65>c;c++)Eb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),Fb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?Fb:Eb,d=[],e=0;e<a.length;e+=3){var f=a[e],h=e+1<a.length,j=h?a[e+1]:0,l=e+2<a.length,o=l?a[e+2]:0,q=f>>2,f=(f&3)<<4|j>>4,j=(j&15)<<2|o>>6,o=o&63;l||(o=64,h||(j=64));d.push(c[q],c[f],c[j],c[o])}return d.join("")}
;var Hb,Ib=1;Hb=function(){return Ib++};function A(a,b){a||g(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function Jb(a){var b=ra(a),a=new mb;a.update(b);var b=[],c=8*a.wc;56>a.$a?a.update(a.Jb,56-a.$a):a.update(a.Jb,64-(a.$a-56));for(var d=63;56<=d;d--)a.dc[d]=c&255,c/=256;nb(a,a.dc);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.z[d]>>e&255;return Gb(b)}
function Kb(){for(var a="",b=0;b<arguments.length;b++)a=ea(arguments[b])?a+Kb.apply(m,arguments[b]):"object"===typeof arguments[b]?a+z(arguments[b]):a+arguments[b],a+=" ";return a}var Lb=m,Mb=k;function Nb(){Mb===k&&(Mb=n,Lb===m&&"true"===O.getItem("logging_enabled")&&Ob(k));if(Lb){var a=Kb.apply(m,arguments);Lb(a)}}function Pb(a){return function(){Nb(a,arguments)}}
function Qb(){if("undefined"!==typeof console){var a="FIREBASE INTERNAL ERROR: "+Kb.apply(m,arguments);"undefined"!==typeof console.error?console.error(a):console.log(a)}}function Rb(){var a=Kb.apply(m,arguments);g(Error("FIREBASE FATAL ERROR: "+a))}function P(){if("undefined"!==typeof console){var a="FIREBASE WARNING: "+Kb.apply(m,arguments);"undefined"!==typeof console.warn?console.warn(a):console.log(a)}}
function Ca(a){return fa(a)&&(a!=a||a==Number.POSITIVE_INFINITY||a==Number.NEGATIVE_INFINITY)}function Sb(a,b){return a!==b?a===m?-1:b===m?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Ub(a,b){if(b&&a in b)return b[a];g(Error("Missing required key ("+a+") in object: "+z(b)))}var Vb=0;function Ka(a){if("object"!==typeof a||a===m)return z(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=z(b[d]),c+=":",c+=Ka(a[b[d]]);return c+"}"}
function Wb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c}
function Xb(a){A(!Ca(a));var b,c,d,e;0===a?(d=c=0,b=-Infinity===1/a?1:0):(b=0>a,a=Math.abs(a),a>=Math.pow(2,-1022)?(d=Math.min(Math.floor(Math.log(a)/Math.LN2),1023),c=d+1023,d=Math.round(a*Math.pow(2,52-d)-Math.pow(2,52))):(c=0,d=Math.round(a/Math.pow(2,-1074))));e=[];for(a=52;a;a-=1)e.push(d%2?1:0),d=Math.floor(d/2);for(a=11;a;a-=1)e.push(c%2?1:0),c=Math.floor(c/2);e.push(b?1:0);e.reverse();b=e.join("");c="";for(a=0;64>a;a+=8)d=parseInt(b.substr(a,8),2).toString(16),1===d.length&&(d="0"+d),c+=d;
return c.toLowerCase()};function Yb(a,b){this.oa=a;A(this.oa!==m,"LeafNode shouldn't be created with null value.");this.Ra="undefined"!==typeof b?b:m}s=Yb.prototype;s.J=r(k);s.m=aa("Ra");s.bc=function(a){return new Yb(this.oa,a)};s.M=function(){return Q};s.D=function(a){return F(a)===m?this:Q};s.Q=r(m);s.C=function(a,b){return(new R(new N,this.Ra)).C(a,b)};s.Va=function(a,b){var c=F(a);return c===m?b:this.C(c,Q.Va(La(a),b))};s.f=r(n);s.Db=r(0);
s.$=function(a){return a&&this.m()!==m?{".value":this.j(),".priority":this.m()}:this.j()};s.hash=function(){var a="";this.m()!==m&&(a+="priority:"+Zb(this.m())+":");var b=typeof this.oa,a=a+(b+":"),a="number"===b?a+Xb(this.oa):a+this.oa;return Jb(a)};s.j=aa("oa");s.toString=function(){return"string"===typeof this.oa?'"'+this.oa+'"':this.oa};function R(a,b){this.P=a||new N;this.Ra="undefined"!==typeof b?b:m}s=R.prototype;s.J=r(n);s.m=aa("Ra");s.bc=function(a){return new R(this.P,a)};s.C=function(a,b){var c=this.P.remove(a);b&&b.f()&&(b=m);b!==m&&(c=c.ha(a,b));return b&&b.m()!==m?new $b(c,m,this.Ra):new R(c,this.Ra)};s.Va=function(a,b){var c=F(a);if(c===m)return b;var d=this.M(c).Va(La(a),b);return this.C(c,d)};s.f=function(){return this.P.f()};s.Db=function(){return this.P.count()};var ac=/^\d+$/;s=R.prototype;
s.$=function(a){if(this.f())return m;var b={},c=0,d=0,e=k;this.A(function(f,h){b[f]=h.$(a);c++;e&&ac.test(f)?d=Math.max(d,Number(f)):e=n});if(!a&&e&&d<2*c){var f=[],h;for(h in b)f[h]=b[h];return f}a&&this.m()!==m&&(b[".priority"]=this.m());return b};s.hash=function(){var a="";this.m()!==m&&(a+="priority:"+Zb(this.m())+":");this.A(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Jb(a)};s.M=function(a){a=this.P.get(a);return a===m?Q:a};
s.D=function(a){var b=F(a);return b===m?this:this.M(b).D(La(a))};s.Q=function(a){return Xa(this.P,a)};s.Gc=function(){return this.P.fb()};s.Hc=function(){return this.P.Pa()};s.A=function(a){return this.P.sa(a)};s.ic=function(a){return this.P.Ga(a)};s.Na=function(){return this.P.Na()};s.toString=function(){var a="{",b=k;this.A(function(c,d){b?b=n:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var Q=new R(new N);function $b(a,b,c){R.call(this,a,c);b===m&&(b=new N(bc),a.sa(function(a,c){b=b.ha({name:a,ua:c.m()},c)}));this.ka=b}ka($b,R);s=$b.prototype;s.C=function(a,b){var c=this.M(a),d=this.P,e=this.ka;c!==m&&(d=d.remove(a),e=e.remove({name:a,ua:c.m()}));b&&b.f()&&(b=m);b!==m&&(d=d.ha(a,b),e=e.ha({name:a,ua:b.m()},b));return new $b(d,e,this.m())};s.Q=function(a,b){var c=Xa(this.ka,{name:a,ua:b.m()});return c?c.name:m};s.A=function(a){return this.ka.sa(function(b,c){return a(b.name,c)})};
s.ic=function(a){return this.ka.Ga(function(b,c){return a(b.name,c)})};s.Na=function(){return this.ka.Na(function(a,b){return{key:a.name,value:b}})};s.Gc=function(){return this.ka.f()?m:this.ka.fb().name};s.Hc=function(){return this.ka.f()?m:this.ka.Pa().name};function cc(a,b){if("object"!==typeof a)return new Yb(a,b);if(a===m)return Q;var c=m;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);A(c===m||"string"===typeof c||"number"===typeof c);if(".value"in a&&a[".value"]!==m)return new Yb(a[".value"],c);var c=new R(new N,c),d;for(d in a)if(E(a,d)&&"."!==d.substring(0,1)){var e=cc(a[d]);if(e.J()||!e.f())c=c.C(d,e)}return c}function bc(a,b){return Sb(a.ua,b.ua)||(a.name!==b.name?a.name<b.name?-1:1:0)}
function Zb(a){return"number"===typeof a?"number:"+Xb(a):"string:"+a};function S(a,b){this.u=a;this.Qb=b}S.prototype.$=function(){B("Firebase.DataSnapshot.val",0,0,arguments.length);return this.u.$()};S.prototype.val=S.prototype.$;S.prototype.jd=function(){B("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.u.$(k)};S.prototype.exportVal=S.prototype.jd;S.prototype.B=function(a){B("Firebase.DataSnapshot.child",0,1,arguments.length);fa(a)&&(a=String(a));Ga("Firebase.DataSnapshot.child",a);var b=new J(a),c=this.Qb.B(b);return new S(this.u.D(b),c)};
S.prototype.child=S.prototype.B;S.prototype.jc=function(a){B("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Ga("Firebase.DataSnapshot.hasChild",a);var b=new J(a);return!this.u.D(b).f()};S.prototype.hasChild=S.prototype.jc;S.prototype.m=function(){B("Firebase.DataSnapshot.getPriority",0,0,arguments.length);return this.u.m()};S.prototype.getPriority=S.prototype.m;
S.prototype.forEach=function(a){B("Firebase.DataSnapshot.forEach",1,1,arguments.length);D("Firebase.DataSnapshot.forEach",1,a,n);if(this.u.J())return n;var b=this;return this.u.A(function(c,d){return a(new S(d,b.Qb.B(c)))})};S.prototype.forEach=S.prototype.forEach;S.prototype.zb=function(){B("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.u.J()?n:!this.u.f()};S.prototype.hasChildren=S.prototype.zb;
S.prototype.name=function(){B("Firebase.DataSnapshot.name",0,0,arguments.length);return this.Qb.name()};S.prototype.name=S.prototype.name;S.prototype.Db=function(){B("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.u.Db()};S.prototype.numChildren=S.prototype.Db;S.prototype.ud=function(){B("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.Qb};S.prototype.ref=S.prototype.ud;function dc(a){this.pc=a;this.Lb=[];this.La=0;this.fc=-1;this.Da=m};function T(a,b){for(var c in a)b.call(i,a[c],c,a)}function ec(a){var b={},c;for(c in a)b[c]=a[c];return b};function fc(){this.Xa={}}function gc(a,b,c){t(c)||(c=1);E(a.Xa,b)||(a.Xa[b]=0);a.Xa[b]+=c}fc.prototype.get=function(){return ec(this.Xa)};function hc(a){this.fd=a;this.Ab=m}hc.prototype.get=function(){var a=this.fd.get(),b=ec(a);if(this.Ab)for(var c in this.Ab)b[c]-=this.Ab[c];this.Ab=a;return b};function ic(a,b){this.uc={};this.Xb=new hc(a);this.o=b;setTimeout(y(this.Rc,this),10+6E4*Math.random())}ic.prototype.Rc=function(){var a=this.Xb.get(),b={},c=n,d;for(d in a)0<a[d]&&E(this.uc,d)&&(b[d]=a[d],c=k);c&&(a=this.o,a.aa&&(b={c:b},a.e("reportStats",b),a.wa("s",b)));setTimeout(y(this.Rc,this),6E5*Math.random())};var jc={},kc={};function lc(a){a=a.toString();jc[a]||(jc[a]=new fc);return jc[a]};var mc=m;"undefined"!==typeof MozWebSocket?mc=MozWebSocket:"undefined"!==typeof WebSocket&&(mc=WebSocket);function nc(a,b,c){this.gc=a;this.e=Pb(this.gc);this.frames=this.bb=m;this.vc=0;this.T=lc(b);this.Ka=(b.Tb?"wss://":"ws://")+b.ba+"/.ws?v=5";b.host!==b.ba&&(this.Ka=this.Ka+"&ns="+b.gb);c&&(this.Ka=this.Ka+"&s="+c)}var oc;
nc.prototype.open=function(a,b){this.S=b;this.Hb=a;this.e("websocket connecting to "+this.Ka);this.R=new mc(this.Ka);this.Ya=n;var c=this;this.R.onopen=function(){c.e("Websocket connected.");c.Ya=k};this.R.onclose=function(){c.e("Websocket connection was disconnected.");c.R=m;c.Ea()};this.R.onmessage=function(a){if(c.R!==m)if(a=a.data,gc(c.T,"bytes_received",a.length),c.frames!==m)pc(c,a);else{a:{A(c.frames===m,"We already have a frame buffer");if(4>=a.length){var b=Number(a);if(!isNaN(b)){c.vc=b;
c.frames=[];a=m;break a}}c.vc=1;c.frames=[]}a!==m&&pc(c,a)}};this.R.onerror=function(){c.e("WebSocket error.  Closing connection.");c.Ea()}};nc.prototype.start=p();nc.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&mc!==m&&!oc};function pc(a,b){a.frames.push(b);if(a.frames.length==a.vc){var c=a.frames.join("");a.frames=m;c="undefined"!==typeof JSON&&t(JSON.parse)?JSON.parse(c):la(c);qc(a);a.Hb(c)}}
nc.prototype.send=function(a){qc(this);a=z(a);gc(this.T,"bytes_sent",a.length);a=Wb(a,16384);1<a.length&&this.R.send(String(a.length));for(var b=0;b<a.length;b++)this.R.send(a[b])};nc.prototype.sb=function(){this.Ba=k;this.bb&&(clearTimeout(this.bb),this.bb=m);this.R&&(this.R.close(),this.R=m)};nc.prototype.Ea=function(){this.Ba||(this.e("WebSocket is closing itself"),this.sb(),this.S&&(this.S(this.Ya),this.S=m))};nc.prototype.close=function(){this.Ba||(this.e("WebSocket is being closed"),this.sb())};
function qc(a){clearTimeout(a.bb);a.bb=setInterval(function(){a.R.send("0");qc(a)},45E3)};function rc(){this.set={}}s=rc.prototype;s.add=function(a,b){this.set[a]=b!==m?b:k};s.contains=function(a){return E(this.set,a)};s.get=function(a){return this.set[a]};s.remove=function(a){delete this.set[a]};s.f=function(){var a;a:{for(a in this.set){a=n;break a}a=k}return a};s.count=function(){var a=0,b;for(b in this.set)a++;return a};s.keys=function(){var a=[],b;for(b in this.set)E(this.set,b)&&a.push(b);return a};var sc="pLPCommand",tc="pRTLPCB";function uc(a,b,c){this.gc=a;this.e=Pb(a);this.Dd=b;this.T=lc(b);this.Ub=c;this.Ya=n;this.vb=function(a){b.host!==b.ba&&(a.ns=b.gb);var c=[],f;for(f in a)a.hasOwnProperty(f)&&c.push(f+"="+a[f]);return(b.Tb?"https://":"http://")+b.ba+"/.lp?"+c.join("&")}}var vc;
uc.prototype.open=function(a,b){function c(){if(!d.Ba){d.da=new wc(function(a,b,c,e,f){gc(d.T,"bytes_received",z(arguments).length);if(d.da)if(d.za&&(clearTimeout(d.za),d.za=m),d.Ya=k,"start"==a)d.id=b,d.Qc=c;else if("close"===a)if(b){d.da.Wc=n;var h=d.Lc;h.fc=b;h.Da=function(){d.Ea()};h.fc<h.La&&(h.Da(),h.Da=m)}else d.Ea();else g(Error("Unrecognized command received: "+a))},function(a,b){gc(d.T,"bytes_received",z(arguments).length);var c=d.Lc;for(c.Lb[a]=b;c.Lb[c.La];){var e=c.Lb[c.La];delete c.Lb[c.La];
for(var f=0;f<e.length;++f)e[f]&&c.pc(e[f]);if(c.La===c.fc){c.Da&&(clearTimeout(c.Da),c.Da(),c.Da=m);break}c.La++}},function(){d.Ea()},d.vb);var a={start:"t"};a.ser=Math.floor(1E8*Math.random());d.da.$b&&(a.cb=d.da.$b);a.v="5";d.Ub&&(a.s=d.Ub);a=d.vb(a);d.e("Connecting via long-poll to "+a);xc(d.da,a,p())}}this.Ac=0;this.W=b;this.Lc=new dc(a);this.Ba=n;var d=this;this.za=setTimeout(function(){d.e("Timed out trying to connect.");d.Ea();d.za=m},3E4);if("complete"===document.readyState)c();else{var e=
n,f=function(){document.body?e||(e=k,c()):setTimeout(f,10)};document.addEventListener?(document.addEventListener("DOMContentLoaded",f,n),window.addEventListener("load",f,n)):document.attachEvent&&(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&f()},n),window.attachEvent("onload",f,n))}};
uc.prototype.start=function(){var a=this.da,b=this.Qc;a.pd=this.id;a.qd=b;for(a.cc=k;yc(a););a=this.id;b=this.Qc;this.Qa=document.createElement("iframe");var c={dframe:"t"};c.id=a;c.pw=b;a=this.vb(c);this.Qa.src=a;this.Qa.style.display="none";document.body.appendChild(this.Qa)};uc.isAvailable=function(){return vc||k};uc.prototype.sb=function(){this.Ba=k;this.da&&(this.da.close(),this.da=m);this.Qa&&(document.body.removeChild(this.Qa),this.Qa=m);this.za&&(clearTimeout(this.za),this.za=m)};
uc.prototype.Ea=function(){this.Ba||(this.e("Longpoll is closing itself"),this.sb(),this.W&&(this.W(this.Ya),this.W=m))};uc.prototype.close=function(){this.Ba||(this.e("Longpoll is being closed."),this.sb())};uc.prototype.send=function(a){a=z(a);gc(this.T,"bytes_sent",a.length);for(var a=ra(a),a=Gb(a,k),a=Wb(a,1840),b=0;b<a.length;b++){var c=this.da;c.mb.push({yd:this.Ac,Cd:a.length,Bc:a[b]});c.cc&&yc(c);this.Ac++}};
function wc(a,b,c,d){this.vb=d;this.S=c;this.qc=new rc;this.mb=[];this.hc=Math.floor(1E8*Math.random());this.Wc=k;this.$b=Hb();window[sc+this.$b]=a;window[tc+this.$b]=b;a=document.createElement("iframe");a.style.display="none";document.body?document.body.appendChild(a):g("Document body has not initialized. Wait to initialize Firebase until after the document is ready.");a.contentDocument?a.qa=a.contentDocument:a.contentWindow?a.qa=a.contentWindow.document:a.document&&(a.qa=a.document);this.ia=a;try{this.ia.qa.open(),
this.ia.qa.write("<html><body></body></html>"),this.ia.qa.close()}catch(e){Nb("frame writing exception"),e.stack&&Nb(e.stack),Nb(e)}}wc.prototype.close=function(){this.cc=n;this.ia&&(this.ia.qa.body.innerHTML="",document.body.removeChild(this.ia),this.ia=m);var a=this.S;a&&(this.S=m,a())};
function yc(a){if(a.cc&&a.Wc&&a.qc.count()<(0<a.mb.length?2:1)){a.hc++;var b={};b.id=a.pd;b.pw=a.qd;b.ser=a.hc;for(var b=a.vb(b),c="",d=0;0<a.mb.length;)if(1870>=a.mb[0].Bc.length+30+c.length){var e=a.mb.shift(),c=c+"&seg"+d+"="+e.yd+"&ts"+d+"="+e.Cd+"&d"+d+"="+e.Bc;d++}else break;var b=b+c,f=a.hc;a.qc.add(f);var h=function(){a.qc.remove(f);yc(a)},j=setTimeout(h,25E3);xc(a,b,function(){clearTimeout(j);h()});return k}return n}
function xc(a,b,c){setTimeout(function(){try{var d=a.ia.qa.createElement("script");d.type="text/javascript";d.async=k;d.src=b;d.onload=d.onreadystatechange=function(){var a=d.readyState;if(!a||"loaded"===a||"complete"===a)d.onload=d.onreadystatechange=m,d.parentNode&&d.parentNode.removeChild(d),c()};d.onerror=function(){Nb("Long-poll script failed to load.");a.close()};a.ia.qa.body.appendChild(d)}catch(e){}},1)};function zc(){function a(a,c){c&&c.isAvailable()&&b.push(c)}var b=[],c=Ac;if("array"==da(c))for(var d=0;d<c.length;++d)a(0,c[d]);else T(c,a);this.Zb=b}var Ac=[uc,{isAvailable:r(n)},nc];function U(a,b,c,d,e,f){this.id=a;this.e=Pb("c:"+this.id+":");this.pc=c;this.hb=d;this.W=e;this.oc=f;this.L=b;this.Kb=[];this.zc=0;this.xc=new zc;this.ma=0;this.e("Connection created");Bc(this)}function Bc(a){var b;var c=a.xc;0<c.Zb.length?b=c.Zb[0]:g(Error("No transports available"));a.I=new b("c:"+a.id+":"+a.zc++,a.L);b=Cc(a,a.I);c=Dc(a,a.I);a.tb=a.I;a.qb=a.I;a.I.open(b,c);a.w=m}
function Dc(a,b){return function(c){b===a.I?(a.I=m,!c&&0===a.ma?(a.e("Realtime connection failed."),"s-"===a.L.ba.substr(0,2)&&(O.removeItem(a.L.gb),a.L.ba=a.L.host)):1===a.ma&&a.e("Realtime connection lost."),a.close()):b===a.w?(c=a.w,a.w=m,(a.tb===c||a.qb===c)&&a.close()):a.e("closing an old connection")}}
function Cc(a,b){return function(c){if(2!=a.ma)if(b===a.qb){var d=Ub("t",c),c=Ub("d",c);if("c"==d){if(d=Ub("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,f=c.h;a.Ub=c.s;rb(a.L,f);if(0==a.ma&&(a.I.start(),c=a.I,a.e("Realtime connection established."),a.I=c,a.ma=1,a.hb&&(a.hb(d),a.hb=m),"5"!==e&&P("Protocol version mismatch detected"),c=1<a.xc.Zb.length?a.xc.Zb[1]:m))a.w=new c("c:"+a.id+":"+a.zc++,a.L,a.Ub),a.w.open(Cc(a,a.w),Dc(a,a.w))}else if("n"===d){a.e("recvd end transmission on primary");a.qb=
a.w;for(c=0;c<a.Kb.length;++c)a.Fb(a.Kb[c]);a.Kb=[];Ec(a)}else"s"===d?(a.e("Connection shutdown command received. Shutting down..."),a.oc&&(a.oc(c),a.oc=m),a.W=m,a.close()):"r"===d?(a.e("Reset packet received.  New host: "+c),rb(a.L,c),1===a.ma?a.close():(Fc(a),Bc(a))):Qb("Unknown control packet command: "+d)}else"d"==d&&a.Fb(c)}else b===a.w?(d=Ub("t",c),c=Ub("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.w.start(),a.e("sending client ack on secondary"),a.w.send({t:"c",d:{t:"a",d:{}}}),a.e("Ending transmission on primary"),
a.I.send({t:"c",d:{t:"n",d:{}}}),a.tb=a.w,Ec(a)):"r"===c&&(a.e("Got a reset on secondary, closing it"),a.w.close(),(a.tb===a.w||a.qb===a.w)&&a.close())):"d"==d?a.Kb.push(c):g(Error("Unknown protocol layer: "+d))):a.e("message on old connection")}}U.prototype.sc=function(a){a={t:"d",d:a};1!==this.ma&&g("Connection is not connected");this.tb.send(a)};function Ec(a){a.tb===a.w&&a.qb===a.w&&(a.e("cleaning up and promoting a connection: "+a.w.gc),a.I=a.w,a.w=m)}U.prototype.Fb=function(a){this.pc(a)};
U.prototype.close=function(){2!==this.ma&&(this.e("Closing realtime connection."),this.ma=2,Fc(this),this.W&&(this.W(),this.W=m))};function Fc(a){a.e("Shutting down all connections");a.I&&(a.I.close(),a.I=m);a.w&&(a.w.close(),a.w=m)};function Gc(a,b,c,d){this.id=Hc++;this.e=Pb("p:"+this.id+":");this.Ua=k;this.ca={};this.N=[];this.ib=0;this.nc={};this.aa=n;this.Pb=1E3;this.Gb=b;this.Nc=c;this.W=d;this.L=a;this.rc=m;this.Mb=[];this.va={};this.xd=0;this.eb=this.Kc=m;setTimeout(y(this.Cc,this),0)}var Hc=0,Ic=0;s=Gc.prototype;
s.wa=function(a,b,c,d){var e=++this.xd,a={r:e,a:a,b:b};this.e(z(a));this.aa?this.ob.sc(a):this.Mb.push(a);var f=this,a=setTimeout(function(){var a=f.va[e];a&&(delete f.va[e],a.ga&&a.ga.Ib&&a.ga.Ib())},45E3);this.va[e]={ga:{Hb:c,Ib:d},Zc:a}};function Jc(a,b,c,d,e){a.e("Listen on "+b+" for "+c);var f={p:b},d=kb(d,function(a){return Ja(a)});"{}"!==c&&(f.q=d);a.wa("l",f,function(d){a.e("listen response",d);d=d.s;"ok"!==d&&Kc(a,b,c);e&&e(d)},function(){a.e("timed out on listen...")})}
s.Wa=function(a,b){this.xb={gd:a,Ec:n,ea:b};this.e("Authenticating using credential: "+this.xb);Lc(this)};s.ub=function(){delete this.xb;this.aa&&this.wa("unauth",{},p(),p())};function Lc(a){var b=a.xb;a.aa&&b&&a.wa("auth",{cred:b.gd},function(c){c=c.s;"ok"!==c&&delete a.xb;b.Ec||(b.Ec=k,b.ea&&b.ea(c))},function(){a.e("timed out on auth...")})}
s.ad=function(a,b,c){a=a.toString();if(Kc(this,a,b)&&this.aa){this.e("Unlisten on "+a+" for "+b);var d=this,a={p:a},c=kb(c,function(a){return Ja(a)});"{}"!==b&&(a.q=c);this.wa("u",a,m,function(){d.e("timed out on unlisten...")})}};s.S=function(a,b){this.nc[a]=b;this.aa&&Mc(this,a,b)};function Mc(a,b,c){b={p:b,d:c};a.e("onDisconnect",b);a.wa("o",b,function(a){"ok"!==a.s&&g("onDisconnect failed: "+z(a.d))},function(){a.e("timed out on onDisconnect...")})}s.put=function(a,b,c,d){Nc(this,"p",a,b,c,d)};
function Nc(a,b,c,d,e,f){c={p:c,d:d};t(f)&&(c.h=f);a.N.push({action:b,Sc:c,F:e});a.ib++;b=a.N.length-1;a.aa&&Oc(a,b)}function Oc(a,b){var c=a.N[b].action,d=a.N[b].F;a.wa(c,a.N[b].Sc,function(e){a.e(c+" response",e);delete a.N[b];a.ib--;0===a.ib&&(a.N=[]);d&&d(e.s)},function(){a.e("timed out on put...")})}
s.Fb=function(a){if("r"in a){this.e("from server: "+z(a));var b=a.r,c=this.va[b];c&&(delete this.va[b],clearTimeout(c.Zc),c.ga&&c.ga.Hb&&c.ga.Hb(a.b))}else"error"in a&&g("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,c=a.b,this.e("handleServerMessage",b,c),"d"===b?this.Gb(c.p,c.d):"m"===b?this.Gb(c.p,c.d,k):"c"===b?(a=c.p,b=(b=c.q)?kb(b,function(a){return Ka(a)}).join("$"):"{}",(a=Kc(this,a,b))&&a.F&&a.F("permission_denied")):"sd"===b?this.rc?this.rc(c):"msg"in c&&"undefined"!==typeof console&&
console.log("FIREBASE: "+c.msg.replace("\n","\nFIREBASE: ")):Qb("Unrecognized action received from server: "+z(b)+"\nAre you using the latest client?"))};
s.hb=function(a){this.e("connection ready");this.aa=k;this.eb=(new Date).getTime();Vb=a-(new Date).getTime();for(a=0;a<this.Mb.length;a++)this.ob.sc(this.Mb[a]);this.Mb=[];Lc(this);for(var b in this.ca)for(var c in this.ca[b])a=this.ca[b][c],Jc(this,b,c,a.Sa,a.F);for(b in this.nc)Mc(this,b,this.nc[b]);for(b=0;b<this.N.length;b++)this.N[b]&&Oc(this,b);this.Nc&&this.Nc()};
s.Oc=function(){this.aa=n;this.e("data client disconnected");if(!this.Ua){for(var a=0;a<this.N.length;a++){var b=this.N[a];b&&"h"in b.Sc&&(b.F&&b.F("disconnect"),delete this.N[a],this.ib--)}0===this.ib&&(this.N=[]);for(var c in this.va)a=this.va[c],delete this.va[c],a!==m&&(a.ga&&a.ga.Ib&&a.ga.Ib(),clearTimeout(a.Zc))}var d=y(function(){this.Cc()},this);this.Ua?(this.eb&&(3E4<(new Date).getTime()-this.eb&&(this.Pb=1E3),this.eb=m),c=Math.max(0,this.Pb-((new Date).getTime()-this.Kc)),c*=Math.random(),
this.e("Trying to reconnect in "+c+"ms"),setTimeout(d,c),this.Pb=Math.min(3E4,1.3*this.Pb)):this.Uc=function(){setTimeout(d,0)};this.W&&this.W()};s.Cc=function(){if(this.Ua){this.e("Making a connection attempt");this.Kc=(new Date).getTime();this.eb=m;var a=y(this.Fb,this),b=y(this.hb,this),c=y(this.Oc,this),d=this.id+":"+Ic++,e=this;this.ob=new U(d,this.L,a,b,c,function(a){e.Ua=n;g(Error(a))})}};s.Oa=function(){this.Ua=n;this.ob?this.ob.close():this.Oc()};
s.pb=function(){this.Ua=k;this.Uc();this.Uc=i};function Kc(a,b,c){b=(new J(b)).toString();c||(c="{}");var d=a.ca[b][c];delete a.ca[b][c];return d};function Pc(){this.Ha=Q}function V(a,b){return a.Ha.D(b)}function W(a,b,c){a.Ha=a.Ha.Va(b,c)}Pc.prototype.toString=function(){return this.Ha.toString()};function Qc(){this.xa=new Pc;this.K=new Pc;this.ya=new Pc;this.lb=new Ra}function Rc(a,b){for(var c=V(a.xa,b),d=V(a.K,b),e=L(a.lb,b),f=n,h=e;h!==m;){if(h.j()!==m){f=k;break}h=h.parent()}if(f)return n;c=Sc(c,d,e);return c!==d?(W(a.K,b,c),k):n}function Sc(a,b,c){if(c.f())return a;if(c.j()!==m)return b;a=a||Q;c.A(function(d){var d=d.name(),e=a.M(d),f=b.M(d),h=L(c,d),e=Sc(e,f,h);a=a.C(d,e)});return a}
Qc.prototype.set=function(a,b){var c=this,d=[];jb(b,function(a){var b=a.path,a=a.Ca,h=Hb();M(L(c.lb,b),h);W(c.K,b,a);d.push({path:b,zd:h})});return d};function Tc(a,b){jb(b,function(b){var d=b.zd,b=L(a.lb,b.path),e=b.j();A(e!==m,"pendingPut should not be null.");e===d&&M(b,m)})};function Uc(){this.Aa=[]}function Vc(a,b){if(0!==b.length){a.Aa.push.apply(a.Aa,b);for(var c=0;c<a.Aa.length;c++)if(a.Aa[c]){var d=a.Aa[c];a.Aa[c]=m;var e=d.ea;e(d.Xc,d.nb)}a.Aa=[]}};function X(a,b,c,d){this.type=a;this.ja=b;this.U=c;this.nb=d};function Wc(a){this.H=a;this.fa=[];this.Dc=new Uc}function Xc(a,b,c,d,e){a.fa.push({type:b,ea:c,cancel:d,V:e});var d=[],f=Yc(a.g);a.ab&&f.push(new X("value",a.g));for(var h=0;h<f.length;h++)if(f[h].type===b){var j=new Y(a.H.k,a.H.path);f[h].U&&(j=j.B(f[h].U));d.push({ea:e?y(c,e):c,Xc:new S(f[h].ja,j),nb:f[h].nb})}Vc(a.Dc,d)}Wc.prototype.Nb=function(a,b){b=this.Ob(a,b);b!=m&&Zc(this,b)};
function Zc(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],f=e.type,h=new Y(a.H.k,a.H.path);b[d].U&&(h=h.B(b[d].U));h=new S(b[d].ja,h);"value"===e.type&&!h.zb()?f+="("+h.$()+")":"value"!==e.type&&(f+=" "+h.name());Nb(a.H.k.o.id+": event:"+a.H.path+":"+a.H.Fa()+":"+f);for(f=0;f<a.fa.length;f++){var j=a.fa[f];b[d].type===j.type&&c.push({ea:j.V?y(j.ea,j.V):j.ea,Xc:h,nb:e.nb})}}Vc(a.Dc,c)}
function Yc(a){var b=[];if(!a.J()){var c=m;a.A(function(a,e){b.push(new X("child_added",e,a,c));c=a})}return b}function $c(a){a.ab||(a.ab=k,Zc(a,[new X("value",a.g)]))};function ad(a,b){Wc.call(this,a);this.g=b}ka(ad,Wc);ad.prototype.Ob=function(a,b){this.g=a;this.ab&&b!=m&&b.push(new X("value",this.g));return b};ad.prototype.Za=function(){return{}};function bd(a,b){this.yb=a;this.mc=b}
function cd(a,b,c,d,e){var f=a.D(c),h=b.D(c),d=new bd(d,e),e=fd(d,c,f,h),j=n;if(!f.f()&&!h.f()&&f.m()!==h.m())var j=a.D(c.parent()),l=b.D(c.parent()),o=Ma(c),j=j.Q(o,f)!=l.Q(o,h);if(e||j){f=c;c=e;for(h=j;f.parent()!==m;){var q=a.D(f),e=b.D(f),j=f.parent();if(!d.yb||L(d.yb,j).j())l=b.D(j),o=[],f=Ma(f),q.f()?(q=l.Q(f,e),o.push(new X("child_added",e,f,q))):e.f()?o.push(new X("child_removed",q,f)):(q=l.Q(f,e),h&&o.push(new X("child_moved",e,f,q)),c&&o.push(new X("child_changed",e,f,q))),d.mc(j,l,o);h&&
(h=n,c=k);f=j}}}function fd(a,b,c,d){var e,f=[];c===d?e=n:c.J()&&d.J()?e=c.j()!==d.j():c.J()?(gd(a,b,Q,d,f),e=k):d.J()?(gd(a,b,c,Q,f),e=k):e=gd(a,b,c,d,f);e?a.mc(b,d,f):c.m()!==d.m()&&a.mc(b,d,m);return e}
function gd(a,b,c,d,e){var f=n,h=!a.yb||!L(a.yb,b).f(),j=[],l=[],o=[],q=[],x={},u={},w,K,I,G;w=c.Na();I=Za(w);K=d.Na();for(G=Za(K);I!==m||G!==m;){c=I===m?1:G===m?-1:I.key===G.key?0:bc({name:I.key,ua:I.value.m()},{name:G.key,ua:G.value.m()});if(0>c)f=ua(x,I.key),t(f)?(o.push({Fc:I,$c:j[f]}),j[f]=m):(u[I.key]=l.length,l.push(I)),f=k,I=Za(w);else{if(0<c)f=ua(u,G.key),t(f)?(o.push({Fc:l[f],$c:G}),l[f]=m):(x[G.key]=j.length,j.push(G)),f=k;else{c=b.B(G.key);if(c=fd(a,c,I.value,G.value))q.push(G),f=k;I=
Za(w)}G=Za(K)}if(!h&&f)return k}for(h=0;h<l.length;h++)if(x=l[h])c=b.B(x.key),fd(a,c,x.value,Q),e.push(new X("child_removed",x.value,x.key));for(h=0;h<j.length;h++)if(x=j[h])c=b.B(x.key),l=d.Q(x.key,x.value),fd(a,c,Q,x.value),e.push(new X("child_added",x.value,x.key,l));for(h=0;h<o.length;h++)x=o[h].Fc,j=o[h].$c,c=b.B(j.key),l=d.Q(j.key,j.value),e.push(new X("child_moved",j.value,j.key,l)),(c=fd(a,c,x.value,j.value))&&q.push(j);for(h=0;h<q.length;h++)a=q[h],l=d.Q(a.key,a.value),e.push(new X("child_changed",
a.value,a.key,l));return f};function hd(){this.kb=this.na=m;this.set={}}ka(hd,rc);s=hd.prototype;s.setActive=function(a){this.na=a};function id(a){return a.contains("default")}function jd(a){return a.na!=m&&id(a)}s.defaultView=function(){return id(this)?this.get("default"):m};s.path=aa("kb");s.toString=function(){return kb(this.keys(),function(a){return"default"===a?"{}":a}).join("$")};s.Sa=function(){var a=[];T(this.set,function(b){a.push(b.H)});return a};function kd(a,b){Wc.call(this,a);this.g=Q;this.Ob(b,Yc(b))}ka(kd,Wc);
kd.prototype.Ob=function(a,b){if(b===m)return b;var c=[],d=this.H;t(d.Z)&&(t(d.la)&&d.la!=m?c.push(function(a,b){var c=Sb(b,d.Z);return 0<c||0===c&&a>=d.la}):c.push(function(a,b){return 0<=Sb(b,d.Z)}));t(d.ra)&&(t(d.Ma)?c.push(function(a,b){var c=Sb(b,d.ra);return 0>c||0===c&&a<=d.Ma}):c.push(function(a,b){return 0>=Sb(b,d.ra)}));var e=m,f=m;if(t(this.H.ta))if(t(this.H.Z)){if(e=ld(a,c,this.H.ta,n)){var h=a.M(e).m();c.push(function(a,b){var c=Sb(b,h);return 0>c||0===c&&a<=e})}}else if(f=ld(a,c,this.H.ta,
k)){var j=a.M(f).m();c.push(function(a,b){var c=Sb(b,j);return 0<c||0===c&&a>=f})}for(var l=[],o=[],q=[],x=[],u=0;u<b.length;u++){var w=b[u].U,K=b[u].ja;switch(b[u].type){case "child_added":md(c,w,K)&&(this.g=this.g.C(w,K),o.push(b[u]));break;case "child_removed":this.g.M(w).f()||(this.g=this.g.C(w,m),l.push(b[u]));break;case "child_changed":!this.g.M(w).f()&&md(c,w,K)&&(this.g=this.g.C(w,K),x.push(b[u]));break;case "child_moved":var I=!this.g.M(w).f(),G=md(c,w,K);I?G?(this.g=this.g.C(w,K),q.push(b[u])):
(l.push(new X("child_removed",this.g.M(w),w)),this.g=this.g.C(w,m)):G&&(this.g=this.g.C(w,K),o.push(b[u]))}}var dd=e||f;if(dd){var ed=(u=f!==m)?this.g.Gc():this.g.Hc(),Tb=n,Oa=n,Pa=this;(u?a.ic:a.A).call(a,function(a,b){!Oa&&ed===m&&(Oa=k);if(Oa&&Tb)return k;Tb?(l.push(new X("child_removed",Pa.g.M(a),a)),Pa.g=Pa.g.C(a,m)):Oa&&(o.push(new X("child_added",b,a)),Pa.g=Pa.g.C(a,b));ed===a&&(Oa=k);a===dd&&(Tb=k)})}for(u=0;u<o.length;u++)c=o[u],w=this.g.Q(c.U,c.ja),l.push(new X("child_added",c.ja,c.U,w));
for(u=0;u<q.length;u++)c=q[u],w=this.g.Q(c.U,c.ja),l.push(new X("child_moved",c.ja,c.U,w));for(u=0;u<x.length;u++)c=x[u],w=this.g.Q(c.U,c.ja),l.push(new X("child_changed",c.ja,c.U,w));this.ab&&0<l.length&&l.push(new X("value",this.g));return l};function ld(a,b,c,d){if(a.J())return m;var e=m;(d?a.ic:a.A).call(a,function(a,d){if(md(b,a,d)&&(e=a,c--,0===c))return k});return e}function md(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.m()))return n;return k}
kd.prototype.jc=function(a){return this.g.M(a)!==Q};kd.prototype.Za=function(a,b,c){var d={};this.g.J()||this.g.A(function(a){d[a]=k});var e=this.g,c=V(c,new J("")),f=new Ra;M(L(f,this.H.path),k);var h=Q.Va(a,b),j=[];cd(c,h,a,f,function(a,b,c){c!==m&&(j=j.concat(c))});this.Ob(b,j);this.g.J()||this.g.A(function(a){d[a]=k});this.g=e;return d};function nd(a,b){this.o=a;this.i=b;this.Mc=b.Ha;this.pa=new Ra}
nd.prototype.wb=function(a,b,c,d,e){var f=a.path,h=L(this.pa,f),j=h.j();j===m?(j=new hd,M(h,j)):A(!j.f(),"We shouldn't be storing empty QueryMaps");var l=a.Fa();if(j.contains(l))Xc(j.get(l),b,c,d,e);else{var o=this.i.Ha.D(f),a="default"===a.Fa()?new ad(a,o):new kd(a,o);if(jd(j)||od(h))j.add(l,a),j.kb||(j.kb=a.H.path);else{var q,x;j.f()||(q=j.toString(),x=j.Sa());j.add(l,a);j.kb||(j.kb=a.H.path);j.setActive(pd(this,j));q&&x&&this.o.ad(j.path(),q,x)}jd(j)&&Ta(h,function(a){if(a=a.j()){a.na&&a.na();
a.na=m}});Xc(a,b,c,d,e);(b=(b=Ua(L(this.pa,f),function(a){var b;if(b=a.j())if(b=a.j().defaultView())b=a.j().defaultView().ab;if(b)return k},k))||this.o===m)&&$c(a)}};function qd(a,b,c,d,e){for(var f=a.get(b),h=n,j=f.fa.length-1;0<=j;j--){var l=f.fa[j];if((!c||l.type===c)&&(!d||l.ea===d)&&(!e||l.V===e))if(f.fa.splice(j,1),h=k,c&&d)break}(c=h&&!(0<f.fa.length))&&a.remove(b);return c}nd.prototype.Rb=function(a,b,c,d){var e=L(this.pa,a.path).j();return e===m?m:rd(this,e,a,b,c,d)};
function rd(a,b,c,d,e,f){var h=b.path(),h=L(a.pa,h),c=c?c.Fa():m,j=[];c&&"default"!==c?qd(b,c,d,e,f)&&j.push(c):jb(b.keys(),function(a){qd(b,a,d,e,f)&&j.push(a)});b.f()&&M(h,m);c=od(h);if(0<j.length&&!c){for(var l=h,o=h.parent(),c=n;!c&&o;){var q=o.j();if(q){A(!jd(q));var x=l.name(),u=n;T(q.set,function(a){u=a.jc(x)||u});u&&(c=k)}l=o;o=o.parent()}l=m;if(!jd(b)){o=b.na;b.na=m;var w=[],K=function(b){var c=b.j();c&&id(c)?(w.push(c.path()),c.na==m&&c.setActive(pd(a,c))):(c&&c.na==m&&c.setActive(pd(a,
c)),b.A(K))};K(h);l=w;o&&o()}return c?m:l}return m}function sd(a,b,c){Ta(L(a.pa,b),function(a){(a=a.j())&&T(a.set,function(a){$c(a)})},c,k)}function td(a,b,c){function d(a){for(var b=0;b<c.length;++b)if(c[b].contains(a))return k;return n}var e=a.Mc,f=a.i.Ha;a.Mc=f;var h=b.toString();cd(e,f,b,a.pa,function(b,c,e){if(b.toString().substring(0,h.length)===h){var f=d(b);f&&sd(a,b,n);a.Nb(b,c,e);f&&sd(a,b,k)}else a.Nb(b,c,e)});d(b)&&sd(a,b,k)}
nd.prototype.Nb=function(a,b,c){a=L(this.pa,a).j();a!==m&&T(a.set,function(a){a.Nb(b,c)})};function od(a){return Ua(a,function(a){return a.j()&&jd(a.j())})}
function pd(a,b){if(a.o){var c=b.keys(),d=a.o,e=function(d){"ok"!==d?(P("on() or once() for "+b.path().toString()+" failed: "+d),b&&T(b.set,function(a){for(var b=0;b<a.fa.length;b++){var c=a.fa[b];c.cancel&&(c.V?y(c.cancel,c.V):c.cancel)()}}),rd(a,b)):jb(c,function(a){(a=b.get(a))&&$c(a)})},f=b.toString(),h=b.path().toString();d.ca[h]=d.ca[h]||{};A(!d.ca[h][f],"listen() called twice for same path/queryId.");d.ca[h][f]={Sa:b.Sa(),F:e};d.aa&&Jc(d,h,f,b.Sa(),e);return y(a.o.ad,a.o,b.path(),b.toString(),
b.Sa())}return ca}nd.prototype.Za=function(a,b,c,d){var e={};T(b.set,function(b){b=b.Za(a,c,d);T(b,function(a,b){e[b]=E(e,b)?e:a})});c.J()||c.A(function(a){E(e,a)||(e[a]=n)});return e};
function ud(a,b,c,d,e,f){var h=b.path();if(f!==m){var j=[];d.J()||d.A(function(a,b){j.push({path:h.B(a),Ca:b});delete f[a]});T(f,function(a,b){j.push({path:h.B(b),Ca:Q})});return j}var b=a.Za(h,b,d,e),l=Q,o=[];T(b,function(b,f){var h=new J(f);b?l=l.C(f,d.D(h)):o=o.concat(vd(a,d.D(h),L(c,h),e))});return[{path:h,Ca:l}].concat(o)}
function wd(a,b,c,d,e){for(var f=L(a.pa,b),h=f.parent(),j=n;!j&&h!==m;){var l=h.j();l!==m&&(id(l)?j=k:(l=a.Za(b,l,c,d),f=f.name(),ua(l,f)&&(j=k)));f=h;h=h.parent()}if(j)return[{path:b,Ca:c}];h=L(a.pa,b);j=h.j();return j!==m?id(j)?[{path:b,Ca:c}]:ud(a,j,h,c,d,e):vd(a,c,h,d)}function vd(a,b,c,d){var e=c.j();if(e!==m)return id(e)?[{path:c.path(),Ca:b}]:ud(a,e,c,b,d,m);if(b.J())return[];var f=[];b.A(function(b,e){var l=new J(b);f=f.concat(vd(a,e,L(c,l),d))});return f};function xd(a){this.L=a;this.T=lc(a);this.o=new Gc(this.L,y(this.Gb,this),y(this.rd,this),y(this.sd,this));var b=y(function(){return new ic(this.T,this.o)},this),a=a.toString();kc[a]||(kc[a]=b());this.Yc=kc[a];this.Yb=new Ra;this.i=new Qc;this.O=new nd(this.o,this.i.ya);this.Ic=new Pc;this.kc=new nd(m,this.Ic);yd(this,n)}s=xd.prototype;s.toString=function(){return(this.L.Tb?"https://":"http://")+this.L.host};s.name=function(){return this.L.gb};
s.Gb=function(a,b,c){var d=[],e=m;if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new J(a.substring(0,a.length-9)),c=V(this.i.xa,a).bc(b),d.push(a);else if(c){var e=b,a=new J(a),c=V(this.i.xa,a),f;for(f in b){var h=cc(b[f]),c=c.C(f,h);d.push(a.B(f))}}else a=new J(a),c=cc(b),d.push(a);b=wd(this.O,a,c,this.i.K,e);e=n;for(f=0;f<b.length;++f){var c=b[f],h=this.i,j=c.path;W(h.xa,j,c.Ca);e=Rc(h,j)||e}e&&(a=zd(this,a),Ad(this,a),a=a.path());td(this.O,a,d)};s.rd=function(){yd(this,k)};
s.sd=function(){yd(this,n)};function yd(a,b){var c=new J("/.info/connected");W(a.Ic,c,cc(b));td(a.kc,c,[c])}s.Wa=function(a,b){this.o.Wa(a,function(a){Bd(b,"ok"===a,a)})};s.ub=function(){this.o.ub()};
s.rb=function(a,b,c,d){this.e("set",{path:a.toString(),value:b});var b=cc(b,c),c=wd(this.O,a,b,this.i.K,m),e=this.i.set(a,c),f=this;this.o.put(a.toString(),b.$(k),function(b){var c="ok"===b;Tc(f.i,e);if(!c){P("set at "+a+" failed: "+b);Rc(f.i,a);var l=zd(f,a);Ad(f,l);td(f.O,l.path(),[])}Bd(d,c,b)});b=zd(this,a);Cd(this,a);Ad(this,b);td(this.O,b.path(),[a])};
s.update=function(a,b,c){this.e("update",{path:a.toString(),value:b});var d=V(this.i.ya,a),e=k,f=[],h;for(h in b){var e=n,j=cc(b[h]),d=d.C(h,j);f.push(a.B(h))}if(e)Nb("update() called with empty data.  Don't do anything."),Bd(c,k);else{var d=wd(this.O,a,d,this.i.K,b),l=this.i.set(a,d),o=this;Nc(this.o,"m",a.toString(),b,function(b){A("ok"===b||"permission_denied"===b,"merge at "+a+" failed.");var d="ok"===b;Tc(o.i,l);Bd(c,d,b)},i);b=zd(this,a);Cd(this,a);Ad(this,b);td(this.O,b.path(),f)}};
s.Wb=function(a,b,c){this.e("setPriority",{path:a.toString(),ua:b});var d=V(this.i.K,a).bc(b),d=wd(this.O,a,d,this.i.K,m),e=this.i.set(a,d),f=this;this.o.put(a.toString()+"/.priority",b,function(a){var b="ok"===a;Tc(f.i,e);Bd(c,b,a)});a=zd(this,a);Ad(this,a);td(this.O,a.path(),[])};s.Vb=function(a,b){this.o.S(a.toString(),b)};s.wb=function(a,b,c,d,e){".info"===F(a.path)?this.kc.wb(a,b,c,d,e):this.O.wb(a,b,c,d,e)};
s.Rb=function(a,b,c,d){if(".info"===F(a.path))this.kc.Rb(a,b,c,d);else if(b=this.O.Rb(a,b,c,d),b!==m){for(var c=this.i,a=a.path,d=[],e=0;e<b.length;++e)d[e]=V(c.xa,b[e]);W(c.xa,a,Q);for(e=0;e<b.length;++e)W(c.xa,b[e],d[e])}};s.Oa=function(){this.o.Oa()};s.pb=function(){this.o.pb()};
s.tc=function(a){if("undefined"!==typeof console){a?(this.Xb||(this.Xb=new hc(this.T)),a=this.Xb.get()):a=this.T.get();var b=a,c=[],d=0,e;for(e in b)c[d++]=e;var f=function(a,b){return Math.max(b.length,a)};if(c.reduce)e=c.reduce(f,0);else{var h=0;jb(c,function(a){h=f.call(i,h,a)});e=h}for(var j in a){b=a[j];for(c=j.length;c<e+2;c++)j+=" ";console.log(j+b)}}};s.e=function(){Nb("r:"+this.o.id+":",arguments)};function Dd(a,b){var c=new Y(a,b);return new S(V(a.i.ya,b),c)}
function Bd(a,b,c){a&&(1===a.length?a(b):b?a(m):a(Error(c)))}
function Ed(a,b,c){ga(c)&&1===c.length&&(P("\n"+b+' was passed an onComplete callback that takes 1 argument.\nOn 2/4/2013, we are changing our callback signature from:\n    function(success) { /* success is true for success, false for failure. */ }\nto:\n    function(error) { /* error is null for success, an Error object for failure. */ }\n\nTHIS WILL BE A BREAKING CHANGE!  To fix your code, you can either:\n * Remove all parameters from your callback. E.g.:\n     function() { ... }\n * Opt in to the new behavior early by adding a "dummy" second argument. E.g.:\n     function(error, dummy) { ... }\nPlease email support@firebase.com for more info.'),gc(a.T,
"old_callback"),a.Yc.uc.old_callback=k)};function Cd(a,b){var c=L(a.Yb,b);Ua(c,function(b){Fd(a,b)});Fd(a,c);Ta(c,function(b){Fd(a,b)})}function Fd(a,b){var c=b.j();if(c!==m){for(var d=-1,e=[],f=0;f<c.length;f++)if(2===c[f].status)A(d===f-1,"All SENT items should be at beginning of queue."),d=f,c[f].status=4,c[f].yc="set";else if(c[f].ac(),c[f].F){var h=Dd(a,b.path());e.push(Gd(c[f].F,Error("set"),n,h))}-1===d?M(b,m):c.length=d+1;for(f=0;f<e.length;f++)e[f]()}}
function Hd(a,b){var c=b||a.Yb;b||Id(a,c);if(!c.f())if(c.j()!==m){var d=Jd(a,c);if(0!==d.length){var e=c.path();if(2!==d[0].status&&4!==d[0].status){for(var f=0;f<d.length;f++)A(1===d[f].status,"tryToSendTransactionForNode_: items in queue should all be run."),d[f].status=2,d[f].Vc++;var h=V(a.i.K,e).hash();W(a.i.K,e,V(a.i.ya,e));var j=V(a.i.K,e).$(k),l=Hb();M(L(a.i.lb,e),l);a.o.put(e.toString(),j,function(b){a.e("transaction put response",{path:e.toString(),status:b});var h=L(a.i.lb,e),j=h.j();A(j!==
m,"tryToSendTransactionsForNode_: pendingPut should not be null.");j===l&&(M(h,m),W(a.i.K,e,V(a.i.xa,e)));if("ok"===b){b=[];for(f=0;f<d.length;f++)d[f].status=3,d[f].F&&(h=Dd(a,d[f].path),b.push(Gd(d[f].F,m,k,h))),d[f].ac();Id(a,c);Hd(a);for(f=0;f<b.length;f++)b[f]()}else{if("datastale"===b)for(f=0;f<d.length;f++)d[f].status=4===d[f].status?5:1;else{P("transaction at "+e+" failed: "+b);for(f=0;f<d.length;f++)d[f].status=5,d[f].yc=b}b=zd(a,e);Ad(a,b);td(a.O,b.path(),[e])}},h)}}}else c.A(function(b){Hd(a,
b)})}
function Ad(a,b){var c=b.path();W(a.i.ya,c,V(a.i.K,c));var d=Jd(a,b);if(0!==d.length){for(var e=V(a.i.ya,c),f=[],h=0;h<d.length;h++){var j=Na(c,d[h].path),l=n,o;A(j!==m,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[h].status)l=k,o=d[h].yc;else if(1===d[h].status)if(25<=d[h].Vc)l=k,o="maxretry";else{var q=d[h].update(e.D(j).$());t(q)?(Aa("transaction failed: Data returned ",q),e=e.Va(j,cc(q))):(l=k,o="nodata")}l&&(d[h].ac(),d[h].status=3,d[h].F&&(l=new Y(a,d[h].path),j=
new S(e.D(j),l),"nodata"===o?f.push(Gd(d[h].F,m,n,j)):f.push(Gd(d[h].F,Error(o),n,j))))}d=V(a.i.K,c).m();W(a.i.ya,c,e.bc(d));Hd(a);for(h=0;h<f.length;h++)f[h]()}}function zd(a,b){for(var c,d=a.Yb;(c=F(b))!==m&&d.j()===m;)d=L(d,c),b=La(b);return d}function Jd(a,b){var c=[];Kd(a,b,c);c.sort(function(a,b){return a.Pc-b.Pc});return c}function Kd(a,b,c){var d=b.j();if(d!==m)for(var e=0;e<d.length;e++)c.push(d[e]);b.A(function(b){Kd(a,b,c)})}
function Id(a,b){var c=b.j();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;M(b,0<c.length?c:m)}b.A(function(b){Id(a,b)})}function Gd(a,b,c,d){return!a?p():0<a.length&&4>a.length?function(){a(c,d,b===m?"":b.message)}:function(){a(b,c,d)}};function Z(){this.Ta={}}Z.ld=function(){return Z.Jc?Z.Jc:Z.Jc=new Z};Z.prototype.Oa=function(){for(var a in this.Ta)this.Ta[a].Oa()};Z.prototype.interrupt=Z.prototype.Oa;Z.prototype.pb=function(){for(var a in this.Ta)this.Ta[a].pb()};Z.prototype.resume=Z.prototype.pb;var $={md:function(a){var b=R.prototype.hash;R.prototype.hash=a;return function(){R.prototype.hash=b}}};$.hijackHash=$.md;$.Fa=function(a){return a.Fa()};$.queryIdentifier=$.Fa;$.od=function(a){return a.k.o.ca};$.listens=$.od;$.vd=function(a){return a.k.o.ob};$.refConnection=$.vd;$.cd=Gc;$.DataConnection=$.cd;Gc.prototype.sendRequest=Gc.prototype.wa;Gc.prototype.interrupt=Gc.prototype.Oa;$.dd=U;$.RealTimeConnection=$.dd;U.prototype.sendRequest=U.prototype.sc;U.prototype.close=U.prototype.close;
$.bd=qb;$.ConnectionTarget=$.bd;$.kd=function(){vc=oc=k};$.forceLongPolling=$.kd;$.Ad=function(a,b){a.k.o.rc=b};$.setSecurityDebugCallback=$.Ad;$.tc=function(a,b){a.k.tc(b)};$.stats=$.tc;var Ld,Md=0,Nd=[];Ld=function(){var a=(new Date).getTime()+Vb,b=a===Md;Md=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);A(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===Nd[d];d--)Nd[d]=0;Nd[d]++}else for(d=0;12>d;d++)Nd[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(Nd[d]);A(20===a.length,"NextPushId: Length should be 20.");return a};function Y(){var a,b,c;if(arguments[0]instanceof xd)c=arguments[0],a=arguments[1];else{B("new Firebase",1,2,arguments.length);var d=arguments[0],e="";a="";b=k;var f="";if(v(d)){e=d.indexOf("//");0<=e&&(b="http:"!==d.substring(0,e),d=d.substring(e+2));var h=d.indexOf("/");-1===h&&(h=d.length);e=d.substring(0,h);d=d.substring(h+1);h=e.split(".");if(3==h.length){if("firebase"===h[1])Rb(e+" is no longer supported. Please use <YOUR FIREBASE>.firebaseio.com instead");else{a=h[0];f="";d=("/"+d).split("/");
for(h=0;h<d.length;h++)if(0<d[h].length){var j=d[h];try{j=decodeURIComponent(j.replace(/\+/g," "))}catch(l){}f+="/"+j}}a=a.toLowerCase()}else a=m}b||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&P("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new qb(e,b,a);b=new J(f);e=b.toString();if(!(d=!v(a.host)))if(!(d=0===a.host.length))if(!(d=!ya(a.gb)))if(d=0!==e.length)e&&(e=e.replace(/^\/*\.info(\/|$)/,
"/")),d=!(v(e)&&0!==e.length&&!xa.test(e));d&&g(Error(C("new Firebase",1,n)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Z?c=arguments[1]:g(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Z.ld();e=a.toString();d=ua(c.Ta,e);d||(d=new xd(a),c.Ta[e]=d);c=d;a=b}H.call(this,c,a)}ka(Y,H);var Od=Y,Pd=["Firebase"],Qd=ba;!(Pd[0]in Qd)&&Qd.execScript&&Qd.execScript("var "+Pd[0]);
for(var Rd;Pd.length&&(Rd=Pd.shift());)!Pd.length&&t(Od)?Qd[Rd]=Od:Qd=Qd[Rd]?Qd[Rd]:Qd[Rd]={};Y.prototype.name=function(){B("Firebase.name",0,0,arguments.length);return this.path.f()?m:Ma(this.path)};Y.prototype.name=Y.prototype.name;Y.prototype.B=function(a){B("Firebase.child",1,1,arguments.length);if(fa(a))a=String(a);else if(!(a instanceof J))if(F(this.path)===m){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Ga("Firebase.child",b)}else Ga("Firebase.child",a);return new Y(this.k,this.path.B(a))};
Y.prototype.child=Y.prototype.B;Y.prototype.parent=function(){B("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===m?m:new Y(this.k,a)};Y.prototype.parent=Y.prototype.parent;Y.prototype.toString=function(){B("Firebase.toString",0,0,arguments.length);var a;if(this.parent()===m)a=this.k.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};Y.prototype.toString=Y.prototype.toString;
Y.prototype.set=function(a,b){B("Firebase.set",1,2,arguments.length);Ha("Firebase.set",this.path);za("Firebase.set",a,n);D("Firebase.set",2,b,k);Ed(this.k,"Firebase.set",b);return this.k.rb(this.path,a,m,b)};Y.prototype.set=Y.prototype.set;
Y.prototype.update=function(a,b){B("Firebase.update",1,2,arguments.length);Ha("Firebase.update",this.path);ha(a)||g(Error(C("Firebase.update",1,n)+" must be an object containing the children to replace."));za("Firebase.update",a,n);D("Firebase.update",2,b,k);Ed(this.k,"Firebase.update",b);return this.k.update(this.path,a,b)};Y.prototype.update=Y.prototype.update;
Y.prototype.rb=function(a,b,c){B("Firebase.setWithPriority",2,3,arguments.length);Ha("Firebase.setWithPriority",this.path);za("Firebase.setWithPriority",a,n);Da("Firebase.setWithPriority",2,b,n);D("Firebase.setWithPriority",3,c,k);Ed(this.k,"Firebase.setWithPriority",c);(".length"===this.name()||".keys"===this.name())&&g("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.k.rb(this.path,a,b,c)};Y.prototype.setWithPriority=Y.prototype.rb;
Y.prototype.remove=function(a){B("Firebase.remove",0,1,arguments.length);Ha("Firebase.remove",this.path);D("Firebase.remove",1,a,k);Ed(this.k,"Firebase.remove",a);this.set(m,a)};Y.prototype.remove=Y.prototype.remove;
Y.prototype.transaction=function(a,b){function c(){}B("Firebase.transaction",1,2,arguments.length);Ha("Firebase.transaction",this.path);D("Firebase.transaction",1,a,n);D("Firebase.transaction",2,b,k);var d=this.k;ga(b)&&(0<b.length&&4>b.length)&&(P("\nFirebase.transaction was passed an onComplete callback that takes "+b.length+' arguments.\nOn 2/4/2013, we are changing our transaction callback signature from:\n    function(success, snapshot, abortReason) {\n        // success is true if the transaction was committed, false for any failure.\n    }\nto:\n    function(error, committed, snapshot) { \n        // error is an Error object on fatal errors, else null.\n        // committed is true if the transaction was committed, false if you returned no data from your update function.\n    }\n\nTHIS WILL BE A BREAKING CHANGE!  To fix your code, you can either:\n * Remove all parameters from your callback. E.g.:\n   function() { ... }\n * Opt in to the new behavior early by adding a 4th "dummy" argument. E.g.:\n   function(error, committed, snapshot, dummy) { ... }\nPlease email support@firebase.com for more info.'),
gc(d.T,"old_callback_transaction"),d.Yc.uc.old_callback_transaction=k);(".length"===this.name()||".keys"===this.name())&&g("Firebase.transaction failed: "+this.name()+" is a read-only object.");var e=this.k,f=this.path;e.e("transaction on "+f);var h=new Y(e,f);h.lc("value",c);var d={path:f,update:a,F:b,Pc:Hb(),Vc:0,ac:function(){h.Eb("value",c)}},j=e.i.ya,l=d.update(V(j,f).$());if(t(l)){Aa("transaction failed: Data returned ",l);var o=V(e.i.K,f).m();W(j,f,cc(l,o));td(e.O,f,[f]);d.status=1;f=L(e.Yb,
f);j=f.j()||[];j.push(d);M(f,j);Hd(e)}else d.ac(),d.F&&(e=Dd(e,f),Gd(d.F,m,n,e)())};Y.prototype.transaction=Y.prototype.transaction;Y.prototype.Wb=function(a,b){B("Firebase.setPriority",1,2,arguments.length);Ha("Firebase.setPriority",this.path);Da("Firebase.setPriority",1,a,n);D("Firebase.setPriority",2,b,k);Ed(this.k,"Firebase.setPriority",b);this.k.Wb(this.path,a,b)};Y.prototype.setPriority=Y.prototype.Wb;
Y.prototype.push=function(a,b){B("Firebase.push",0,2,arguments.length);Ha("Firebase.push",this.path);za("Firebase.push",a,k);D("Firebase.push",2,b,k);Ed(this.k,"Firebase.push",b);var c=Ld(),c=this.B(c);"undefined"!==typeof a&&a!==m&&c.set(a,b);return c};Y.prototype.push=Y.prototype.push;Y.prototype.S=function(){var a=this;return{set:function(b){a.k.Vb(a.path,b)},rb:p(),Wb:p(),remove:function(){a.k.Vb(a.path,m)},update:p(),cancel:p()}};Y.prototype.onDisconnect=Y.prototype.S;
Y.prototype.wd=function(){B("Firebase.removeOnDisconnect",0,0,arguments.length);P("FirebaseRef.removeOnDisconnect() being deprecated. Please use FirebaseRef.onDisconnect().remove() instead.");this.S().remove()};Y.prototype.removeOnDisconnect=Y.prototype.wd;Y.prototype.Vb=function(a){B("Firebase.setOnDisconnect",1,1,arguments.length);za("Firebase.setOnDisconnect",a,n);P("FirebaseRef.setOnDisconnect(value) being deprecated. Please use FirebaseRef.onDisconnect().set(value) instead.");this.S().set(a)};
Y.prototype.setOnDisconnect=Y.prototype.Vb;Y.prototype.Wa=function(a,b){B("Firebase.auth",1,2,arguments.length);v(a)||g(Error(C("Firebase.auth",1,n)+"must be a valid credential (a string)."));D("Firebase.auth",2,b,k);Ed(this.k,"Firebase.auth",b);this.k.Wa(a,b)};Y.prototype.auth=Y.prototype.Wa;Y.prototype.ub=function(){this.k.ub()};Y.prototype.unauth=Y.prototype.ub;
function Ob(a,b){A(!b||a===k||a===n,"Can't turn on custom loggers persistently.");a===k?("undefined"!==typeof console&&("function"===typeof console.log?Lb=y(console.log,console):"object"===typeof console.log&&(Lb=function(a){console.log(a)})),b&&O.setItem("logging_enabled","true")):a?Lb=a:(Lb=m,O.removeItem("logging_enabled"))}Y.enableLogging=Ob;Y.INTERNAL=$;Y.Context=Z;})();

exports.Firebase = Firebase;
