
// this is firebase-node.js with long-polling disabled, some window.* -like
// globals added, and a final "exports.Firebase = Firebase" at the end.

var WebSocket = require("websocket").WebSocket; // must provide this
var setTimeout = require("timers").setTimeout;
var clearTimeout = require("timers").clearTimeout;
var setInterval = require("timers").setInterval;

(function() {function g(a){throw a;}var i=void 0,l=!0,m=null,n=!1;function aa(a){return function(){return this[a]}}function p(a){return function(){return a}}var q,ba=this;function ca(){}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return a!==i}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"string"==typeof a}function fa(a){return"number"==typeof a}function ga(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return v.apply(m,arguments)}function ja(a,b){function c(){}c.prototype=b.prototype;a.Uc=b.prototype;a.prototype=new c};function ka(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function la(){this.yb=i}
function ma(a,b,c){switch(typeof b){case "string":na(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if("array"==da(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],ma(a,a.yb?a.yb.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),
na(f,c),c.push(":"),ma(a,a.yb?a.yb.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var oa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},pa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function na(a,b){b.push('"',a.replace(pa,function(a){if(a in oa)return oa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return oa[a]=e+b.toString(16)}),'"')};function y(a){if("undefined"!==typeof JSON&&s(JSON.stringify))a=JSON.stringify(a);else{var b=[];ma(new la,a,b);a=b.join("")}return a};function z(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&g(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function A(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:qa.assert(n,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}return a+" failed: "+(d+" argument ")}
function B(a,b,c,d){(!d||s(c))&&"function"!=da(c)&&g(Error(A(a,b,d)+"must be a valid function."))}function ra(a,b,c){s(c)&&(!ga(c)||c===m)&&g(Error(A(a,b,l)+"must be a valid context object."))};function C(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function sa(a,b){if(Object.prototype.hasOwnProperty.call(a,b))return a[b]};var ta={},qa={},ua=/[\[\].#$\/]/,va=/[\[\].#$]/;function wa(a){return t(a)&&0!==a.length&&!ua.test(a)}function xa(a,b,c){(!c||s(b))&&ya(A(a,1,c),b)}
function ya(a,b,c,d){c||(c=0);d||(d=[]);s(b)||g(Error(a+"contains undefined"+za(d)));"function"==da(b)&&g(Error(a+"contains a function"+za(d)));Aa(b)&&g(Error(a+"contains "+b.toString()+za(d)));1E3<c&&g(new TypeError(a+"contains a cyclic object value ("+d.slice(0,100).join(".")+"...)"));t(b)&&(b.length>10485760/3&&10485760<ta.Vc.Tc(b).length)&&g(Error(a+"contains a string greater than 10485760 utf8 bytes"+za(d)+" ('"+b.substring(0,50)+"...')"));if(ga(b))for(var e in b)C(b,e)&&(".priority"!==e&&(".value"!==
e&&!wa(e))&&g(Error(a+"contains an invalid key ("+e+")"+za(d)+'.  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),d.push(e),ya(a,b[e],c+1,d),d.pop())}function za(a){return 0==a.length?"":" in property "+a.join(".")}function Ba(a,b,c,d){(!d||s(c))&&(c!==m&&!fa(c)&&!t(c))&&g(Error(A(a,b,d)+"must be a valid firebase priority (null or a string.)"))}
function Ca(a,b,c){if(!c||s(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:g(Error(A(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}function Da(a,b){s(b)&&!wa(b)&&g(Error(A(a,2,l)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}
function Ea(a,b){(!t(b)||0===b.length||va.test(b))&&g(Error(A(a,1,n)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function Fa(a,b){".info"===D(b)&&g(Error(a+" failed: Can't modify data under /.info/"))};function E(a,b,c,d,e,f,h){this.n=a;this.path=b;this.ma=c;this.V=Ga.test(d)?Number(d):d;this.ea=e;this.ja=Ga.test(f)?Number(f):f;this.Ca=h;s(this.V)&&(s(this.ja)&&s(this.ma))&&g("Query: Can't combine startAt(), endAt(), and limit().")}E.prototype.Kb=function(a,b){z("Query.on",2,4,arguments.length);Ca("Query.on",a,n);B("Query.on",2,b,n);var c=Ha("Query.on",arguments[2],arguments[3]);this.n.cb(this,a,b,c.cancel,c.S);return b};E.prototype.on=E.prototype.Kb;
E.prototype.lb=function(a,b,c){z("Query.off",0,3,arguments.length);Ca("Query.off",a,l);B("Query.off",2,b,l);ra("Query.off",3,c);this.n.xb(this,a,b,c)};E.prototype.off=E.prototype.lb;E.prototype.Jc=function(a,b){function c(h){f&&(f=n,e.lb(a,c),b.call(d.S,h))}z("Query.once",2,4,arguments.length);Ca("Query.once",a,n);B("Query.once",2,b,n);var d=Ha("Query.once",arguments[2],arguments[3]),e=this,f=l;this.Kb(a,c,function(){e.lb(a,c);d.cancel&&d.cancel.call(d.S)})};E.prototype.once=E.prototype.Jc;
E.prototype.Ec=function(a){z("Query.limit",1,1,arguments.length);(!fa(a)||Math.floor(a)!==a||0>=a)&&g("Query.limit: First argument must be a positive integer.");return new E(this.n,this.path,a,this.V,this.ea,this.ja,this.Ca)};E.prototype.limit=E.prototype.Ec;E.prototype.Sc=function(a,b){z("Query.startAt",0,2,arguments.length);Ba("Query.startAt",1,a,l);Da("Query.startAt",b);s(a)||(b=a=m);return new E(this.n,this.path,this.ma,a,b,this.ja,this.Ca)};E.prototype.startAt=E.prototype.Sc;
E.prototype.Ac=function(a,b){z("Query.endAt",0,2,arguments.length);Ba("Query.endAt",1,a,l);Da("Query.endAt",b);return new E(this.n,this.path,this.ma,this.V,this.ea,a,b)};E.prototype.endAt=E.prototype.Ac;function Ka(a){var b={};s(a.V)&&(b.sp=a.V);s(a.ea)&&(b.sn=a.ea);s(a.ja)&&(b.ep=a.ja);s(a.Ca)&&(b.en=a.Ca);s(a.ma)&&(b.l=a.ma);s(a.V)&&(s(a.ea)&&a.V===m&&a.ea===m)&&(b.vf="l");return b}E.prototype.ua=function(){var a=La(Ka(this));return"{}"===a?"default":a};
function Ha(a,b,c){var d={};b&&c?(d.cancel=b,B(a,3,d.cancel,l),d.S=c,ra(a,4,d.S)):b&&("object"===typeof b&&b!==m?d.S=b:"function"===typeof b?d.cancel=b:g(Error(A(a,3,l)+"must either be a cancel callback or a context object.")));return d};function F(a){if(a instanceof F)return a;if(1==arguments.length){this.k=a.split("/");for(var b=0,c=0;c<this.k.length;c++)0<this.k[c].length&&(this.k[b]=this.k[c],b++);this.k.length=b;this.T=0}else this.k=arguments[0],this.T=arguments[1]}function D(a){return a.T>=a.k.length?m:a.k[a.T]}function Ma(a){var b=a.T;b<a.k.length&&b++;return new F(a.k,b)}function Na(a){return a.T<a.k.length?a.k[a.k.length-1]:m}q=F.prototype;
q.toString=function(){for(var a="",b=this.T;b<this.k.length;b++)""!==this.k[b]&&(a+="/"+this.k[b]);return a||"/"};q.parent=function(){if(this.T>=this.k.length)return m;for(var a=[],b=this.T;b<this.k.length-1;b++)a.push(this.k[b]);return new F(a,0)};q.A=function(a){for(var b=[],c=this.T;c<this.k.length;c++)b.push(this.k[c]);if(a instanceof F)for(c=a.T;c<a.k.length;c++)b.push(a.k[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new F(b,0)};
q.e=function(){return this.T>=this.k.length};function Oa(a,b){var c=D(a);if(c===m)return b;if(c===D(b))return Oa(Ma(a),Ma(b));g("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")}q.contains=function(a){var b=0;if(this.k.length>a.k.length)return n;for(;b<this.k.length;){if(this.k[b]!==a.k[b])return n;++b}return l};function Pa(){this.children={};this.Gb=0;this.value=m}function Qa(a,b,c){this.hb=a?a:"";this.Ta=b?b:m;this.m=c?c:new Pa}function I(a,b){for(var c=b instanceof F?b:new F(b),d=a,e;(e=D(c))!==m;)d=new Qa(e,d,sa(d.m.children,e)||new Pa),c=Ma(c);return d}q=Qa.prototype;q.i=function(){return this.m.value};function J(a,b){K("undefined"!==typeof b);a.m.value=b;Ra(a)}q.gb=function(){return 0<this.m.Gb};q.e=function(){return this.i()===m&&!this.gb()};
q.z=function(a){for(var b in this.m.children)a(new Qa(b,this,this.m.children[b]))};function Sa(a,b,c,d){c&&!d&&b(a);a.z(function(a){Sa(a,b,l,d)});c&&d&&b(a)}function Ta(a,b,c){for(a=c?a:a.parent();a!==m;){if(b(a))return l;a=a.parent()}return n}q.path=function(){return new F(this.Ta===m?this.hb:this.Ta.path()+"/"+this.hb)};q.name=aa("hb");q.parent=aa("Ta");
function Ra(a){if(a.Ta!==m){var b=a.Ta,c=a.hb,d=a.e(),e=C(b.m.children,c);d&&e?(delete b.m.children[c],b.m.Gb--,Ra(b)):!d&&!e&&(b.m.children[c]=a.m,b.m.Gb++,Ra(b))}};function M(a,b){this.Aa=a?a:Ua;this.U=b?b:Va}function Ua(a,b){return a<b?-1:a>b?1:0}q=M.prototype;q.ba=function(a,b){return new M(this.Aa,this.U.ba(a,b,this.Aa).copy(m,m,n,m,m))};q.remove=function(a){return new M(this.Aa,this.U.remove(a,this.Aa).copy(m,m,n,m,m))};q.get=function(a){for(var b,c=this.U;!c.e();){b=this.Aa(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return m};
function Wa(a,b){for(var c,d=a.U,e=m;!d.e();){c=a.Aa(b,d.key);if(0===c){if(d.left.e())return e?e.key:m;for(d=d.left;!d.right.e();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}g("Attempted to find predecessor key for a nonexistent key.  What gives?")}q.e=function(){return this.U.e()};q.count=function(){return this.U.count()};q.Pa=function(){return this.U.Pa()};q.Fa=function(){return this.U.Fa()};q.ka=function(a){return this.U.ka(a)};q.wa=function(a){return this.U.wa(a)};
q.Da=function(a){return new Xa(this.U,a)};function Xa(a,b){this.oc=b;for(this.jb=[];!a.e();)this.jb.push(a),a=a.left}function Ya(a){if(0===a.jb.length)return m;var b=a.jb.pop(),c;c=a.oc?a.oc(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.e();)a.jb.push(b),b=b.left;return c}function Za(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=m?c:l;this.left=d!=m?d:Va;this.right=e!=m?e:Va}q=Za.prototype;
q.copy=function(a,b,c,d,e){return new Za(a!=m?a:this.key,b!=m?b:this.value,c!=m?c:this.color,d!=m?d:this.left,e!=m?e:this.right)};q.count=function(){return this.left.count()+1+this.right.count()};q.e=p(n);q.ka=function(a){return this.left.ka(a)||a(this.key,this.value)||this.right.ka(a)};q.wa=function(a){return this.right.wa(a)||a(this.key,this.value)||this.left.wa(a)};function $a(a){return a.left.e()?a:$a(a.left)}q.Pa=function(){return $a(this).key};
q.Fa=function(){return this.right.e()?this.key:this.right.Fa()};q.ba=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(m,m,m,e.left.ba(a,b,c),m):0===d?e.copy(m,b,m,m,m):e.copy(m,m,m,m,e.right.ba(a,b,c));return ab(e)};function bb(a){if(a.left.e())return Va;!a.left.D()&&!a.left.left.D()&&(a=cb(a));a=a.copy(m,m,m,bb(a.left),m);return ab(a)}
q.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.e()&&(!c.left.D()&&!c.left.left.D())&&(c=cb(c)),c=c.copy(m,m,m,c.left.remove(a,b),m);else{c.left.D()&&(c=db(c));!c.right.e()&&(!c.right.D()&&!c.right.left.D())&&(c=eb(c),c.left.left.D()&&(c=db(c),c=eb(c)));if(0===b(a,c.key)){if(c.right.e())return Va;d=$a(c.right);c=c.copy(d.key,d.value,m,m,bb(c.right))}c=c.copy(m,m,m,m,c.right.remove(a,b))}return ab(c)};q.D=aa("color");
function ab(a){a.right.D()&&!a.left.D()&&(a=fb(a));a.left.D()&&a.left.left.D()&&(a=db(a));a.left.D()&&a.right.D()&&(a=eb(a));return a}function cb(a){a=eb(a);a.right.left.D()&&(a=a.copy(m,m,m,m,db(a.right)),a=fb(a),a=eb(a));return a}function fb(a){var b;b=a.copy(m,m,l,m,a.right.left);return a.right.copy(m,m,a.color,b,m)}function db(a){var b;b=a.copy(m,m,l,a.left.right,m);return a.left.copy(m,m,a.color,m,b)}
function eb(a){var b,c;b=a.left.copy(m,m,!a.left.color,m,m);c=a.right.copy(m,m,!a.right.color,m,m);return a.copy(m,m,!a.color,b,c)}function gb(){}q=gb.prototype;q.copy=function(){return this};q.ba=function(a,b){return new Za(a,b,i,i,i)};q.remove=function(){return this};q.get=p(m);q.count=p(0);q.e=p(l);q.ka=p(n);q.wa=p(n);q.Pa=p(m);q.Fa=p(m);q.D=p(n);var Va=new gb;var hb=Array.prototype,ib=hb.forEach?function(a,b,c){hb.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},jb=hb.map?function(a,b,c){return hb.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};function kb(){};function lb(){this.w=[];this.Fb=[];this.yc=[];this.qb=[];this.qb[0]=128;for(var a=1;64>a;++a)this.qb[a]=0;this.reset()}ja(lb,kb);lb.prototype.reset=function(){this.w[0]=1732584193;this.w[1]=4023233417;this.w[2]=2562383102;this.w[3]=271733878;this.w[4]=3285377520;this.Tb=this.La=0};
function mb(a,b){var c;c||(c=0);for(var d=a.yc,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}c=a.w[0];for(var h=a.w[1],j=a.w[2],k=a.w[3],o=a.w[4],r,e=0;80>e;e++)40>e?20>e?(f=k^h&(j^k),r=1518500249):(f=h^j^k,r=1859775393):60>e?(f=h&j|k&(h|j),r=2400959708):(f=h^j^k,r=3395469782),f=(c<<5|c>>>27)+f+o+r+d[e]&4294967295,o=k,k=j,j=(h<<30|h>>>2)&4294967295,h=c,c=f;a.w[0]=a.w[0]+c&4294967295;a.w[1]=a.w[1]+h&
4294967295;a.w[2]=a.w[2]+j&4294967295;a.w[3]=a.w[3]+k&4294967295;a.w[4]=a.w[4]+o&4294967295}lb.prototype.update=function(a,b){s(b)||(b=a.length);var c=this.Fb,d=this.La,e=0;if(t(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(mb(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(mb(this,c),d=0);this.La=d;this.Tb+=b};function nb(){this.za={};this.length=0}nb.prototype.setItem=function(a,b){C(this.za,a)||(this.length+=1);this.za[a]=b};nb.prototype.getItem=function(a){return C(this.za,a)?this.za[a]:m};nb.prototype.removeItem=function(a){C(this.za,a)&&(this.length-=1,delete this.za[a])};var N=m;if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),N=sessionStorage}catch(ob){N=new nb}else N=new nb;function pb(a,b,c,d){this.host=a;this.Ob=b;this.ib=c;this.la=d||N.getItem(a)||this.host}function qb(a,b){b!==a.la&&(a.la=b,"s-"===a.la.substr(0,2)&&N.setItem(a.host,a.la))};var rb,sb,tb,ub;function vb(){return ba.navigator?ba.navigator.userAgent:m}ub=tb=sb=rb=n;var wb;if(wb=vb()){var xb=ba.navigator;rb=0==wb.indexOf("Opera");sb=!rb&&-1!=wb.indexOf("MSIE");tb=!rb&&-1!=wb.indexOf("WebKit");ub=!rb&&!tb&&"Gecko"==xb.product}var yb=sb,zb=ub,Ab=tb;var Bb;if(rb&&ba.opera){var Cb=ba.opera.version;"function"==typeof Cb&&Cb()}else zb?Bb=/rv\:([^\);]+)(\)|;)/:yb?Bb=/MSIE\s+([^\);]+)(\)|;)/:Ab&&(Bb=/WebKit\/(\S+)/),Bb&&Bb.exec(vb());var Db=m;var Eb,Gb=1;Eb=function(){return Gb++};function K(a,b){a||g(Error("Firebase INTERNAL ASSERT FAILED:"+b))}
function Hb(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);55296<=e&&56319>=e&&(e-=55296,d++,K(d<a.length,"Surrogate pair missing trail surrogate."),e=65536+(e<<10)+(a.charCodeAt(d)-56320));128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(65536>e?b[c++]=e>>12|224:(b[c++]=e>>18|240,b[c++]=e>>12&63|128),b[c++]=e>>6&63|128),b[c++]=e&63|128)}a=new lb;a.update(b);b=[];d=8*a.Tb;56>a.La?a.update(a.qb,56-a.La):a.update(a.qb,64-(a.La-56));for(c=63;56<=c;c--)a.Fb[c]=d&255,d/=256;mb(a,a.Fb);for(c=d=0;5>
c;c++)for(e=24;0<=e;e-=8)b[d++]=a.w[c]>>e&255;ea(b)||g(Error("encodeByteArray takes an array as a parameter"));if(!Db){Db={};for(a=0;65>a;a++)Db[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=Db;c=[];for(d=0;d<b.length;d+=3){var f=b[d],h=(e=d+1<b.length)?b[d+1]:0,j=d+2<b.length,k=j?b[d+2]:0,o=f>>2,f=(f&3)<<4|h>>4,h=(h&15)<<2|k>>6,k=k&63;j||(k=64,e||(h=64));c.push(a[o],a[f],a[h],a[k])}return c.join("")}
function Ib(){for(var a="",b=0;b<arguments.length;b++)a=ea(arguments[b])?a+Ib.apply(m,arguments[b]):"object"===typeof arguments[b]?a+y(arguments[b]):a+arguments[b],a+=" ";return a}var Jb=m,Kb=l;function Lb(){Kb===l&&(Kb=n,Jb===m&&"true"===N.getItem("logging_enabled")&&Mb(l));if(Jb){var a=Ib.apply(m,arguments);Jb(a)}}function Nb(a){return function(){Lb(a,arguments)}}function Ob(){if("undefined"!==typeof console){var a=Ib.apply(m,arguments);console.log("FIREBASE INTERNAL ERROR: "+a)}}
function Pb(){if("undefined"!==typeof console){var a=Ib.apply(m,arguments);console.log("FIREBASE WARNING: "+a)}}function Qb(a){for(var b="",a=a.split("/"),c=0;c<a.length;c++)if(0<a[c].length){var d=a[c];try{d=decodeURIComponent(d.replace(/\+/g," "))}catch(e){}b+="/"+d}return b}var Ga=/^[\-+]?[0-9]*\.?[0-9]+(e\-|e\+|E\-|E\+|e|E)?[0-9]*$/;function Aa(a){return fa(a)&&(a!=a||a==Number.POSITIVE_INFINITY||a==Number.NEGATIVE_INFINITY)}
function Rb(a,b){return a!==b?a===m?-1:b===m?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Sb(a,b){if(b&&a in b)return b[a];g(Error("Missing required key ("+a+") in object: "+y(b)))}var Tb=0;function La(a){if("object"!==typeof a||a===m)return y(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=y(b[d]),c+=":",c+=La(a[b[d]]);return c+"}"};function Ub(a,b){this.ha=a;K(this.ha!==m,"LeafNode shouldn't be created with null value.");this.Ga="undefined"!==typeof b?b:m}q=Ub.prototype;q.I=p(l);q.j=aa("Ga");q.Eb=function(a){return new Ub(this.ha,a)};q.L=function(){return O};q.C=function(a){return D(a)===m?this:O};q.P=p(m);q.B=function(a,b){return(new P(new M,this.Ga)).B(a,b)};q.Ia=function(a,b){var c=D(a);return c===m?b:this.B(c,O.Ia(Ma(a),b))};q.e=p(n);q.kb=p(0);
q.W=function(a){return a&&this.j()!==m?{".value":this.i(),".priority":""+this.j()}:this.i()};
q.hash=function(){var a="";this.j()!==m&&(a+="priority:"+this.j()+":");var b=typeof this.ha,a=a+(b+":");if("number"===b){b=this.ha;K(!Aa(b));var c,d,e,f;0===b?(e=d=0,c=-Infinity===1/b?1:0):(c=0>b,b=Math.abs(b),b>=Math.pow(2,-1022)?(e=Math.min(Math.floor(Math.log(b)/Math.LN2),1023),d=e+1023,e=Math.round(b*Math.pow(2,52-e)-Math.pow(2,52))):(d=0,e=Math.round(b/Math.pow(2,-1074))));f=[];for(b=52;b;b-=1)f.push(e%2?1:0),e=Math.floor(e/2);for(b=11;b;b-=1)f.push(d%2?1:0),d=Math.floor(d/2);f.push(c?1:0);f.reverse();
c=f.join("");d="";for(b=0;64>b;b+=8)e=parseInt(c.substr(b,8),2).toString(16),1===e.length&&(e="0"+e),d+=e;a+=d.toLowerCase()}else a+=this.ha;return Hb(a)};q.i=aa("ha");q.toString=function(){return"string"===typeof this.ha?'"'+this.ha+'"':this.ha};function P(a,b){this.O=a||new M;this.Ga="undefined"!==typeof b?b:m}q=P.prototype;q.I=p(n);q.j=aa("Ga");q.Eb=function(a){return new P(this.O,a)};q.B=function(a,b){var c=this.O.remove(a);b&&b.e()&&(b=m);b!==m&&(c=c.ba(a,b));return b&&b.j()!==m?new Vb(c,m,this.Ga):new P(c,this.Ga)};q.Ia=function(a,b){var c=D(a);if(c===m)return b;var d=this.L(c).Ia(Ma(a),b);return this.B(c,d)};q.e=function(){return this.O.e()};q.kb=function(){return this.O.count()};var Wb=/^\d+$/;q=P.prototype;
q.W=function(a){if(this.e())return m;var b={},c=0,d=0,e=l;this.z(function(f,h){b[f]=h.W(a);c++;e&&Wb.test(f)?d=Math.max(d,Number(f)):e=n});if(!a&&e&&d<2*c){var f=[],h;for(h in b)f[h]=b[h];return f}a&&this.j()!==m&&(b[".priority"]=""+this.j());return b};q.hash=function(){var a="";this.j()!==m&&(a+="priority:"+this.j()+":");this.z(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Hb(a)};q.L=function(a){a=this.O.get(a);return a===m?O:a};
q.C=function(a){var b=D(a);return b===m?this:this.L(b).C(Ma(a))};q.P=function(a){return Wa(this.O,a)};q.cc=function(){return this.O.Pa()};q.ec=function(){return this.O.Fa()};q.z=function(a){return this.O.ka(a)};q.Hb=function(a){return this.O.wa(a)};q.Da=function(){return this.O.Da()};q.toString=function(){var a="{",b=l;this.z(function(c,d){b?b=n:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var O=new P(new M);function Vb(a,b,c){P.call(this,a,c);b===m&&(b=new M(Xb),a.ka(function(a,c){b=b.ba({name:a,na:c.j()},c)}));this.da=b}ja(Vb,P);q=Vb.prototype;q.B=function(a,b){var c=this.L(a),d=this.O,e=this.da;c!==m&&(d=d.remove(a),e=e.remove({name:a,na:c.j()}));b&&b.e()&&(b=m);b!==m&&(d=d.ba(a,b),e=e.ba({name:a,na:b.j()},b));return new Vb(d,e,this.j())};q.P=function(a,b){var c=Wa(this.da,{name:a,na:b.j()});return c?c.name:m};q.z=function(a){return this.da.ka(function(b,c){return a(b.name,c)})};
q.Hb=function(a){return this.da.wa(function(b,c){return a(b.name,c)})};q.Da=function(){return this.da.Da(function(a,b){return{key:a.name,value:b}})};q.cc=function(){return this.da.e()?m:this.da.Pa().name};q.ec=function(){return this.da.e()?m:this.da.Fa().name};function Q(a,b){if("object"!==typeof a)return new Ub(a,b);if(a===m)return O;var c=m;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);c!==m&&(c=Ga.test(c)?Number(c):c);if(".value"in a&&a[".value"]!==m)return new Ub(a[".value"],c);var c=new P(new M,c),d;for(d in a)if(C(a,d)&&"."!==d.substring(0,1)){var e=Q(a[d]);if(e.I()||!e.e())c=c.B(d,e)}return c}function Xb(a,b){return Rb(a.na,b.na)||(a.name!==b.name?a.name<b.name?-1:1:0)};function R(a,b){this.m=a;this.wb=b}R.prototype.W=function(){z("Firebase.DataSnapshot.val",0,0,arguments.length);return this.m.W()};R.prototype.val=R.prototype.W;R.prototype.Bc=function(){z("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.m.W(l)};R.prototype.exportVal=R.prototype.Bc;R.prototype.A=function(a){z("Firebase.DataSnapshot.child",0,1,arguments.length);fa(a)&&(a=String(a));Ea("Firebase.DataSnapshot.child",a);var b=new F(a),c=this.wb.A(b);return new R(this.m.C(b),c)};
R.prototype.child=R.prototype.A;R.prototype.Ib=function(a){z("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Ea("Firebase.DataSnapshot.hasChild",a);var b=new F(a);return!this.m.C(b).e()};R.prototype.hasChild=R.prototype.Ib;R.prototype.j=function(){z("Firebase.DataSnapshot.getPriority",0,0,arguments.length);var a=this.m.j();return a===m?a:""+a};R.prototype.getPriority=R.prototype.j;
R.prototype.forEach=function(a){z("Firebase.DataSnapshot.forEach",1,1,arguments.length);B("Firebase.DataSnapshot.forEach",1,a,n);if(this.m.I())return n;var b=this;return this.m.z(function(c,d){return a(new R(d,b.wb.A(c)))})};R.prototype.forEach=R.prototype.forEach;R.prototype.gb=function(){z("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.m.I()?n:!this.m.e()};R.prototype.hasChildren=R.prototype.gb;
R.prototype.name=function(){z("Firebase.DataSnapshot.name",0,0,arguments.length);return this.wb.name()};R.prototype.name=R.prototype.name;R.prototype.kb=function(){z("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.m.kb()};R.prototype.numChildren=R.prototype.kb;R.prototype.Kc=function(){z("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.wb};R.prototype.ref=R.prototype.Kc;var Yb=m;"undefined"!==typeof MozWebSocket?Yb=MozWebSocket:"undefined"!==typeof WebSocket&&(Yb=WebSocket);function Zb(a,b,c){this.Wb=a;this.c=Nb(this.Wb);this.frames=this.Na=m;this.Sb=0;this.Ba=(b.Ob?"wss://":"ws://")+b.la+"/.ws?v=5";b.host!==b.la&&(this.Ba=this.Ba+"&ns="+b.ib);c&&(this.Ba=this.Ba+"&s="+c)}var $b;
Zb.prototype.open=function(a,b){this.Qa=b;this.ob=a;this.c("websocket connecting to "+this.Ba);this.Q=new Yb(this.Ba);this.$b=n;var c=this;this.Q.onopen=function(){c.c("Websocket connected.");c.$b=l};this.Q.onclose=function(){c.c("Websocket connection was disconnected.");c.Q=m;ac(c)};this.Q.onmessage=function(a){if(c.Q!==m)if(a=a.data,c.frames!==m)bc(c,a);else{a:{K(c.frames===m,"We already have a frame buffer");if(4>=a.length){var b=Number(a);if(!isNaN(b)){c.Sb=b;c.frames=[];a=m;break a}}c.Sb=1;c.frames=
[]}a!==m&&bc(c,a)}};this.Q.onerror=function(){c.c("WebSocket error.  Closing connection.");ac(c)}};Zb.prototype.start=function(){};Zb.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&Yb!==m&&!$b};function bc(a,b){a.frames.push(b);if(a.frames.length==a.Sb){var c=a.frames.join("");a.frames=m;c="undefined"!==typeof JSON&&s(JSON.parse)?JSON.parse(c):ka(c);cc(a);a.ob(c)}}
Zb.prototype.send=function(a){cc(this);a=y(a);if(16384>=a.length)a=[a];else{for(var b=[],c=0;c<a.length;c+=16384)c+16384>a?b.push(a.substring(c,a.length)):b.push(a.substring(c,c+16384));a=b}1<a.length&&this.Q.send(String(a.length));for(b=0;b<a.length;b++)this.Q.send(a[b])};function dc(a){a.hc=l;a.Na&&(clearTimeout(a.Na),a.Na=m);a.Q&&(a.Q.close(),a.Q=m)}function ac(a){a.hc||(a.c("WebSocket is closing itself"),dc(a),a.Qa&&(a.Qa(a.$b),a.Qa=m))}
Zb.prototype.close=function(){this.hc||(this.c("WebSocket is being closed"),dc(this))};function cc(a){clearTimeout(a.Na);a.Na=setInterval(function(){a.Q.send("0");cc(a)},45E3)};function S(a,b){for(var c in a)b.call(i,a[c],c,a)};function ec(){this.set={}}q=ec.prototype;q.add=function(a,b){this.set[a]=b!==m?b:l};q.contains=function(a){return C(this.set,a)};q.get=function(a){return this.set[a]};q.remove=function(a){delete this.set[a]};q.e=function(){var a;a:{for(a in this.set){a=n;break a}a=l}return a};q.count=function(){var a=0,b;for(b in this.set)a++;return a};q.keys=function(){var a=[],b;for(b in this.set)C(this.set,b)&&a.push(b);return a};function fc(){function a(a,c){c&&c.isAvailable()&&b.push(c)}var b=[],c=gc;if("array"==da(c))for(var d=0;d<c.length;++d)a(0,c[d]);else S(c,a);this.Cb=b}var gc=[Zb];function T(a,b,c,d,e,f){this.id=a;this.c=Nb("c:"+this.id+":");this.Ic=c;this.Ra=d;this.ta=e;this.Nb=f;this.K=b;this.rb=[];this.Xb=0;this.Ub=new fc;this.fa=0;this.c("Connection created");hc(this)}function hc(a){var b;var c=a.Ub;0<c.Cb.length?b=c.Cb[0]:g(Error("No transports available"));a.H=new b("c:"+a.id+":"+a.Xb++,a.K);b=ic(a,a.H);c=jc(a,a.H);a.ab=a.H;a.Za=a.H;a.H.open(b,c);a.o=m}
function jc(a,b){return function(c){b===a.H?(a.H=m,!c&&0===a.fa?(a.c("Realtime connection failed."),"s-"===a.K.la.substr(0,2)&&(N.removeItem(a.K.ib),a.K.la=a.K.host)):1===a.fa&&a.c("Realtime connection lost."),a.close()):b===a.o?(c=a.o,a.o=m,(a.ab===c||a.Za===c)&&a.close()):a.c("closing an old connection")}}
function ic(a,b){return function(c){if(2!=a.fa)if(b===a.Za){var d=Sb("t",c),c=Sb("d",c);if("c"==d){if(d=Sb("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,f=c.h;a.Pc=c.s;qb(a.K,f);if(0==a.fa&&(a.H.start(),c=a.H,a.c("Realtime connection established."),a.H=c,a.fa=1,a.Ra&&(a.Ra(d),a.Ra=m),"4"!==e&&Pb("Protocol version mismatch detected"),c=1<a.Ub.Cb.length?a.Ub.Cb[1]:m))a.o=new c("c:"+a.id+":"+a.Xb++,a.K,a.Pc),a.o.open(ic(a,a.o),jc(a,a.o))}else if("n"===d){a.c("recvd end transmission on primary");
a.Za=a.o;for(c=0;c<a.rb.length;++c)a.mb(a.rb[c]);a.rb=[];kc(a)}else"s"===d?(a.c("Connection shutdown command received. Shutting down..."),a.Nb&&(a.Nb(c),a.Nb=m),a.ta=m,a.close()):"r"===d?(a.c("Reset packet received.  New host: "+c),qb(a.K,c),1===a.fa?a.close():(lc(a),hc(a))):Ob("Unknown control packet command: "+d)}else"d"==d&&a.mb(c)}else b===a.o?(d=Sb("t",c),c=Sb("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.o.start(),a.c("sending client ack on secondary"),a.o.send({t:"c",d:{t:"a",d:{}}}),a.c("Ending transmission on primary"),
a.H.send({t:"c",d:{t:"n",d:{}}}),a.ab=a.o,kc(a)):"r"===c&&(a.c("Got a reset on secondary, closing it"),a.o.close(),(a.ab===a.o||a.Za===a.o)&&a.close())):"d"==d?a.rb.push(c):g(Error("Unknown protocol layer: "+d))):a.c("message on old connection")}}T.prototype.Qb=function(a){a={t:"d",d:a};1!==this.fa&&g("Connection is not connected");this.ab.send(a)};function kc(a){a.ab===a.o&&a.Za===a.o&&(a.c("cleaning up and promoting a connection: "+a.o.Wb),a.H=a.o,a.o=m)}T.prototype.mb=function(a){this.Ic(a)};
T.prototype.close=function(){2!==this.fa&&(this.c("Closing realtime connection."),this.fa=2,lc(this),this.ta&&(this.ta(),this.ta=m))};function lc(a){a.c("Shutting down all connections");a.H&&(a.H.close(),a.H=m);a.o&&(a.o.close(),a.o=m)};function mc(a,b,c,d){this.id=nc++;this.c=Nb("p:"+this.id+":");this.$a=l;this.X={};this.M=[];this.Sa=0;this.Mb={};this.aa=n;this.vb=1E3;this.nb=b;this.kc=c;this.ta=d;this.K=a;this.Pb=m;this.sb=[];this.oa={};this.Oc=0;this.Oa=this.ic=m;setTimeout(v(this.Yb,this),0)}var nc=0,oc=0;q=mc.prototype;
q.ya=function(a,b,c,d){var e=++this.Oc,a={r:e,a:a,b:b};this.c(y(a));this.aa?this.Xa.Qb(a):this.sb.push(a);var f=this,a=setTimeout(function(){var a=f.oa[e];a&&(delete f.oa[e],a.$&&a.$.pb&&a.$.pb())},45E3);this.oa[e]={$:{ob:c,pb:d},sc:a}};function pc(a,b,c,d,e){a.c("Listen on "+b+" for "+c);var f={p:b},d=jb(d,function(a){return Ka(a)});"{}"!==c&&(f.q=d);a.ya("l",f,function(d){a.c("listen response",d);d=d.s;"ok"!==d&&qc(a,b,c);e&&e(d)},function(){a.c("timed out on listen...")})}
q.Ja=function(a,b){this.eb={zc:a,ac:n,Y:b};this.c("Authenticating using credential: "+this.eb);rc(this)};q.bb=function(){delete this.eb;this.aa&&this.ya("unauth",{},function(){},function(){})};function rc(a){var b=a.eb;a.aa&&b&&a.ya("auth",{cred:b.zc},function(c){(c="ok"==c.s)||delete a.eb;b.ac||(b.ac=l,b.Y&&b.Y(c))},function(){a.c("timed out on auth...")})}
q.uc=function(a,b,c){a=a.toString();if(qc(this,a,b)&&this.aa){this.c("Unlisten on "+a+" for "+b);var d=this,a={p:a},c=jb(c,function(a){return Ka(a)});"{}"!==b&&(a.q=c);this.ya("u",a,m,function(){d.c("timed out on unlisten...")})}};q.Qa=function(a,b){this.Mb[a]=b;this.aa&&sc(this,a,b)};function sc(a,b,c){b={p:b,d:c};a.c("onDisconnect",b);a.ya("o",b,function(a){"ok"!==a.s&&g("onDisconnect failed: "+y(a.d))},function(){a.c("timed out on onDisconnect...")})}q.put=function(a,b,c,d){tc(this,"p",a,b,c,d)};
function tc(a,b,c,d,e,f){c={p:c,d:d};s(f)&&(c.h=f);a.M.push({action:b,nc:c,F:e});a.Sa++;b=a.M.length-1;a.aa&&uc(a,b)}function uc(a,b){var c=a.M[b].action,d=a.M[b].F;a.ya(c,a.M[b].nc,function(e){a.c(c+" response",e);delete a.M[b];a.Sa--;0===a.Sa&&(a.M=[]);d&&d(e.s)},function(){a.c("timed out on put...")})}
q.mb=function(a){if("r"in a){this.c("from server: "+y(a));var b=a.r,c=this.oa[b];c&&(delete this.oa[b],clearTimeout(c.sc),c.$&&c.$.ob&&c.$.ob(a.b))}else"error"in a&&g("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,c=a.b,this.c("handleServerMessage",b,c),"d"===b?this.nb(c.p,c.d):"m"===b?this.nb(c.p,c.d,l):"c"===b?(a=c.p,b=(b=c.q)?jb(b,function(a){return La(a)}).join("$"):"{}",(a=qc(this,a,b))&&a.F&&a.F("permission_denied")):"sd"===b?this.Pb?this.Pb(c):"msg"in c&&"undefined"!==typeof console&&
console.log("FIREBASE: "+c.msg.replace("\n","\nFIREBASE: ")):Ob("Unrecognized action received from server: "+y(b)+"\nAre you using the latest client?"))};
q.Ra=function(a){this.c("connection ready");this.aa=l;this.Oa=(new Date).getTime();Tb=a-(new Date).getTime();for(a=0;a<this.sb.length;a++)this.Xa.Qb(this.sb[a]);this.sb=[];rc(this);for(var b in this.X)for(var c in this.X[b])a=this.X[b][c],pc(this,b,c,a.Ha,a.F);for(b in this.Mb)sc(this,b,this.Mb[b]);for(b=0;b<this.M.length;b++)this.M[b]&&uc(this,b);this.kc&&this.kc()};
q.lc=function(){this.aa=n;this.c("data client disconnected");if(!this.$a){for(var a=0;a<this.M.length;a++){var b=this.M[a];b&&"h"in b.nc&&(b.F&&b.F("disconnect"),delete this.M[a],this.Sa--)}0===this.Sa&&(this.M=[]);for(var c in this.oa)a=this.oa[c],delete this.oa[c],a!==m&&(a.$&&a.$.pb&&a.$.pb(),clearTimeout(a.sc))}var d=v(function(){this.Yb()},this);this.$a?(this.Oa&&(3E4<(new Date).getTime()-this.Oa&&(this.vb=1E3),this.Oa=m),c=Math.max(0,this.vb-((new Date).getTime()-this.ic)),c*=Math.random(),
this.c("Trying to reconnect in "+c+"ms"),setTimeout(d,c),this.vb=Math.min(3E4,1.3*this.vb)):this.pc=function(){setTimeout(d,0)};this.ta&&this.ta()};q.Yb=function(){if(this.$a){this.c("Making a connection attempt");this.ic=(new Date).getTime();this.Oa=m;var a=v(this.mb,this),b=v(this.Ra,this),c=v(this.lc,this),d=this.id+":"+oc++;this.Xa=new T(d,this.K,a,b,c,function(a){g(Error(a))})}};q.Ea=function(){this.$a=n;this.Xa?this.Xa.close():this.lc()};q.Ya=function(){this.$a=l;this.pc();this.pc=i};
function qc(a,b,c){b=(new F(b)).toString();c||(c="{}");var d=a.X[b][c];delete a.X[b][c];return d};function vc(){this.xa=O}function U(a,b){return a.xa.C(b)}function V(a,b,c){a.xa=a.xa.Ia(b,c)}vc.prototype.toString=function(){return this.xa.toString()};function wc(){this.pa=new vc;this.J=new vc;this.qa=new vc;this.Va=new Qa}function xc(a,b){for(var c=U(a.pa,b),d=U(a.J,b),e=I(a.Va,b),f=n,h=e;h!==m;){if(h.i()!==m){f=l;break}h=h.parent()}if(f)return n;c=yc(c,d,e);return c!==d?(V(a.J,b,c),l):n}function yc(a,b,c){if(c.e())return a;if(c.i()!==m)return b;a=a||O;c.z(function(d){var d=d.name(),e=a.L(d),f=b.L(d),h=I(c,d),e=yc(e,f,h);a=a.B(d,e)});return a}
wc.prototype.set=function(a,b){var c=this,d=[];ib(b,function(a){var b=a.path,a=a.sa,h=Eb();J(I(c.Va,b),h);V(c.J,b,a);d.push({path:b,Qc:h})});return d};function zc(a,b){ib(b,function(b){var d=b.Qc,b=I(a.Va,b.path),e=b.i();K(e!==m,"pendingPut should not be null.");e===d&&J(b,m)})};function Ac(){this.ra=[]}function Bc(a,b){if(0!==b.length){a.ra.push.apply(a.ra,b);for(var c=0;c<a.ra.length;c++)if(a.ra[c]){var d=a.ra[c];a.ra[c]=m;var e=d.Y;e(d.rc,d.Wa)}a.ra=[]}};function W(a,b,c,d){this.type=a;this.ca=b;this.R=c;this.Wa=d};function Cc(a){this.G=a;this.Z=[];this.Zb=new Ac}function Dc(a,b,c,d,e){a.Z.push({type:b,Y:c,cancel:d,S:e});var d=[],f=Ec(a.f);a.Ma&&f.push(new W("value",a.f));for(var h=0;h<f.length;h++)if(f[h].type===b){var j=new X(a.G.n,a.G.path);f[h].R&&(j=j.A(f[h].R));d.push({Y:e?v(c,e):c,rc:new R(f[h].ca,j),Wa:f[h].Wa})}Bc(a.Zb,d)}Cc.prototype.tb=function(a,b){b=this.ub(a,b);b!=m&&Fc(this,b)};
function Fc(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],f=e.type,h=new X(a.G.n,a.G.path);b[d].R&&(h=h.A(b[d].R));h=new R(b[d].ca,h);"value"===e.type&&!h.gb()?f+="("+h.W()+")":"value"!==e.type&&(f+=" "+h.name());Lb(a.G.n.u.id+": event:"+a.G.path+":"+a.G.ua()+":"+f);for(f=0;f<a.Z.length;f++){var j=a.Z[f];b[d].type===j.type&&c.push({Y:j.S?v(j.Y,j.S):j.Y,rc:h,Wa:e.Wa})}}Bc(a.Zb,c)}function Ec(a){var b=[];if(!a.I()){var c=m;a.z(function(a,e){b.push(new W("child_added",e,a,c));c=a})}return b}
function Gc(a){a.Ma||(a.Ma=l,Fc(a,[new W("value",a.f)]))};function Hc(a,b){Cc.call(this,a);this.f=b}ja(Hc,Cc);Hc.prototype.ub=function(a,b){this.f=a;this.Ma&&b!=m&&b.push(new W("value",this.f));return b};Hc.prototype.Ka=function(){return{}};function Ic(a,b){this.fb=a;this.Lb=b}
function Jc(a,b,c,d,e){var f=a.C(c),h=b.C(c),d=new Ic(d,e),e=Mc(d,c,f,h),j=n;if(!f.e()&&!h.e()&&f.j()!==h.j())var j=a.C(c.parent()),k=b.C(c.parent()),o=Na(c),j=j.P(o,f)!=k.P(o,h);if(e||j){f=c;c=e;for(h=j;f.parent()!==m;){var r=a.C(f),e=b.C(f),j=f.parent();if(!d.fb||I(d.fb,j).i())k=b.C(j),o=[],f=Na(f),r.e()?(r=k.P(f,e),o.push(new W("child_added",e,f,r))):e.e()?o.push(new W("child_removed",r,f)):(r=k.P(f,e),h&&o.push(new W("child_moved",e,f,r)),c&&o.push(new W("child_changed",e,f,r))),d.Lb(j,k,o);h&&
(h=n,c=l);f=j}}}function Mc(a,b,c,d){var e,f=[];c===d?e=n:c.I()&&d.I()?e=c.i()!==d.i():c.I()?(Nc(a,b,O,d,f),e=l):d.I()?(Nc(a,b,c,O,f),e=l):e=Nc(a,b,c,d,f);e?a.Lb(b,d,f):c.j()!==d.j()&&a.Lb(b,d,m);return e}
function Nc(a,b,c,d,e){var f=n,h=!a.fb||!I(a.fb,b).e(),j=[],k=[],o=[],r=[],x={},u={},w,L,H,G;w=c.Da();H=Ya(w);L=d.Da();for(G=Ya(L);H!==m||G!==m;){c=H===m?1:G===m?-1:H.key===G.key?0:Xb({name:H.key,na:H.value.j()},{name:G.key,na:G.value.j()});if(0>c)f=sa(x,H.key),s(f)?(o.push({bc:H,tc:j[f]}),j[f]=m):(u[H.key]=k.length,k.push(H)),f=l,H=Ya(w);else{if(0<c)f=sa(u,G.key),s(f)?(o.push({bc:k[f],tc:G}),k[f]=m):(x[G.key]=j.length,j.push(G)),f=l;else{c=b.A(G.key);if(c=Mc(a,c,H.value,G.value))r.push(G),f=l;H=
Ya(w)}G=Ya(L)}if(!h&&f)return l}for(h=0;h<k.length;h++)if(x=k[h])c=b.A(x.key),Mc(a,c,x.value,O),e.push(new W("child_removed",x.value,x.key));for(h=0;h<j.length;h++)if(x=j[h])c=b.A(x.key),k=d.P(x.key,x.value),Mc(a,c,O,x.value),e.push(new W("child_added",x.value,x.key,k));for(h=0;h<o.length;h++)x=o[h].bc,j=o[h].tc,c=b.A(j.key),k=d.P(j.key,j.value),e.push(new W("child_moved",j.value,j.key,k)),(c=Mc(a,c,x.value,j.value))&&r.push(j);for(h=0;h<r.length;h++)a=r[h],k=d.P(a.key,a.value),e.push(new W("child_changed",
a.value,a.key,k));return f};function Oc(){this.Ua=this.ga=m;this.set={}}ja(Oc,ec);q=Oc.prototype;q.setActive=function(a){this.ga=a};function Pc(a){return a.contains("default")}function Qc(a){return a.ga!=m&&Pc(a)}q.defaultView=function(){return Pc(this)?this.get("default"):m};q.path=aa("Ua");q.toString=function(){return jb(this.keys(),function(a){return"default"===a?"{}":a}).join("$")};q.Ha=function(){var a=[];S(this.set,function(b){a.push(b.G)});return a};function Rc(a,b){Cc.call(this,a);this.f=O;this.ub(b,Ec(b))}ja(Rc,Cc);
Rc.prototype.ub=function(a,b){if(b===m)return b;var c=[],d=this.G;s(d.V)&&(s(d.ea)&&d.ea!=m?c.push(function(a,b){var c=Rb(b,d.V);return 0<c||0===c&&a>=d.ea}):c.push(function(a,b){return 0<=Rb(b,d.V)}));s(d.ja)&&(s(d.Ca)?c.push(function(a,b){var c=Rb(b,d.ja);return 0>c||0===c&&a<=d.Ca}):c.push(function(a,b){return 0>=Rb(b,d.ja)}));var e=m,f=m;if(s(this.G.ma))if(s(this.G.V)){if(e=Sc(a,c,this.G.ma,n)){var h=a.L(e).j();c.push(function(a,b){var c=Rb(b,h);return 0>c||0===c&&a<=e})}}else if(f=Sc(a,c,this.G.ma,
l)){var j=a.L(f).j();c.push(function(a,b){var c=Rb(b,j);return 0<c||0===c&&a>=f})}for(var k=[],o=[],r=[],x=[],u=0;u<b.length;u++){var w=b[u].R,L=b[u].ca;switch(b[u].type){case "child_added":Tc(c,w,L)&&(this.f=this.f.B(w,L),o.push(b[u]));break;case "child_removed":this.f.L(w).e()||(this.f=this.f.B(w,m),k.push(b[u]));break;case "child_changed":!this.f.L(w).e()&&Tc(c,w,L)&&(this.f=this.f.B(w,L),x.push(b[u]));break;case "child_moved":var H=!this.f.L(w).e(),G=Tc(c,w,L);H?G?(this.f=this.f.B(w,L),r.push(b[u])):
(k.push(new W("child_removed",this.f.L(w),w)),this.f=this.f.B(w,m)):G&&(this.f=this.f.B(w,L),o.push(b[u]))}}var Kc=e||f;if(Kc){var Lc=(u=f!==m)?this.f.cc():this.f.ec(),Fb=n,Ia=n,Ja=this;(u?a.Hb:a.z).call(a,function(a,b){!Ia&&Lc===m&&(Ia=l);if(Ia&&Fb)return l;Fb?(k.push(new W("child_removed",Ja.f.L(a),a)),Ja.f=Ja.f.B(a,m)):Ia&&(o.push(new W("child_added",b,a)),Ja.f=Ja.f.B(a,b));Lc===a&&(Ia=l);a===Kc&&(Fb=l)})}for(u=0;u<o.length;u++)c=o[u],w=this.f.P(c.R,c.ca),k.push(new W("child_added",c.ca,c.R,w));
for(u=0;u<r.length;u++)c=r[u],w=this.f.P(c.R,c.ca),k.push(new W("child_moved",c.ca,c.R,w));for(u=0;u<x.length;u++)c=x[u],w=this.f.P(c.R,c.ca),k.push(new W("child_changed",c.ca,c.R,w));this.Ma&&0<k.length&&k.push(new W("value",this.f));return k};function Sc(a,b,c,d){if(a.I())return m;var e=m;(d?a.Hb:a.z).call(a,function(a,d){if(Tc(b,a,d)&&(e=a,c--,0===c))return l});return e}function Tc(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.j()))return n;return l}
Rc.prototype.Ib=function(a){return this.f.L(a)!==O};Rc.prototype.Ka=function(a,b,c){var d={};this.f.I()||this.f.z(function(a){d[a]=l});var e=this.f,c=U(c,new F("")),f=new Qa;J(I(f,this.G.path),l);var h=O.Ia(a,b),j=[];Jc(c,h,a,f,function(a,b,c){c!==m&&(j=j.concat(c))});this.ub(b,j);this.f.I()||this.f.z(function(a){d[a]=l});this.f=e;return d};function Uc(a,b){this.u=a;this.g=b;this.jc=b.xa;this.ia=new Qa}
Uc.prototype.cb=function(a,b,c,d,e){var f=a.path,h=I(this.ia,f),j=h.i();j===m?(j=new Oc,J(h,j)):K(!j.e(),"We shouldn't be storing empty QueryMaps");var k=a.ua();if(j.contains(k))Dc(j.get(k),b,c,d,e);else{var o=this.g.xa.C(f),a="default"===a.ua()?new Hc(a,o):new Rc(a,o);if(Qc(j)||Vc(h))j.add(k,a),j.Ua||(j.Ua=a.G.path);else{var r,x;j.e()||(r=j.toString(),x=j.Ha());j.add(k,a);j.Ua||(j.Ua=a.G.path);j.setActive(Wc(this,j));r&&x&&this.u.uc(j.path(),r,x)}Qc(j)&&Sa(h,function(a){if(a=a.i()){a.ga&&a.ga();
a.ga=m}});Dc(a,b,c,d,e);(b=(b=Ta(I(this.ia,f),function(a){var b;if(b=a.i())if(b=a.i().defaultView())b=a.i().defaultView().Ma;if(b)return l},l))||this.u===m)&&Gc(a)}};function Xc(a,b,c,d,e){for(var f=a.get(b),h=n,j=f.Z.length-1;0<=j;j--){var k=f.Z[j];if((!c||k.type===c)&&(!d||k.Y===d)&&(!e||k.S===e))if(f.Z.splice(j,1),h=l,c&&d)break}(c=h&&!(0<f.Z.length))&&a.remove(b);return c}Uc.prototype.xb=function(a,b,c,d){var e=I(this.ia,a.path).i();return e===m?m:Yc(this,e,a,b,c,d)};
function Yc(a,b,c,d,e,f){var h=b.path(),h=I(a.ia,h),c=c?c.ua():m,j=[];c&&"default"!==c?Xc(b,c,d,e,f)&&j.push(c):ib(b.keys(),function(a){Xc(b,a,d,e,f)&&j.push(a)});b.e()&&J(h,m);c=Vc(h);if(0<j.length&&!c){for(var k=h,o=h.parent(),c=n;!c&&o;){var r=o.i();if(r){K(!Qc(r));var x=k.name(),u=n;S(r.set,function(a){u=a.Ib(x)||u});u&&(c=l)}k=o;o=o.parent()}k=m;if(!Qc(b)){o=b.ga;b.ga=m;var w=[],L=function(b){var c=b.i();c&&Pc(c)?(w.push(c.path()),c.ga==m&&c.setActive(Wc(a,c))):(c&&c.ga==m&&c.setActive(Wc(a,
c)),b.z(L))};L(h);k=w;o&&o()}return c?m:k}return m}function Zc(a,b,c){Sa(I(a.ia,b),function(a){(a=a.i())&&S(a.set,function(a){Gc(a)})},c,l)}function Y(a,b,c){function d(a){for(var b=0;b<c.length;++b)if(c[b].contains(a))return l;return n}var e=a.jc,f=a.g.xa;a.jc=f;var h=b.toString();Jc(e,f,b,a.ia,function(b,c,e){if(b.toString().substring(0,h.length)===h){var f=d(b);f&&Zc(a,b,n);a.tb(b,c,e);f&&Zc(a,b,l)}else a.tb(b,c,e)});d(b)&&Zc(a,b,l)}
Uc.prototype.tb=function(a,b,c){a=I(this.ia,a).i();a!==m&&S(a.set,function(a){a.tb(b,c)})};function Vc(a){return Ta(a,function(a){return a.i()&&Qc(a.i())})}
function Wc(a,b){if(a.u){var c=b.keys(),d=a.u,e=function(d){"ok"!==d?(Pb("on() or once() for "+b.path().toString()+" failed: "+d),b&&S(b.set,function(a){for(var b=0;b<a.Z.length;b++){var c=a.Z[b];c.cancel&&(c.S?v(c.cancel,c.S):c.cancel)()}}),Yc(a,b)):ib(c,function(a){(a=b.get(a))&&Gc(a)})},f=b.toString(),h=b.path().toString();d.X[h]=d.X[h]||{};K(!d.X[h][f],"listen() called twice for same path/queryId.");d.X[h][f]={Ha:b.Ha(),F:e};d.aa&&pc(d,h,f,b.Ha(),e);return v(a.u.uc,a.u,b.path(),b.toString(),b.Ha())}return ca}
Uc.prototype.Ka=function(a,b,c,d){var e={};S(b.set,function(b){b=b.Ka(a,c,d);S(b,function(a,b){e[b]=C(e,b)?e:a})});c.I()||c.z(function(a){C(e,a)||(e[a]=n)});return e};function $c(a,b,c,d,e,f){var h=b.path();if(f!==m){var j=[];d.I()||d.z(function(a,b){j.push({path:h.A(a),sa:b});delete f[a]});S(f,function(a,b){j.push({path:h.A(b),sa:O})});return j}var b=a.Ka(h,b,d,e),k=O,o=[];S(b,function(b,f){var h=new F(f);b?k=k.B(f,d.C(h)):o=o.concat(ad(a,d.C(h),I(c,h),e))});return[{path:h,sa:k}].concat(o)}
function bd(a,b,c,d,e){for(var f=I(a.ia,b),h=f.parent(),j=n;!j&&h!==m;){var k=h.i();k!==m&&(Pc(k)?j=l:(k=a.Ka(b,k,c,d),f=f.name(),sa(k,f)&&(j=l)));f=h;h=h.parent()}if(j)return[{path:b,sa:c}];h=I(a.ia,b);j=h.i();return j!==m?Pc(j)?[{path:b,sa:c}]:$c(a,j,h,c,d,e):ad(a,c,h,d)}function ad(a,b,c,d){var e=c.i();if(e!==m)return Pc(e)?[{path:c.path(),sa:b}]:$c(a,e,c,b,d,m);if(b.I())return[];var f=[];b.z(function(b,e){var k=new F(b);f=f.concat(ad(a,e,I(c,k),d))});return f};function cd(a){this.K=a;this.u=new mc(this.K,v(this.nb,this),v(this.Gc,this),v(this.Hc,this));this.Bb=new Qa;this.g=new wc;this.N=new Uc(this.u,this.g.qa);this.fc=new vc;this.Jb=new Uc(m,this.fc);dd(this,n)}q=cd.prototype;q.toString=function(){return(this.K.Ob?"https://":"http://")+this.K.host};q.name=function(){return this.K.ib};
q.nb=function(a,b,c){var d=[],e=m;if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new F(a.substring(0,a.length-9)),b!==m&&Ga.test(b)&&(b=Number(b)),c=U(this.g.pa,a).Eb(b),d.push(a);else if(c){var e=b,a=new F(a),c=U(this.g.pa,a),f;for(f in b){var h=Q(b[f]),c=c.B(f,h);d.push(a.A(f))}}else a=new F(a),c=Q(b),d.push(a);e=bd(this.N,a,c,this.g.J,e);b=n;for(f=0;f<e.length;++f){var c=e[f],h=this.g,j=c.path;V(h.pa,j,c.sa);b=xc(h,j)||b}b&&(a=ed(this,a),fd(this,a),a=a.path());Y(this.N,a,d)};
q.Gc=function(){dd(this,l)};q.Hc=function(){dd(this,n)};function dd(a,b){var c=new F("/.info/connected");V(a.fc,c,Q(b));Y(a.Jb,c,[c])}q.Ja=function(a,b){this.u.Ja(a,b)};q.bb=function(){this.u.bb()};
q.Ab=function(a,b,c,d){c!==m&&Ga.test(c)&&(c=Number(c));this.c("set",{path:a.toString(),value:b});var b=Q(b,c),c=bd(this.N,a,b,this.g.J,m),e=this.g.set(a,c),f=this;this.u.put(a.toString(),b.W(l),function(b){var c="ok"===b;zc(f.g,e);c||(Pb("set at "+a+" failed: "+b),xc(f.g,a),b=ed(f,a),fd(f,b),Y(f.N,b.path(),[]));d&&d(c)});b=ed(this,a);gd(this,a);fd(this,b);Y(this.N,b.path(),[a])};
q.update=function(a,b,c){this.c("update",{path:a.toString(),value:b});var d=U(this.g.qa,a),e=l,f=[],h;for(h in b){var e=n,j=Q(b[h]),d=d.B(h,j);f.push(a.A(h))}if(e)Lb("update() called with empty data.  Don't do anything."),c&&c(l);else{var d=bd(this.N,a,d,this.g.J,b),k=this.g.set(a,d),o=this;tc(this.u,"m",a.toString(),b,function(b){K("ok"===b||"permission_denied"===b,"merge at "+a+" failed.");b="ok"===b;zc(o.g,k);c&&c(b)},i);b=ed(this,a);gd(this,a);fd(this,b);Y(this.N,b.path(),f)}};
q.Rb=function(a,b,c){this.c("setPriority",{path:a.toString(),na:b});var d=U(this.g.J,a).Eb(b),d=bd(this.N,a,d,this.g.J,m),e=this.g.set(a,d),f=this;this.u.put(a.toString()+"/.priority",b,function(a){a="ok"===a;zc(f.g,e);c&&c(a)});a=ed(this,a);fd(this,a);Y(this.N,a.path(),[])};q.zb=function(a,b){this.u.Qa(a.toString(),b)};q.cb=function(a,b,c,d,e){".info"===D(a.path)?this.Jb.cb(a,b,c,d,e):this.N.cb(a,b,c,d,e)};
q.xb=function(a,b,c,d){if(".info"===D(a.path))this.Jb.xb(a,b,c,d);else if(b=this.N.xb(a,b,c,d),b!==m){for(var c=this.g,a=a.path,d=[],e=0;e<b.length;++e)d[e]=U(c.pa,b[e]);V(c.pa,a,O);for(e=0;e<b.length;++e)V(c.pa,b[e],d[e])}};q.Ea=function(){this.u.Ea()};q.Ya=function(){this.u.Ya()};q.c=function(){Lb("r:"+this.u.id+":",arguments)};function hd(a,b){var c=new X(a,b);return new R(U(a.g.qa,b),c)};function gd(a,b){var c=I(a.Bb,b);Ta(c,function(b){id(a,b)});id(a,c);Sa(c,function(b){id(a,b)})}function id(a,b){var c=b.i();if(c!==m){for(var d=-1,e=[],f=0;f<c.length;f++)if(2===c[f].status)K(d===f-1,"All SENT items should be at beginning of queue."),d=f,c[f].status=4,c[f].Vb="set";else if(c[f].Db(),c[f].F){var h=hd(a,b.path());e.push(v(c[f].F,m,n,h))}-1===d?J(b,m):c.length=d+1;for(f=0;f<e.length;f++)e[f]()}}
function jd(a,b){var c=b||a.Bb;b||kd(a,c);if(!c.e())if(c.i()!==m){var d=ld(a,c);if(0!==d.length){var e=c.path();if(2!==d[0].status&&4!==d[0].status){for(var f=0;f<d.length;f++)K(1===d[f].status,"tryToSendTransactionForNode_: items in queue should all be run."),d[f].status=2,d[f].qc++;var h=U(a.g.J,e).hash();V(a.g.J,e,U(a.g.qa,e));var j=U(a.g.J,e).W(l),k=Eb();J(I(a.g.Va,e),k);a.u.put(e.toString(),j,function(b){a.c("transaction put response",{path:e.toString(),status:b});var h=I(a.g.Va,e),j=h.i();K(j!==
m,"tryToSendTransactionsForNode_: pendingPut should not be null.");j===k&&(J(h,m),V(a.g.J,e,U(a.g.pa,e)));if("ok"===b){b=[];for(f=0;f<d.length;f++)d[f].status=3,d[f].F&&(h=hd(a,d[f].path),b.push(v(d[f].F,m,l,h))),d[f].Db();kd(a,c);jd(a);for(f=0;f<b.length;f++)b[f]()}else{if("datastale"===b)for(f=0;f<d.length;f++)d[f].status=4===d[f].status?5:1;else{Pb("transaction at "+e+" failed: "+b);for(f=0;f<d.length;f++)d[f].status=5,d[f].Vb=b}b=ed(a,e);fd(a,b);Y(a.N,b.path(),[e])}},h)}}}else c.z(function(b){jd(a,
b)})}
function fd(a,b){var c=b.path();V(a.g.qa,c,U(a.g.J,c));var d=ld(a,b);if(0!==d.length){for(var e=U(a.g.qa,c),f=[],h=0;h<d.length;h++){var j=Oa(c,d[h].path),k=n,o;K(j!==m,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[h].status)k=l,o=d[h].Vb;else if(1===d[h].status)if(25<=d[h].qc)k=l,o="maxretry";else{var r=d[h].update(e.C(j).W());s(r)?(ya("transaction failed: Data returned ",r),e=e.Ia(j,Q(r))):(k=l,o="nodata")}k&&(d[h].Db(),d[h].status=3,d[h].F&&(k=new X(a,d[h].path),j=new R(e.C(j),
k),f.push(v(d[h].F,m,n,j,o))))}d=U(a.g.J,c).j();V(a.g.qa,c,e.Eb(d));jd(a);for(h=0;h<f.length;h++)f[h]()}}function ed(a,b){for(var c,d=a.Bb;(c=D(b))!==m&&d.i()===m;)d=I(d,c),b=Ma(b);return d}function ld(a,b){var c=[];md(a,b,c);c.sort(function(a,b){return a.mc-b.mc});return c}function md(a,b,c){var d=b.i();if(d!==m)for(var e=0;e<d.length;e++)c.push(d[e]);b.z(function(b){md(a,b,c)})}
function kd(a,b){var c=b.i();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;J(b,0<c.length?c:m)}b.z(function(b){kd(a,b)})};function Z(){this.va={}}Z.dc=function(){return Z.gc?Z.gc:Z.gc=new Z};Z.prototype.Ea=function(){for(var a in this.va)this.va[a].Ea()};Z.prototype.interrupt=Z.prototype.Ea;Z.prototype.Ya=function(){for(var a in this.va)this.va[a].Ya()};Z.prototype.resume=Z.prototype.Ya;var $={Nc:function(){return Z.dc().va}};$.repos=$.Nc;$.Dc=function(a){var b=P.prototype.hash;P.prototype.hash=a;return function(){P.prototype.hash=b}};$.hijackHash=$.Dc;$.ua=function(a){return a.ua()};$.queryIdentifier=$.ua;$.Fc=function(a){return a.n.u.X};$.listens=$.Fc;$.Lc=function(a){return a.n.u.Xa};$.refConnection=$.Lc;$.wc=mc;$.DataConnection=$.wc;mc.prototype.sendRequest=mc.prototype.ya;mc.prototype.interrupt=mc.prototype.Ea;$.xc=T;$.RealTimeConnection=$.xc;T.prototype.sendRequest=T.prototype.Qb;
T.prototype.close=T.prototype.close;$.vc=pb;$.ConnectionTarget=$.vc;$.Cc=function(){$b=l};$.forceLongPolling=$.Cc;$.Rc=function(a,b){a.n.u.Pb=b};$.setSecurityDebugCallback=$.Rc;var nd,od=0,pd=[];nd=function(){var a=(new Date).getTime()+Tb,b=a===od;od=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);K(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===pd[d];d--)pd[d]=0;pd[d]++}else for(d=0;12>d;d++)pd[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(pd[d]);K(20===a.length,"NextPushId: Length should be 20.");return a};function X(){var a,b,c;if(arguments[0]instanceof cd)c=arguments[0],a=arguments[1];else{z("new Firebase",1,2,arguments.length);a=arguments[0];var d="",e="",f=l;b="";if(t(a)){d=a.indexOf("//");0<=d&&(f="http:"!==a.substring(0,d),a=a.substring(d+2));var h=a.indexOf("/");-1===h&&(h=a.length);d=a.substring(0,h);a=a.substring(h+1);var h=a.indexOf("/"),j=d.split(".");3==j.length?("firebase"===j[1]?(Pb(d+" is deprecated. Please use <YOUR FIREBASE>.firebaseio.com instead"),0<h?(e=a.substring(0,h),b=Qb(a.substring(h))):
(e=a,b="/"),j[0]=e,j[1]="firebaseio",d=j.join(".")):(e=j[0],b=Qb("/"+a)),e=e.toLowerCase()):e=m}f||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&Pb("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new pb(d,f,e);b=new F(b);f=b.toString();if(!(d=!t(a.host)))if(!(d=0===a.host.length))if(!(d=!wa(a.ib)))if(d=0!==f.length)f&&(f=f.replace(/^\/*\.info(\/|$)/,"/")),d=!(t(f)&&0!==f.length&&
!va.test(f));d&&g(Error(A("new Firebase",1,n)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Z?c=arguments[1]:g(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Z.dc();f=(a.Ob?"https://":"http://")+a.host;d=sa(c.va,f);d||(d=new cd(a),c.va[f]=d);c=d;a=b}E.call(this,c,a)}ja(X,E);var qd=X,rd=["Firebase"],sd=ba;!(rd[0]in sd)&&sd.execScript&&sd.execScript("var "+rd[0]);
for(var td;rd.length&&(td=rd.shift());)!rd.length&&s(qd)?sd[td]=qd:sd=sd[td]?sd[td]:sd[td]={};X.prototype.name=function(){z("Firebase.name",0,0,arguments.length);return this.path.e()?m:Na(this.path)};X.prototype.name=X.prototype.name;X.prototype.A=function(a){z("Firebase.child",1,1,arguments.length);if(fa(a))a=String(a);else if(!(a instanceof F))if(D(this.path)===m){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Ea("Firebase.child",b)}else Ea("Firebase.child",a);return new X(this.n,this.path.A(a))};
X.prototype.child=X.prototype.A;X.prototype.parent=function(){z("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===m?m:new X(this.n,a)};X.prototype.parent=X.prototype.parent;X.prototype.toString=function(){z("Firebase.toString",0,0,arguments.length);var a;if(this.parent()===m)a=this.n.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};X.prototype.toString=X.prototype.toString;
X.prototype.set=function(a,b){z("Firebase.set",1,2,arguments.length);Fa("Firebase.set",this.path);xa("Firebase.set",a,n);B("Firebase.set",2,b,l);return this.n.Ab(this.path,a,m,b)};X.prototype.set=X.prototype.set;
X.prototype.update=function(a,b){z("Firebase.update",1,2,arguments.length);Fa("Firebase.update",this.path);ga(a)||g(Error(A("Firebase.update",1,n)+" must be an object containing the children to replace."));xa("Firebase.update",a,n);B("Firebase.update",2,b,l);return this.n.update(this.path,a,b)};X.prototype.update=X.prototype.update;
X.prototype.Ab=function(a,b,c){z("Firebase.setWithPriority",2,3,arguments.length);Fa("Firebase.setWithPriority",this.path);xa("Firebase.setWithPriority",a,n);Ba("Firebase.setWithPriority",2,b,n);B("Firebase.setWithPriority",3,c,l);(".length"===this.name()||".keys"===this.name())&&g("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.n.Ab(this.path,a,b,c)};X.prototype.setWithPriority=X.prototype.Ab;
X.prototype.remove=function(a){z("Firebase.remove",0,1,arguments.length);Fa("Firebase.remove",this.path);B("Firebase.remove",1,a,l);this.set(m,a)};X.prototype.remove=X.prototype.remove;
X.prototype.transaction=function(a,b){function c(){}z("Firebase.transaction",1,2,arguments.length);Fa("Firebase.transaction",this.path);B("Firebase.transaction",1,a,n);B("Firebase.transaction",2,b,l);(".length"===this.name()||".keys"===this.name())&&g("Firebase.transaction failed: "+this.name()+" is a read-only object.");var d=this.n,e=this.path;d.c("transaction on "+e);var f=new X(d,e);f.Kb("value",c);var h={path:e,update:a,F:b,mc:Eb(),qc:0,Db:function(){f.lb("value",c)}},j=d.g.qa,k=h.update(U(j,
e).W());if(s(k)){ya("transaction failed: Data returned ",k);var o=U(d.g.J,e).j();V(j,e,Q(k,o));Y(d.N,e,[e]);h.status=1;e=I(d.Bb,e);j=e.i()||[];j.push(h);J(e,j);jd(d)}else h.Db(),h.F&&(d=hd(d,e),h.F(n,d))};X.prototype.transaction=X.prototype.transaction;X.prototype.Rb=function(a,b){z("Firebase.setPriority",1,2,arguments.length);Fa("Firebase.setPriority",this.path);Ba("Firebase.setPriority",1,a,n);B("Firebase.setPriority",2,b,l);a!==m&&Ga.test(a)&&(a=Number(a));this.n.Rb(this.path,a,b)};
X.prototype.setPriority=X.prototype.Rb;X.prototype.push=function(a,b){z("Firebase.push",0,2,arguments.length);Fa("Firebase.push",this.path);xa("Firebase.push",a,l);B("Firebase.push",2,b,l);var c=nd(),c=this.A(c);"undefined"!==typeof a&&a!==m&&c.set(a,b);return c};X.prototype.push=X.prototype.push;X.prototype.Mc=function(){z("Firebase.removeOnDisconnect",0,0,arguments.length);this.n.zb(this.path,m)};X.prototype.removeOnDisconnect=X.prototype.Mc;
X.prototype.zb=function(a){z("Firebase.setOnDisconnect",1,1,arguments.length);xa("Firebase.setOnDisconnect",a,n);this.n.zb(this.path,a)};X.prototype.setOnDisconnect=X.prototype.zb;X.prototype.Ja=function(a,b){z("Firebase.auth",1,2,arguments.length);t(a)||g(Error(A("Firebase.auth",1,n)+"must be a valid credential (a string)."));B("Firebase.auth",2,b,l);this.n.Ja(a,b)};X.prototype.auth=X.prototype.Ja;X.prototype.bb=function(){this.n.bb()};X.prototype.unauth=X.prototype.bb;
function Mb(a,b){K(!b||a===l||a===n,"Can't turn on custom loggers persistently.");a===l?("undefined"!==typeof console&&("function"===typeof console.log?Jb=v(console.log,console):"object"===typeof console.log&&(Jb=function(a){console.log(a)})),b&&N.setItem("logging_enabled","true")):a?Jb=a:(Jb=m,N.removeItem("logging_enabled"))}X.enableLogging=Mb;X.TEST_HOOKS=$;X.Context=Z;})();
exports.Firebase = Firebase;
